# Generated by default/object.tt
package Paws::IoTFleetWise::CollectionScheme;
  use Moose;
  has ConditionBasedCollectionScheme => (is => 'ro', isa => 'Paws::IoTFleetWise::ConditionBasedCollectionScheme', request_name => 'conditionBasedCollectionScheme', traits => ['NameInRequest']);
  has TimeBasedCollectionScheme => (is => 'ro', isa => 'Paws::IoTFleetWise::TimeBasedCollectionScheme', request_name => 'timeBasedCollectionScheme', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::IoTFleetWise::CollectionScheme

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::IoTFleetWise::CollectionScheme object:

  $service_obj->Method(Att1 => { ConditionBasedCollectionScheme => $value, ..., TimeBasedCollectionScheme => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::IoTFleetWise::CollectionScheme object:

  $result = $service_obj->Method(...);
  $result->Att1->ConditionBasedCollectionScheme

=head1 DESCRIPTION

Specifies what data to collect and how often or when to collect it.

=head1 ATTRIBUTES


=head2 ConditionBasedCollectionScheme => L<Paws::IoTFleetWise::ConditionBasedCollectionScheme>

Information about a collection scheme that uses a simple logical
expression to recognize what data to collect.


=head2 TimeBasedCollectionScheme => L<Paws::IoTFleetWise::TimeBasedCollectionScheme>

Information about a collection scheme that uses a time period to decide
how often to collect data.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::IoTFleetWise>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

