# Generated by default/object.tt
package Paws::IoTFleetWise::StructuredMessageListDefinition;
  use Moose;
  has Capacity => (is => 'ro', isa => 'Int', request_name => 'capacity', traits => ['NameInRequest']);
  has ListType => (is => 'ro', isa => 'Str', request_name => 'listType', traits => ['NameInRequest'], required => 1);
  has MemberType => (is => 'ro', isa => 'Paws::IoTFleetWise::StructuredMessage', request_name => 'memberType', traits => ['NameInRequest'], required => 1);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::IoTFleetWise::StructuredMessageListDefinition

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::IoTFleetWise::StructuredMessageListDefinition object:

  $service_obj->Method(Att1 => { Capacity => $value, ..., Name => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::IoTFleetWise::StructuredMessageListDefinition object:

  $result = $service_obj->Method(...);
  $result->Att1->Capacity

=head1 DESCRIPTION

Represents a list type node of the complex data structure.

=head1 ATTRIBUTES


=head2 Capacity => Int

The capacity of the structured message list definition when the list
type is C<FIXED_CAPACITY> or C<DYNAMIC_BOUNDED_CAPACITY>.


=head2 B<REQUIRED> ListType => Str

The type of list of the structured message list definition.


=head2 B<REQUIRED> MemberType => L<Paws::IoTFleetWise::StructuredMessage>

The member type of the structured message list definition.


=head2 B<REQUIRED> Name => Str

The name of the structured message list definition.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::IoTFleetWise>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

