# Generated by default/object.tt
package Paws::GuardDuty::CoverageResourceDetails;
  use Moose;
  has Ec2InstanceDetails => (is => 'ro', isa => 'Paws::GuardDuty::CoverageEc2InstanceDetails', request_name => 'ec2InstanceDetails', traits => ['NameInRequest']);
  has EcsClusterDetails => (is => 'ro', isa => 'Paws::GuardDuty::CoverageEcsClusterDetails', request_name => 'ecsClusterDetails', traits => ['NameInRequest']);
  has EksClusterDetails => (is => 'ro', isa => 'Paws::GuardDuty::CoverageEksClusterDetails', request_name => 'eksClusterDetails', traits => ['NameInRequest']);
  has ResourceType => (is => 'ro', isa => 'Str', request_name => 'resourceType', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::GuardDuty::CoverageResourceDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GuardDuty::CoverageResourceDetails object:

  $service_obj->Method(Att1 => { Ec2InstanceDetails => $value, ..., ResourceType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GuardDuty::CoverageResourceDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->Ec2InstanceDetails

=head1 DESCRIPTION

Information about the resource for each individual EKS cluster.

=head1 ATTRIBUTES


=head2 Ec2InstanceDetails => L<Paws::GuardDuty::CoverageEc2InstanceDetails>

Information about the Amazon EC2 instance assessed for runtime
coverage.


=head2 EcsClusterDetails => L<Paws::GuardDuty::CoverageEcsClusterDetails>

Information about the Amazon ECS cluster that is assessed for runtime
coverage.


=head2 EksClusterDetails => L<Paws::GuardDuty::CoverageEksClusterDetails>

EKS cluster details involved in the coverage statistics.


=head2 ResourceType => Str

The type of Amazon Web Services resource.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GuardDuty>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

