# Generated by default/object.tt
package Paws::GuardDuty::OrganizationKubernetesConfigurationResult;
  use Moose;
  has AuditLogs => (is => 'ro', isa => 'Paws::GuardDuty::OrganizationKubernetesAuditLogsConfigurationResult', request_name => 'auditLogs', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::GuardDuty::OrganizationKubernetesConfigurationResult

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GuardDuty::OrganizationKubernetesConfigurationResult object:

  $service_obj->Method(Att1 => { AuditLogs => $value, ..., AuditLogs => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GuardDuty::OrganizationKubernetesConfigurationResult object:

  $result = $service_obj->Method(...);
  $result->Att1->AuditLogs

=head1 DESCRIPTION

The current configuration of all Kubernetes data sources for the
organization.

=head1 ATTRIBUTES


=head2 B<REQUIRED> AuditLogs => L<Paws::GuardDuty::OrganizationKubernetesAuditLogsConfigurationResult>

The current configuration of Kubernetes audit logs as a data source for
the organization.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GuardDuty>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

