# Generated by default/object.tt
package Paws::GuardDuty::RdsLimitlessDbDetails;
  use Moose;
  has DbClusterIdentifier => (is => 'ro', isa => 'Str', request_name => 'dbClusterIdentifier', traits => ['NameInRequest']);
  has DbShardGroupArn => (is => 'ro', isa => 'Str', request_name => 'dbShardGroupArn', traits => ['NameInRequest']);
  has DbShardGroupIdentifier => (is => 'ro', isa => 'Str', request_name => 'dbShardGroupIdentifier', traits => ['NameInRequest']);
  has DbShardGroupResourceId => (is => 'ro', isa => 'Str', request_name => 'dbShardGroupResourceId', traits => ['NameInRequest']);
  has Engine => (is => 'ro', isa => 'Str', request_name => 'engine', traits => ['NameInRequest']);
  has EngineVersion => (is => 'ro', isa => 'Str', request_name => 'engineVersion', traits => ['NameInRequest']);
  has Tags => (is => 'ro', isa => 'ArrayRef[Paws::GuardDuty::Tag]', request_name => 'tags', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::GuardDuty::RdsLimitlessDbDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GuardDuty::RdsLimitlessDbDetails object:

  $service_obj->Method(Att1 => { DbClusterIdentifier => $value, ..., Tags => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GuardDuty::RdsLimitlessDbDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->DbClusterIdentifier

=head1 DESCRIPTION

Contains information about the resource type C<RDSLimitlessDB> that is
involved in a GuardDuty finding.

=head1 ATTRIBUTES


=head2 DbClusterIdentifier => Str

The name of the database cluster that is a part of the Limitless
Database.


=head2 DbShardGroupArn => Str

The Amazon Resource Name (ARN) that identifies the DB shard group.


=head2 DbShardGroupIdentifier => Str

The name associated with the Limitless DB shard group.


=head2 DbShardGroupResourceId => Str

The resource identifier of the DB shard group within the Limitless
Database.


=head2 Engine => Str

The database engine of the database instance involved in the finding.


=head2 EngineVersion => Str

The version of the database engine.


=head2 Tags => ArrayRef[L<Paws::GuardDuty::Tag>]

Information about the tag key-value pair.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GuardDuty>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

