# Generated by default/object.tt
package Paws::AutoScaling::CapacityReservationSpecification;
  use Moose;
  has CapacityReservationPreference => (is => 'ro', isa => 'Str');
  has CapacityReservationTarget => (is => 'ro', isa => 'Paws::AutoScaling::CapacityReservationTarget');

1;

### main pod documentation begin ###

=head1 NAME

Paws::AutoScaling::CapacityReservationSpecification

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::AutoScaling::CapacityReservationSpecification object:

  $service_obj->Method(Att1 => { CapacityReservationPreference => $value, ..., CapacityReservationTarget => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::AutoScaling::CapacityReservationSpecification object:

  $result = $service_obj->Method(...);
  $result->Att1->CapacityReservationPreference

=head1 DESCRIPTION

Describes the Capacity Reservation preference and targeting options. If
you specify C<open> or C<none> for C<CapacityReservationPreference>, do
not specify a C<CapacityReservationTarget>.

=head1 ATTRIBUTES


=head2 CapacityReservationPreference => Str

The capacity reservation preference. The following options are
available:

=over

=item *

C<capacity-reservations-only> - Auto Scaling will only launch instances
into a Capacity Reservation or Capacity Reservation resource group. If
capacity isn't available, instances will fail to launch.

=item *

C<capacity-reservations-first> - Auto Scaling will try to launch
instances into a Capacity Reservation or Capacity Reservation resource
group first. If capacity isn't available, instances will run in
On-Demand capacity.

=item *

C<none> - Auto Scaling will not launch instances into a Capacity
Reservation. Instances will run in On-Demand capacity.

=item *

C<default> - Auto Scaling uses the Capacity Reservation preference from
your launch template or an open Capacity Reservation.

=back



=head2 CapacityReservationTarget => L<Paws::AutoScaling::CapacityReservationTarget>

Describes a target Capacity Reservation or Capacity Reservation
resource group.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::AutoScaling>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

