
package Paws::Athena::ListNotebookMetadata;
  use Moose;
  has Filters => (is => 'ro', isa => 'Paws::Athena::FilterDefinition');
  has MaxResults => (is => 'ro', isa => 'Int');
  has NextToken => (is => 'ro', isa => 'Str');
  has WorkGroup => (is => 'ro', isa => 'Str', required => 1);

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'ListNotebookMetadata');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::Athena::ListNotebookMetadataOutput');
  class_has _result_key => (isa => 'Str', is => 'ro');
1;

### main pod documentation begin ###

=head1 NAME

Paws::Athena::ListNotebookMetadata - Arguments for method ListNotebookMetadata on L<Paws::Athena>

=head1 DESCRIPTION

This class represents the parameters used for calling the method ListNotebookMetadata on the
L<Amazon Athena|Paws::Athena> service. Use the attributes of this class
as arguments to method ListNotebookMetadata.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to ListNotebookMetadata.

=head1 SYNOPSIS

    my $athena = Paws->service('Athena');
    my $ListNotebookMetadataOutput = $athena->ListNotebookMetadata(
      WorkGroup => 'MyWorkGroupName',
      Filters   => {
        Name => 'MyNotebookName',    # min: 1, max: 255; OPTIONAL
      },    # OPTIONAL
      MaxResults => 1,            # OPTIONAL
      NextToken  => 'MyToken',    # OPTIONAL
    );

    # Results:
    my $NextToken = $ListNotebookMetadataOutput->NextToken;
    my $NotebookMetadataList =
      $ListNotebookMetadataOutput->NotebookMetadataList;

    # Returns a L<Paws::Athena::ListNotebookMetadataOutput> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/athena/ListNotebookMetadata>

=head1 ATTRIBUTES


=head2 Filters => L<Paws::Athena::FilterDefinition>

Search filter string.



=head2 MaxResults => Int

Specifies the maximum number of results to return.



=head2 NextToken => Str

A token generated by the Athena service that specifies where to
continue pagination if a previous request was truncated.



=head2 B<REQUIRED> WorkGroup => Str

The name of the Spark enabled workgroup to retrieve notebook metadata
for.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method ListNotebookMetadata in L<Paws::Athena>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

