# Generated by default/object.tt
package Paws::Athena::QueryRuntimeStatisticsRows;
  use Moose;
  has InputBytes => (is => 'ro', isa => 'Int');
  has InputRows => (is => 'ro', isa => 'Int');
  has OutputBytes => (is => 'ro', isa => 'Int');
  has OutputRows => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Athena::QueryRuntimeStatisticsRows

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Athena::QueryRuntimeStatisticsRows object:

  $service_obj->Method(Att1 => { InputBytes => $value, ..., OutputRows => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Athena::QueryRuntimeStatisticsRows object:

  $result = $service_obj->Method(...);
  $result->Att1->InputBytes

=head1 DESCRIPTION

Statistics such as input rows and bytes read by the query, rows and
bytes output by the query, and the number of rows written by the query.

=head1 ATTRIBUTES


=head2 InputBytes => Int

The number of bytes read to execute the query.


=head2 InputRows => Int

The number of rows read to execute the query.


=head2 OutputBytes => Int

The number of bytes returned by the query.


=head2 OutputRows => Int

The number of rows returned by the query.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Athena>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

