# Generated by default/object.tt
package Paws::GroundStation::EphemerisDescription;
  use Moose;
  has EphemerisData => (is => 'ro', isa => 'Str', request_name => 'ephemerisData', traits => ['NameInRequest']);
  has SourceS3Object => (is => 'ro', isa => 'Paws::GroundStation::S3Object', request_name => 'sourceS3Object', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::GroundStation::EphemerisDescription

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GroundStation::EphemerisDescription object:

  $service_obj->Method(Att1 => { EphemerisData => $value, ..., SourceS3Object => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GroundStation::EphemerisDescription object:

  $result = $service_obj->Method(...);
  $result->Att1->EphemerisData

=head1 DESCRIPTION

Description of ephemeris.

=head1 ATTRIBUTES


=head2 EphemerisData => Str

Supplied ephemeris data.


=head2 SourceS3Object => L<Paws::GroundStation::S3Object>

Source S3 object used for the ephemeris.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GroundStation>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

