# Generated by default/object.tt
package Paws::S3Control::NoncurrentVersionExpiration;
  use Moose;
  has NewerNoncurrentVersions => (is => 'ro', isa => 'Int');
  has NoncurrentDays => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::S3Control::NoncurrentVersionExpiration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::S3Control::NoncurrentVersionExpiration object:

  $service_obj->Method(Att1 => { NewerNoncurrentVersions => $value, ..., NoncurrentDays => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::S3Control::NoncurrentVersionExpiration object:

  $result = $service_obj->Method(...);
  $result->Att1->NewerNoncurrentVersions

=head1 DESCRIPTION

The container of the noncurrent version expiration.

=head1 ATTRIBUTES


=head2 NewerNoncurrentVersions => Int

Specifies how many noncurrent versions S3 on Outposts will retain. If
there are this many more recent noncurrent versions, S3 on Outposts
will take the associated action. For more information about noncurrent
versions, see Lifecycle configuration elements
(https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html)
in the I<Amazon S3 User Guide>.


=head2 NoncurrentDays => Int

Specifies the number of days an object is noncurrent before Amazon S3
can perform the associated action. For information about the noncurrent
days calculations, see How Amazon S3 Calculates When an Object Became
Noncurrent
(https://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html#non-current-days-calculations)
in the I<Amazon S3 User Guide>.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::S3Control>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

