# Generated by default/object.tt
package Paws::OpenSearch::AuthorizedPrincipal;
  use Moose;
  has Principal => (is => 'ro', isa => 'Str');
  has PrincipalType => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::AuthorizedPrincipal

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::AuthorizedPrincipal object:

  $service_obj->Method(Att1 => { Principal => $value, ..., PrincipalType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::AuthorizedPrincipal object:

  $result = $service_obj->Method(...);
  $result->Att1->Principal

=head1 DESCRIPTION

Information about an Amazon Web Services account or service that has
access to an Amazon OpenSearch Service domain through the use of an
interface VPC endpoint.

=head1 ATTRIBUTES


=head2 Principal => Str

The IAM principal
(https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html)
that is allowed access to the domain.


=head2 PrincipalType => Str

The type of principal.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

