# Generated by default/object.tt
package Paws::OpenSearch::AutoTuneDetails;
  use Moose;
  has ScheduledAutoTuneDetails => (is => 'ro', isa => 'Paws::OpenSearch::ScheduledAutoTuneDetails');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::AutoTuneDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::AutoTuneDetails object:

  $service_obj->Method(Att1 => { ScheduledAutoTuneDetails => $value, ..., ScheduledAutoTuneDetails => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::AutoTuneDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->ScheduledAutoTuneDetails

=head1 DESCRIPTION

Specifies details about a scheduled Auto-Tune action. For more
information, see Auto-Tune for Amazon OpenSearch Service
(https://docs.aws.amazon.com/opensearch-service/latest/developerguide/auto-tune.html).

=head1 ATTRIBUTES


=head2 ScheduledAutoTuneDetails => L<Paws::OpenSearch::ScheduledAutoTuneDetails>

Container for details about a scheduled Auto-Tune action.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

