# Generated by default/object.tt
package Paws::OpenSearch::AutoTuneOptionsOutput;
  use Moose;
  has ErrorMessage => (is => 'ro', isa => 'Str');
  has State => (is => 'ro', isa => 'Str');
  has UseOffPeakWindow => (is => 'ro', isa => 'Bool');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::AutoTuneOptionsOutput

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::AutoTuneOptionsOutput object:

  $service_obj->Method(Att1 => { ErrorMessage => $value, ..., UseOffPeakWindow => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::AutoTuneOptionsOutput object:

  $result = $service_obj->Method(...);
  $result->Att1->ErrorMessage

=head1 DESCRIPTION

The Auto-Tune settings for a domain, displayed when enabling or
disabling Auto-Tune.

=head1 ATTRIBUTES


=head2 ErrorMessage => Str

Any errors that occurred while enabling or disabling Auto-Tune.


=head2 State => Str

The current state of Auto-Tune on the domain.


=head2 UseOffPeakWindow => Bool

Whether the domain's off-peak window will be used to deploy Auto-Tune
changes rather than a maintenance schedule.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

