# Generated by default/object.tt
package Paws::OpenSearch::AvailabilityZoneInfo;
  use Moose;
  has AvailabilityZoneName => (is => 'ro', isa => 'Str');
  has AvailableDataNodeCount => (is => 'ro', isa => 'Str');
  has ConfiguredDataNodeCount => (is => 'ro', isa => 'Str');
  has TotalShards => (is => 'ro', isa => 'Str');
  has TotalUnAssignedShards => (is => 'ro', isa => 'Str');
  has ZoneStatus => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::AvailabilityZoneInfo

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::AvailabilityZoneInfo object:

  $service_obj->Method(Att1 => { AvailabilityZoneName => $value, ..., ZoneStatus => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::AvailabilityZoneInfo object:

  $result = $service_obj->Method(...);
  $result->Att1->AvailabilityZoneName

=head1 DESCRIPTION

Information about an Availability Zone on a domain.

=head1 ATTRIBUTES


=head2 AvailabilityZoneName => Str

The name of the Availability Zone.


=head2 AvailableDataNodeCount => Str

The number of data nodes active in the Availability Zone.


=head2 ConfiguredDataNodeCount => Str

The total number of data nodes configured in the Availability Zone.


=head2 TotalShards => Str

The total number of primary and replica shards in the Availability
Zone.


=head2 TotalUnAssignedShards => Str

The total number of primary and replica shards that aren't allocated to
any of the nodes in the Availability Zone.


=head2 ZoneStatus => Str

The current state of the Availability Zone. Current options are
C<Active> and C<StandBy>.

=over

=item *

C<Active> - Data nodes in the Availability Zone are in use.

=item *

C<StandBy> - Data nodes in the Availability Zone are in a standby
state.

=item *

C<NotAvailable> - Unable to retrieve information.

=back




=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

