# Generated by default/object.tt
package Paws::OpenSearch::ClusterConfig;
  use Moose;
  has ColdStorageOptions => (is => 'ro', isa => 'Paws::OpenSearch::ColdStorageOptions');
  has DedicatedMasterCount => (is => 'ro', isa => 'Int');
  has DedicatedMasterEnabled => (is => 'ro', isa => 'Bool');
  has DedicatedMasterType => (is => 'ro', isa => 'Str');
  has InstanceCount => (is => 'ro', isa => 'Int');
  has InstanceType => (is => 'ro', isa => 'Str');
  has MultiAZWithStandbyEnabled => (is => 'ro', isa => 'Bool');
  has NodeOptions => (is => 'ro', isa => 'ArrayRef[Paws::OpenSearch::NodeOption]');
  has WarmCount => (is => 'ro', isa => 'Int');
  has WarmEnabled => (is => 'ro', isa => 'Bool');
  has WarmType => (is => 'ro', isa => 'Str');
  has ZoneAwarenessConfig => (is => 'ro', isa => 'Paws::OpenSearch::ZoneAwarenessConfig');
  has ZoneAwarenessEnabled => (is => 'ro', isa => 'Bool');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::ClusterConfig

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::ClusterConfig object:

  $service_obj->Method(Att1 => { ColdStorageOptions => $value, ..., ZoneAwarenessEnabled => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::ClusterConfig object:

  $result = $service_obj->Method(...);
  $result->Att1->ColdStorageOptions

=head1 DESCRIPTION

Container for the cluster configuration of an OpenSearch Service
domain. For more information, see Creating and managing Amazon
OpenSearch Service domains
(https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html).

=head1 ATTRIBUTES


=head2 ColdStorageOptions => L<Paws::OpenSearch::ColdStorageOptions>

Container for cold storage configuration options.


=head2 DedicatedMasterCount => Int

Number of dedicated master nodes in the cluster. This number must be
greater than 2 and not 4, otherwise you receive a validation exception.


=head2 DedicatedMasterEnabled => Bool

Indicates whether dedicated master nodes are enabled for the
cluster.C<True> if the cluster will use a dedicated master
node.C<False> if the cluster will not.


=head2 DedicatedMasterType => Str

OpenSearch Service instance type of the dedicated master nodes in the
cluster.


=head2 InstanceCount => Int

Number of data nodes in the cluster. This number must be greater than
1, otherwise you receive a validation exception.


=head2 InstanceType => Str

Instance type of data nodes in the cluster.


=head2 MultiAZWithStandbyEnabled => Bool

A boolean that indicates whether a multi-AZ domain is turned on with a
standby AZ. For more information, see Configuring a multi-AZ domain in
Amazon OpenSearch Service
(https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html).


=head2 NodeOptions => ArrayRef[L<Paws::OpenSearch::NodeOption>]

List of node options for the domain.


=head2 WarmCount => Int

The number of warm nodes in the cluster.


=head2 WarmEnabled => Bool

Whether to enable warm storage for the cluster.


=head2 WarmType => Str

The instance type for the cluster's warm nodes.


=head2 ZoneAwarenessConfig => L<Paws::OpenSearch::ZoneAwarenessConfig>

Container for zone awareness configuration options. Only required if
C<ZoneAwarenessEnabled> is C<true>.


=head2 ZoneAwarenessEnabled => Bool

Indicates whether multiple Availability Zones are enabled. For more
information, see Configuring a multi-AZ domain in Amazon OpenSearch
Service
(https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

