# Generated by default/object.tt
package Paws::OpenSearch::DirectQueryDataSource;
  use Moose;
  has DataSourceArn => (is => 'ro', isa => 'Str');
  has DataSourceName => (is => 'ro', isa => 'Str');
  has DataSourceType => (is => 'ro', isa => 'Paws::OpenSearch::DirectQueryDataSourceType');
  has Description => (is => 'ro', isa => 'Str');
  has OpenSearchArns => (is => 'ro', isa => 'ArrayRef[Str|Undef]');
  has TagList => (is => 'ro', isa => 'ArrayRef[Paws::OpenSearch::Tag]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::DirectQueryDataSource

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::DirectQueryDataSource object:

  $service_obj->Method(Att1 => { DataSourceArn => $value, ..., TagList => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::DirectQueryDataSource object:

  $result = $service_obj->Method(...);
  $result->Att1->DataSourceArn

=head1 DESCRIPTION

The configuration details for a data source that can be directly
queried.

=head1 ATTRIBUTES


=head2 DataSourceArn => Str

The unique, system-generated identifier that represents the data
source.


=head2 DataSourceName => Str

A unique, user-defined label to identify the data source within your
OpenSearch Service environment.


=head2 DataSourceType => L<Paws::OpenSearch::DirectQueryDataSourceType>

The supported Amazon Web Services service that is used as the source
for direct queries in OpenSearch Service.


=head2 Description => Str

A description that provides additional context and details about the
data source.


=head2 OpenSearchArns => ArrayRef[Str|Undef]

A list of Amazon Resource Names (ARNs) for the OpenSearch collections
that are associated with the direct query data source.


=head2 TagList => ArrayRef[L<Paws::OpenSearch::Tag>]

A list of tags attached to a direct query data source.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

