# Generated by default/object.tt
package Paws::OpenSearch::PackageAssociationConfiguration;
  use Moose;
  has KeyStoreAccessOption => (is => 'ro', isa => 'Paws::OpenSearch::KeyStoreAccessOption');

1;

### main pod documentation begin ###

=head1 NAME

Paws::OpenSearch::PackageAssociationConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::OpenSearch::PackageAssociationConfiguration object:

  $service_obj->Method(Att1 => { KeyStoreAccessOption => $value, ..., KeyStoreAccessOption => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::OpenSearch::PackageAssociationConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->KeyStoreAccessOption

=head1 DESCRIPTION

The configuration for associating a package with a domain.

=head1 ATTRIBUTES


=head2 KeyStoreAccessOption => L<Paws::OpenSearch::KeyStoreAccessOption>

The configuration parameters to enable accessing the key store required
by the package.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::OpenSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

