# Generated by default/object.tt
package Paws::FIS::ExperimentTemplateExperimentOptions;
  use Moose;
  has AccountTargeting => (is => 'ro', isa => 'Str', request_name => 'accountTargeting', traits => ['NameInRequest']);
  has EmptyTargetResolutionMode => (is => 'ro', isa => 'Str', request_name => 'emptyTargetResolutionMode', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::FIS::ExperimentTemplateExperimentOptions

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::FIS::ExperimentTemplateExperimentOptions object:

  $service_obj->Method(Att1 => { AccountTargeting => $value, ..., EmptyTargetResolutionMode => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::FIS::ExperimentTemplateExperimentOptions object:

  $result = $service_obj->Method(...);
  $result->Att1->AccountTargeting

=head1 DESCRIPTION

Describes the experiment options for an experiment template.

=head1 ATTRIBUTES


=head2 AccountTargeting => Str

The account targeting setting for an experiment template.


=head2 EmptyTargetResolutionMode => Str

The empty target resolution mode for an experiment template.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::FIS>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

