# Generated by default/object.tt
package Paws::SecurityHub::AwsEcsServiceCapacityProviderStrategyDetails;
  use Moose;
  has Base => (is => 'ro', isa => 'Int');
  has CapacityProvider => (is => 'ro', isa => 'Str');
  has Weight => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SecurityHub::AwsEcsServiceCapacityProviderStrategyDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SecurityHub::AwsEcsServiceCapacityProviderStrategyDetails object:

  $service_obj->Method(Att1 => { Base => $value, ..., Weight => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SecurityHub::AwsEcsServiceCapacityProviderStrategyDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->Base

=head1 DESCRIPTION

Strategy item for the capacity provider strategy that the service uses.

=head1 ATTRIBUTES


=head2 Base => Int

The minimum number of tasks to run on the capacity provider. Only one
strategy item can specify a value for C<Base>.

The value must be between 0 and 100000.


=head2 CapacityProvider => Str

The short name of the capacity provider.


=head2 Weight => Int

The relative percentage of the total number of tasks that should use
the capacity provider.

If no weight is specified, the default value is 0. At least one
capacity provider must have a weight greater than 0.

The value can be between 0 and 1000.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SecurityHub>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

