# Generated by default/object.tt
package Paws::SecurityHub::AwsEcsContainerDetails;
  use Moose;
  has Image => (is => 'ro', isa => 'Str');
  has MountPoints => (is => 'ro', isa => 'ArrayRef[Paws::SecurityHub::AwsMountPoint]');
  has Name => (is => 'ro', isa => 'Str');
  has Privileged => (is => 'ro', isa => 'Bool');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SecurityHub::AwsEcsContainerDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SecurityHub::AwsEcsContainerDetails object:

  $service_obj->Method(Att1 => { Image => $value, ..., Privileged => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SecurityHub::AwsEcsContainerDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->Image

=head1 DESCRIPTION

Provides information about an Amazon ECS container.

=head1 ATTRIBUTES


=head2 Image => Str

The image used for the container.


=head2 MountPoints => ArrayRef[L<Paws::SecurityHub::AwsMountPoint>]

The mount points for data volumes in your container.


=head2 Name => Str

The name of the container.


=head2 Privileged => Bool

When this parameter is true, the container is given elevated privileges
on the host container instance (similar to the root user).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SecurityHub>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

