# Generated by default/object.tt
package Paws::SecurityHub::AwsRoute53HostedZoneDetails;
  use Moose;
  has HostedZone => (is => 'ro', isa => 'Paws::SecurityHub::AwsRoute53HostedZoneObjectDetails');
  has NameServers => (is => 'ro', isa => 'ArrayRef[Str|Undef]');
  has QueryLoggingConfig => (is => 'ro', isa => 'Paws::SecurityHub::AwsRoute53QueryLoggingConfigDetails');
  has Vpcs => (is => 'ro', isa => 'ArrayRef[Paws::SecurityHub::AwsRoute53HostedZoneVpcDetails]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SecurityHub::AwsRoute53HostedZoneDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SecurityHub::AwsRoute53HostedZoneDetails object:

  $service_obj->Method(Att1 => { HostedZone => $value, ..., Vpcs => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SecurityHub::AwsRoute53HostedZoneDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->HostedZone

=head1 DESCRIPTION

Provides details about a specified Amazon Route 53 hosted zone,
including the four name servers assigned to the hosted zone. A hosted
zone represents a collection of records that can be managed together,
belonging to a single parent domain name.

=head1 ATTRIBUTES


=head2 HostedZone => L<Paws::SecurityHub::AwsRoute53HostedZoneObjectDetails>

An object that contains information about the specified hosted zone.


=head2 NameServers => ArrayRef[Str|Undef]

An object that contains a list of the authoritative name servers for a
hosted zone or for a reusable delegation set.


=head2 QueryLoggingConfig => L<Paws::SecurityHub::AwsRoute53QueryLoggingConfigDetails>

An array that contains one C<QueryLoggingConfig> element for each DNS
query logging configuration that is associated with the current Amazon
Web Services account.


=head2 Vpcs => ArrayRef[L<Paws::SecurityHub::AwsRoute53HostedZoneVpcDetails>]

An object that contains information about the Amazon Virtual Private
Clouds (Amazon VPCs) that are associated with the specified hosted
zone.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SecurityHub>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

