# Generated by default/object.tt
package Paws::SecurityHub::StandardsControlAssociationId;
  use Moose;
  has SecurityControlId => (is => 'ro', isa => 'Str', required => 1);
  has StandardsArn => (is => 'ro', isa => 'Str', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::SecurityHub::StandardsControlAssociationId

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SecurityHub::StandardsControlAssociationId object:

  $service_obj->Method(Att1 => { SecurityControlId => $value, ..., StandardsArn => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SecurityHub::StandardsControlAssociationId object:

  $result = $service_obj->Method(...);
  $result->Att1->SecurityControlId

=head1 DESCRIPTION

An array with one or more objects that includes a security control
(identified with C<SecurityControlId>, C<SecurityControlArn>, or a mix
of both parameters) and the Amazon Resource Name (ARN) of a standard.
The security control ID or ARN is the same across standards.

=head1 ATTRIBUTES


=head2 B<REQUIRED> SecurityControlId => Str

The unique identifier (identified with C<SecurityControlId>,
C<SecurityControlArn>, or a mix of both parameters) of a security
control across standards.


=head2 B<REQUIRED> StandardsArn => Str

The ARN of a standard.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SecurityHub>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

