# Generated by default/object.tt
package Paws::PersonalizeRuntime::PredictedAction;
  use Moose;
  has ActionId => (is => 'ro', isa => 'Str', request_name => 'actionId', traits => ['NameInRequest']);
  has Score => (is => 'ro', isa => 'Num', request_name => 'score', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::PersonalizeRuntime::PredictedAction

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::PersonalizeRuntime::PredictedAction object:

  $service_obj->Method(Att1 => { ActionId => $value, ..., Score => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::PersonalizeRuntime::PredictedAction object:

  $result = $service_obj->Method(...);
  $result->Att1->ActionId

=head1 DESCRIPTION

An object that identifies an action.

The API returns a list of C<PredictedAction>s.

=head1 ATTRIBUTES


=head2 ActionId => Str

The ID of the recommended action.


=head2 Score => Num

The score of the recommended action. For information about action
scores, see How action recommendation scoring works
(https://docs.aws.amazon.com/personalize/latest/dg/how-action-recommendation-scoring-works.html).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::PersonalizeRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

