# Generated by default/object.tt
package Paws::CognitoIdp::DeviceType;
  use Moose;
  has DeviceAttributes => (is => 'ro', isa => 'ArrayRef[Paws::CognitoIdp::AttributeType]');
  has DeviceCreateDate => (is => 'ro', isa => 'Str');
  has DeviceKey => (is => 'ro', isa => 'Str');
  has DeviceLastAuthenticatedDate => (is => 'ro', isa => 'Str');
  has DeviceLastModifiedDate => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::CognitoIdp::DeviceType

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CognitoIdp::DeviceType object:

  $service_obj->Method(Att1 => { DeviceAttributes => $value, ..., DeviceLastModifiedDate => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CognitoIdp::DeviceType object:

  $result = $service_obj->Method(...);
  $result->Att1->DeviceAttributes

=head1 DESCRIPTION

Information about a user's device that they've registered for device
SRP authentication in your application. For more information, see
Working with user devices in your user pool
(https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html).

=head1 ATTRIBUTES


=head2 DeviceAttributes => ArrayRef[L<Paws::CognitoIdp::AttributeType>]

Metadata about a user's device, like name and last-access source IP.


=head2 DeviceCreateDate => Str

The date and time when the item was created. Amazon Cognito returns
this timestamp in UNIX epoch time format. Your SDK might render the
output in a human-readable format like ISO 8601 or a Java C<Date>
object.


=head2 DeviceKey => Str

The device key, for example
C<us-west-2_EXAMPLE-a1b2c3d4-5678-90ab-cdef-EXAMPLE22222>.


=head2 DeviceLastAuthenticatedDate => Str

The date when the user last signed in with the device.


=head2 DeviceLastModifiedDate => Str

The date and time when the item was modified. Amazon Cognito returns
this timestamp in UNIX epoch time format. Your SDK might render the
output in a human-readable format like ISO 8601 or a Java C<Date>
object.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CognitoIdp>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

