# Generated by default/object.tt
package Paws::CleanRooms::ProtectedJobParameters;
  use Moose;
  has AnalysisTemplateArn => (is => 'ro', isa => 'Str', request_name => 'analysisTemplateArn', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::CleanRooms::ProtectedJobParameters

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CleanRooms::ProtectedJobParameters object:

  $service_obj->Method(Att1 => { AnalysisTemplateArn => $value, ..., AnalysisTemplateArn => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CleanRooms::ProtectedJobParameters object:

  $result = $service_obj->Method(...);
  $result->Att1->AnalysisTemplateArn

=head1 DESCRIPTION

The parameters for the protected job.

=head1 ATTRIBUTES


=head2 AnalysisTemplateArn => Str

The ARN of the analysis template.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CleanRooms>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

