# Generated by default/object.tt
package Paws::CleanRooms::ProtectedJob;
  use Moose;
  has CreateTime => (is => 'ro', isa => 'Str', request_name => 'createTime', traits => ['NameInRequest'], required => 1);
  has Error => (is => 'ro', isa => 'Paws::CleanRooms::ProtectedJobError', request_name => 'error', traits => ['NameInRequest']);
  has Id => (is => 'ro', isa => 'Str', request_name => 'id', traits => ['NameInRequest'], required => 1);
  has JobParameters => (is => 'ro', isa => 'Paws::CleanRooms::ProtectedJobParameters', request_name => 'jobParameters', traits => ['NameInRequest']);
  has MembershipArn => (is => 'ro', isa => 'Str', request_name => 'membershipArn', traits => ['NameInRequest'], required => 1);
  has MembershipId => (is => 'ro', isa => 'Str', request_name => 'membershipId', traits => ['NameInRequest'], required => 1);
  has Result => (is => 'ro', isa => 'Paws::CleanRooms::ProtectedJobResult', request_name => 'result', traits => ['NameInRequest']);
  has ResultConfiguration => (is => 'ro', isa => 'Paws::CleanRooms::ProtectedJobResultConfigurationOutput', request_name => 'resultConfiguration', traits => ['NameInRequest']);
  has Statistics => (is => 'ro', isa => 'Paws::CleanRooms::ProtectedJobStatistics', request_name => 'statistics', traits => ['NameInRequest']);
  has Status => (is => 'ro', isa => 'Str', request_name => 'status', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::CleanRooms::ProtectedJob

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CleanRooms::ProtectedJob object:

  $service_obj->Method(Att1 => { CreateTime => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CleanRooms::ProtectedJob object:

  $result = $service_obj->Method(...);
  $result->Att1->CreateTime

=head1 DESCRIPTION

The parameters for an Clean Rooms protected job.

=head1 ATTRIBUTES


=head2 B<REQUIRED> CreateTime => Str

The creation time of the protected job.


=head2 Error => L<Paws::CleanRooms::ProtectedJobError>

The error from the protected job.


=head2 B<REQUIRED> Id => Str

The identifier for a protected job instance.


=head2 JobParameters => L<Paws::CleanRooms::ProtectedJobParameters>

The job parameters for the protected job.


=head2 B<REQUIRED> MembershipArn => Str

The ARN of the membership.


=head2 B<REQUIRED> MembershipId => Str

he identifier for the membership.


=head2 Result => L<Paws::CleanRooms::ProtectedJobResult>

The result of the protected job.


=head2 ResultConfiguration => L<Paws::CleanRooms::ProtectedJobResultConfigurationOutput>

Contains any details needed to write the job results.


=head2 Statistics => L<Paws::CleanRooms::ProtectedJobStatistics>

The statistics of the protected job.


=head2 B<REQUIRED> Status => Str

The status of the protected job.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CleanRooms>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

