# Generated by default/object.tt
package Paws::Textract::AdapterVersionOverview;
  use Moose;
  has AdapterId => (is => 'ro', isa => 'Str');
  has AdapterVersion => (is => 'ro', isa => 'Str');
  has CreationTime => (is => 'ro', isa => 'Str');
  has FeatureTypes => (is => 'ro', isa => 'ArrayRef[Str|Undef]');
  has Status => (is => 'ro', isa => 'Str');
  has StatusMessage => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Textract::AdapterVersionOverview

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Textract::AdapterVersionOverview object:

  $service_obj->Method(Att1 => { AdapterId => $value, ..., StatusMessage => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Textract::AdapterVersionOverview object:

  $result = $service_obj->Method(...);
  $result->Att1->AdapterId

=head1 DESCRIPTION

Summary info for an adapter version. Contains information on the
AdapterId, AdapterVersion, CreationTime, FeatureTypes, and Status.

=head1 ATTRIBUTES


=head2 AdapterId => Str

A unique identifier for the adapter associated with a given adapter
version.


=head2 AdapterVersion => Str

An identified for a given adapter version.


=head2 CreationTime => Str

The date and time that a given adapter version was created.


=head2 FeatureTypes => ArrayRef[Str|Undef]

The feature types that the adapter version is operating on.


=head2 Status => Str

Contains information on the status of a given adapter version.


=head2 StatusMessage => Str

A message explaining the status of a given adapter vesion.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Textract>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

