# Generated by default/object.tt
package Paws::InternetMonitor::Network;
  use Moose;
  has ASName => (is => 'ro', isa => 'Str', required => 1);
  has ASNumber => (is => 'ro', isa => 'Int', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::InternetMonitor::Network

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::InternetMonitor::Network object:

  $service_obj->Method(Att1 => { ASName => $value, ..., ASNumber => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::InternetMonitor::Network object:

  $result = $service_obj->Method(...);
  $result->Att1->ASName

=head1 DESCRIPTION

An internet service provider (ISP) or network (ASN) in Amazon
CloudWatch Internet Monitor.

=head1 ATTRIBUTES


=head2 B<REQUIRED> ASName => Str

The name of the internet service provider (ISP) or network (ASN).


=head2 B<REQUIRED> ASNumber => Int

The Autonomous System Number (ASN) of the internet provider or network.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::InternetMonitor>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

