# Generated by default/object.tt
package Paws::MediaTailor::SegmentationDescriptor;
  use Moose;
  has SegmentationEventId => (is => 'ro', isa => 'Int');
  has SegmentationTypeId => (is => 'ro', isa => 'Int');
  has SegmentationUpid => (is => 'ro', isa => 'Str');
  has SegmentationUpidType => (is => 'ro', isa => 'Int');
  has SegmentNum => (is => 'ro', isa => 'Int');
  has SegmentsExpected => (is => 'ro', isa => 'Int');
  has SubSegmentNum => (is => 'ro', isa => 'Int');
  has SubSegmentsExpected => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::MediaTailor::SegmentationDescriptor

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MediaTailor::SegmentationDescriptor object:

  $service_obj->Method(Att1 => { SegmentationEventId => $value, ..., SubSegmentsExpected => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MediaTailor::SegmentationDescriptor object:

  $result = $service_obj->Method(...);
  $result->Att1->SegmentationEventId

=head1 DESCRIPTION

The C<segmentation_descriptor> message can contain advanced metadata
fields, like content identifiers, to convey a wide range of information
about the ad break. MediaTailor writes the ad metadata in the egress
manifest as part of the C<EXT-X-DATERANGE> or C<EventStream> ad
marker's SCTE-35 data.

C<segmentation_descriptor> messages must be sent with the
C<time_signal> message type.

See the C<segmentation_descriptor()> table of the 2022 SCTE-35
specification for more information.

=head1 ATTRIBUTES


=head2 SegmentationEventId => Int

The Event Identifier to assign to the
C<segmentation_descriptor.segmentation_event_id> message, as defined in
section 10.3.3.1 of the 2022 SCTE-35 specification. The default value
is 1.


=head2 SegmentationTypeId => Int

The Type Identifier to assign to the
C<segmentation_descriptor.segmentation_type_id> message, as defined in
section 10.3.3.1 of the 2022 SCTE-35 specification. Values must be
between 0 and 256, inclusive. The default value is 48.


=head2 SegmentationUpid => Str

The Upid to assign to the C<segmentation_descriptor.segmentation_upid>
message, as defined in section 10.3.3.1 of the 2022 SCTE-35
specification. The value must be a hexadecimal string containing only
the characters 0 though 9 and A through F. The default value is "" (an
empty string).


=head2 SegmentationUpidType => Int

The Upid Type to assign to the
C<segmentation_descriptor.segmentation_upid_type> message, as defined
in section 10.3.3.1 of the 2022 SCTE-35 specification. Values must be
between 0 and 256, inclusive. The default value is 14.


=head2 SegmentNum => Int

The segment number to assign to the
C<segmentation_descriptor.segment_num> message, as defined in section
10.3.3.1 of the 2022 SCTE-35 specification Values must be between 0 and
256, inclusive. The default value is 0.


=head2 SegmentsExpected => Int

The number of segments expected, which is assigned to the
C<segmentation_descriptor.segments_expectedS> message, as defined in
section 10.3.3.1 of the 2022 SCTE-35 specification Values must be
between 0 and 256, inclusive. The default value is 0.


=head2 SubSegmentNum => Int

The sub-segment number to assign to the
C<segmentation_descriptor.sub_segment_num> message, as defined in
section 10.3.3.1 of the 2022 SCTE-35 specification. Values must be
between 0 and 256, inclusive. The defualt value is null.


=head2 SubSegmentsExpected => Int

The number of sub-segments expected, which is assigned to the
C<segmentation_descriptor.sub_segments_expected> message, as defined in
section 10.3.3.1 of the 2022 SCTE-35 specification. Values must be
between 0 and 256, inclusive. The default value is null.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MediaTailor>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

