# Generated by default/object.tt
package Paws::ComputeOptimizer::Gpu;
  use Moose;
  has GpuCount => (is => 'ro', isa => 'Int', request_name => 'gpuCount', traits => ['NameInRequest']);
  has GpuMemorySizeInMiB => (is => 'ro', isa => 'Int', request_name => 'gpuMemorySizeInMiB', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::ComputeOptimizer::Gpu

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::ComputeOptimizer::Gpu object:

  $service_obj->Method(Att1 => { GpuCount => $value, ..., GpuMemorySizeInMiB => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::ComputeOptimizer::Gpu object:

  $result = $service_obj->Method(...);
  $result->Att1->GpuCount

=head1 DESCRIPTION

Describes the GPU accelerators for the instance type.

=head1 ATTRIBUTES


=head2 GpuCount => Int

The number of GPUs for the instance type.


=head2 GpuMemorySizeInMiB => Int

The total size of the memory for the GPU accelerators for the instance
type, in MiB.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::ComputeOptimizer>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

