# Generated by default/object.tt
package Paws::Glue::AuditContext;
  use Moose;
  has AdditionalAuditContext => (is => 'ro', isa => 'Str');
  has AllColumnsRequested => (is => 'ro', isa => 'Bool');
  has RequestedColumns => (is => 'ro', isa => 'ArrayRef[Str|Undef]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Glue::AuditContext

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Glue::AuditContext object:

  $service_obj->Method(Att1 => { AdditionalAuditContext => $value, ..., RequestedColumns => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Glue::AuditContext object:

  $result = $service_obj->Method(...);
  $result->Att1->AdditionalAuditContext

=head1 DESCRIPTION

A structure containing the Lake Formation audit context.

=head1 ATTRIBUTES


=head2 AdditionalAuditContext => Str

A string containing the additional audit context information.


=head2 AllColumnsRequested => Bool

All columns request for audit.


=head2 RequestedColumns => ArrayRef[Str|Undef]

The requested columns for audit.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Glue>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

