# Generated by default/object.tt
package Paws::Glue::Field;
  use Moose;
  has CustomProperties => (is => 'ro', isa => 'Paws::Glue::CustomProperties');
  has Description => (is => 'ro', isa => 'Str');
  has FieldName => (is => 'ro', isa => 'Str');
  has FieldType => (is => 'ro', isa => 'Str');
  has IsCreateable => (is => 'ro', isa => 'Bool');
  has IsDefaultOnCreate => (is => 'ro', isa => 'Bool');
  has IsFilterable => (is => 'ro', isa => 'Bool');
  has IsNullable => (is => 'ro', isa => 'Bool');
  has IsPartitionable => (is => 'ro', isa => 'Bool');
  has IsPrimaryKey => (is => 'ro', isa => 'Bool');
  has IsRetrievable => (is => 'ro', isa => 'Bool');
  has IsUpdateable => (is => 'ro', isa => 'Bool');
  has IsUpsertable => (is => 'ro', isa => 'Bool');
  has Label => (is => 'ro', isa => 'Str');
  has NativeDataType => (is => 'ro', isa => 'Str');
  has ParentField => (is => 'ro', isa => 'Str');
  has SupportedFilterOperators => (is => 'ro', isa => 'ArrayRef[Str|Undef]');
  has SupportedValues => (is => 'ro', isa => 'ArrayRef[Str|Undef]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Glue::Field

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Glue::Field object:

  $service_obj->Method(Att1 => { CustomProperties => $value, ..., SupportedValues => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Glue::Field object:

  $result = $service_obj->Method(...);
  $result->Att1->CustomProperties

=head1 DESCRIPTION

The C<Field> object has information about the different properties
associated with a field in the connector.

=head1 ATTRIBUTES


=head2 CustomProperties => L<Paws::Glue::CustomProperties>

Optional map of keys which may be returned.


=head2 Description => Str

A description of the field.


=head2 FieldName => Str

A unique identifier for the field.


=head2 FieldType => Str

The type of data in the field.


=head2 IsCreateable => Bool

Indicates whether this field can be created as part of a destination
write.


=head2 IsDefaultOnCreate => Bool

Indicates whether this field is populated automatically when the object
is created, such as a created at timestamp.


=head2 IsFilterable => Bool

Indicates whether this field can used in a filter clause (C<WHERE>
clause) of a SQL statement when querying data.


=head2 IsNullable => Bool

Indicates whether this field can be nullable or not.


=head2 IsPartitionable => Bool

Indicates whether a given field can be used in partitioning the query
made to SaaS.


=head2 IsPrimaryKey => Bool

Indicates whether this field can used as a primary key for the given
entity.


=head2 IsRetrievable => Bool

Indicates whether this field can be added in Select clause of SQL query
or whether it is retrievable or not.


=head2 IsUpdateable => Bool

Indicates whether this field can be updated as part of a destination
write.


=head2 IsUpsertable => Bool

Indicates whether this field can be upserted as part of a destination
write.


=head2 Label => Str

A readable label used for the field.


=head2 NativeDataType => Str

The data type returned by the SaaS API, such as
E<ldquo>picklistE<rdquo> or E<ldquo>textareaE<rdquo> from Salesforce.


=head2 ParentField => Str

A parent field name for a nested field.


=head2 SupportedFilterOperators => ArrayRef[Str|Undef]

Indicates the support filter operators for this field.


=head2 SupportedValues => ArrayRef[Str|Undef]

A list of supported values for the field.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Glue>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

