# Generated by default/object.tt
package Paws::Glue::MetricBasedObservation;
  use Moose;
  has MetricName => (is => 'ro', isa => 'Str');
  has MetricValues => (is => 'ro', isa => 'Paws::Glue::DataQualityMetricValues');
  has NewRules => (is => 'ro', isa => 'ArrayRef[Str|Undef]');
  has StatisticId => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Glue::MetricBasedObservation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Glue::MetricBasedObservation object:

  $service_obj->Method(Att1 => { MetricName => $value, ..., StatisticId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Glue::MetricBasedObservation object:

  $result = $service_obj->Method(...);
  $result->Att1->MetricName

=head1 DESCRIPTION

Describes the metric based observation generated based on evaluated
data quality metrics.

=head1 ATTRIBUTES


=head2 MetricName => Str

The name of the data quality metric used for generating the
observation.


=head2 MetricValues => L<Paws::Glue::DataQualityMetricValues>

An object of type C<DataQualityMetricValues> representing the analysis
of the data quality metric value.


=head2 NewRules => ArrayRef[Str|Undef]

A list of new data quality rules generated as part of the observation
based on the data quality metric value.


=head2 StatisticId => Str

The Statistic ID.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Glue>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

