# Generated by default/object.tt
package Paws::CodePipeline::RuleConfigurationProperty;
  use Moose;
  has Description => (is => 'ro', isa => 'Str', request_name => 'description', traits => ['NameInRequest']);
  has Key => (is => 'ro', isa => 'Bool', request_name => 'key', traits => ['NameInRequest'], required => 1);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);
  has Queryable => (is => 'ro', isa => 'Bool', request_name => 'queryable', traits => ['NameInRequest']);
  has Required => (is => 'ro', isa => 'Bool', request_name => 'required', traits => ['NameInRequest'], required => 1);
  has Secret => (is => 'ro', isa => 'Bool', request_name => 'secret', traits => ['NameInRequest'], required => 1);
  has Type => (is => 'ro', isa => 'Str', request_name => 'type', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::CodePipeline::RuleConfigurationProperty

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CodePipeline::RuleConfigurationProperty object:

  $service_obj->Method(Att1 => { Description => $value, ..., Type => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CodePipeline::RuleConfigurationProperty object:

  $result = $service_obj->Method(...);
  $result->Att1->Description

=head1 DESCRIPTION

Represents information about a rule configuration property.

=head1 ATTRIBUTES


=head2 Description => Str

The description of the action configuration property that is displayed
to users.


=head2 B<REQUIRED> Key => Bool

Whether the configuration property is a key.


=head2 B<REQUIRED> Name => Str

The name of the rule configuration property.


=head2 Queryable => Bool

Indicates whether the property can be queried.

If you create a pipeline with a condition and rule, and that rule
contains a queryable property, the value for that configuration
property is subject to other restrictions. The value must be less than
or equal to twenty (20) characters. The value can contain only
alphanumeric characters, underscores, and hyphens.


=head2 B<REQUIRED> Required => Bool

Whether the configuration property is a required value.


=head2 B<REQUIRED> Secret => Bool

Whether the configuration property is secret.

When updating a pipeline, passing * * * * * without changing any other
values of the action preserves the previous value of the secret.


=head2 Type => Str

The type of the configuration property.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CodePipeline>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

