# Generated by default/object.tt
package Paws::SageMakerGeospatial::InputConfigInput;
  use Moose;
  has PreviousEarthObservationJobArn => (is => 'ro', isa => 'Str');
  has RasterDataCollectionQuery => (is => 'ro', isa => 'Paws::SageMakerGeospatial::RasterDataCollectionQueryInput');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMakerGeospatial::InputConfigInput

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMakerGeospatial::InputConfigInput object:

  $service_obj->Method(Att1 => { PreviousEarthObservationJobArn => $value, ..., RasterDataCollectionQuery => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMakerGeospatial::InputConfigInput object:

  $result = $service_obj->Method(...);
  $result->Att1->PreviousEarthObservationJobArn

=head1 DESCRIPTION

Input configuration information.

=head1 ATTRIBUTES


=head2 PreviousEarthObservationJobArn => Str

The Amazon Resource Name (ARN) of the previous Earth Observation job.


=head2 RasterDataCollectionQuery => L<Paws::SageMakerGeospatial::RasterDataCollectionQueryInput>

The structure representing the RasterDataCollection Query consisting of
the Area of Interest, RasterDataCollectionArn,TimeRange and Property
Filters.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMakerGeospatial>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

