# Generated by default/object.tt
package Paws::ControlTower::LandingZoneOperationSummary;
  use Moose;
  has OperationIdentifier => (is => 'ro', isa => 'Str', request_name => 'operationIdentifier', traits => ['NameInRequest']);
  has OperationType => (is => 'ro', isa => 'Str', request_name => 'operationType', traits => ['NameInRequest']);
  has Status => (is => 'ro', isa => 'Str', request_name => 'status', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::ControlTower::LandingZoneOperationSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::ControlTower::LandingZoneOperationSummary object:

  $service_obj->Method(Att1 => { OperationIdentifier => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::ControlTower::LandingZoneOperationSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->OperationIdentifier

=head1 DESCRIPTION

Returns a summary of information about a landing zone operation.

=head1 ATTRIBUTES


=head2 OperationIdentifier => Str

The C<operationIdentifier> of the landing zone operation.


=head2 OperationType => Str

The type of the landing zone operation.


=head2 Status => Str

The status of the landing zone operation.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::ControlTower>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

