# Generated by default/object.tt
package Paws::Appflow::FieldTypeDetails;
  use Moose;
  has FieldLengthRange => (is => 'ro', isa => 'Paws::Appflow::Range', request_name => 'fieldLengthRange', traits => ['NameInRequest']);
  has FieldType => (is => 'ro', isa => 'Str', request_name => 'fieldType', traits => ['NameInRequest'], required => 1);
  has FieldValueRange => (is => 'ro', isa => 'Paws::Appflow::Range', request_name => 'fieldValueRange', traits => ['NameInRequest']);
  has FilterOperators => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'filterOperators', traits => ['NameInRequest'], required => 1);
  has SupportedDateFormat => (is => 'ro', isa => 'Str', request_name => 'supportedDateFormat', traits => ['NameInRequest']);
  has SupportedValues => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'supportedValues', traits => ['NameInRequest']);
  has ValueRegexPattern => (is => 'ro', isa => 'Str', request_name => 'valueRegexPattern', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Appflow::FieldTypeDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Appflow::FieldTypeDetails object:

  $service_obj->Method(Att1 => { FieldLengthRange => $value, ..., ValueRegexPattern => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Appflow::FieldTypeDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->FieldLengthRange

=head1 DESCRIPTION

Contains details regarding the supported field type and the operators
that can be applied for filtering.

=head1 ATTRIBUTES


=head2 FieldLengthRange => L<Paws::Appflow::Range>

This is the allowable length range for this field's value.


=head2 B<REQUIRED> FieldType => Str

The type of field, such as string, integer, date, and so on.


=head2 FieldValueRange => L<Paws::Appflow::Range>

The range of values this field can hold.


=head2 B<REQUIRED> FilterOperators => ArrayRef[Str|Undef]

The list of operators supported by a field.


=head2 SupportedDateFormat => Str

The date format that the field supports.


=head2 SupportedValues => ArrayRef[Str|Undef]

The list of values that a field can contain. For example, a Boolean
C<fieldType> can have two values: "true" and "false".


=head2 ValueRegexPattern => Str

The regular expression pattern for the field name.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Appflow>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

