# Generated by default/object.tt
package Paws::Appflow::RedshiftConnectorProfileProperties;
  use Moose;
  has BucketName => (is => 'ro', isa => 'Str', request_name => 'bucketName', traits => ['NameInRequest'], required => 1);
  has BucketPrefix => (is => 'ro', isa => 'Str', request_name => 'bucketPrefix', traits => ['NameInRequest']);
  has ClusterIdentifier => (is => 'ro', isa => 'Str', request_name => 'clusterIdentifier', traits => ['NameInRequest']);
  has DataApiRoleArn => (is => 'ro', isa => 'Str', request_name => 'dataApiRoleArn', traits => ['NameInRequest']);
  has DatabaseName => (is => 'ro', isa => 'Str', request_name => 'databaseName', traits => ['NameInRequest']);
  has DatabaseUrl => (is => 'ro', isa => 'Str', request_name => 'databaseUrl', traits => ['NameInRequest']);
  has IsRedshiftServerless => (is => 'ro', isa => 'Bool', request_name => 'isRedshiftServerless', traits => ['NameInRequest']);
  has RoleArn => (is => 'ro', isa => 'Str', request_name => 'roleArn', traits => ['NameInRequest'], required => 1);
  has WorkgroupName => (is => 'ro', isa => 'Str', request_name => 'workgroupName', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Appflow::RedshiftConnectorProfileProperties

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Appflow::RedshiftConnectorProfileProperties object:

  $service_obj->Method(Att1 => { BucketName => $value, ..., WorkgroupName => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Appflow::RedshiftConnectorProfileProperties object:

  $result = $service_obj->Method(...);
  $result->Att1->BucketName

=head1 DESCRIPTION

The connector-specific profile properties when using Amazon Redshift.

=head1 ATTRIBUTES


=head2 B<REQUIRED> BucketName => Str

A name for the associated Amazon S3 bucket.


=head2 BucketPrefix => Str

The object key for the destination bucket in which Amazon AppFlow
places the files.


=head2 ClusterIdentifier => Str

The unique ID that's assigned to an Amazon Redshift cluster.


=head2 DataApiRoleArn => Str

The Amazon Resource Name (ARN) of an IAM role that permits Amazon
AppFlow to access your Amazon Redshift database through the Data API.
For more information, and for the polices that you attach to this role,
see Allow Amazon AppFlow to access Amazon Redshift databases with the
Data API
(https://docs.aws.amazon.com/appflow/latest/userguide/security_iam_service-role-policies.html#access-redshift).


=head2 DatabaseName => Str

The name of an Amazon Redshift database.


=head2 DatabaseUrl => Str

The JDBC URL of the Amazon Redshift cluster.


=head2 IsRedshiftServerless => Bool

Indicates whether the connector profile defines a connection to an
Amazon Redshift Serverless data warehouse.


=head2 B<REQUIRED> RoleArn => Str

The Amazon Resource Name (ARN) of IAM role that grants Amazon Redshift
read-only access to Amazon S3. For more information, and for the
polices that you attach to this role, see Allow Amazon Redshift to
access your Amazon AppFlow data in Amazon S3
(https://docs.aws.amazon.com/appflow/latest/userguide/security_iam_service-role-policies.html#redshift-access-s3).


=head2 WorkgroupName => Str

The name of an Amazon Redshift workgroup.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Appflow>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

