# Generated by default/object.tt
package Paws::M2::BatchJobIdentifier;
  use Moose;
  has FileBatchJobIdentifier => (is => 'ro', isa => 'Paws::M2::FileBatchJobIdentifier', request_name => 'fileBatchJobIdentifier', traits => ['NameInRequest']);
  has RestartBatchJobIdentifier => (is => 'ro', isa => 'Paws::M2::RestartBatchJobIdentifier', request_name => 'restartBatchJobIdentifier', traits => ['NameInRequest']);
  has S3BatchJobIdentifier => (is => 'ro', isa => 'Paws::M2::S3BatchJobIdentifier', request_name => 's3BatchJobIdentifier', traits => ['NameInRequest']);
  has ScriptBatchJobIdentifier => (is => 'ro', isa => 'Paws::M2::ScriptBatchJobIdentifier', request_name => 'scriptBatchJobIdentifier', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::M2::BatchJobIdentifier

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::M2::BatchJobIdentifier object:

  $service_obj->Method(Att1 => { FileBatchJobIdentifier => $value, ..., ScriptBatchJobIdentifier => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::M2::BatchJobIdentifier object:

  $result = $service_obj->Method(...);
  $result->Att1->FileBatchJobIdentifier

=head1 DESCRIPTION

Identifies a specific batch job.

=head1 ATTRIBUTES


=head2 FileBatchJobIdentifier => L<Paws::M2::FileBatchJobIdentifier>

Specifies a file associated with a specific batch job.


=head2 RestartBatchJobIdentifier => L<Paws::M2::RestartBatchJobIdentifier>

Specifies the required information for restart, including
C<executionId> and C<JobStepRestartMarker>.


=head2 S3BatchJobIdentifier => L<Paws::M2::S3BatchJobIdentifier>

Specifies an Amazon S3 location that identifies the batch jobs that you
want to run. Use this identifier to run ad hoc batch jobs.


=head2 ScriptBatchJobIdentifier => L<Paws::M2::ScriptBatchJobIdentifier>

A batch job identifier in which the batch job to run is identified by
the script name.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::M2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

