# Generated by default/object.tt
package Paws::Transfer::DescribedCertificate;
  use Moose;
  has ActiveDate => (is => 'ro', isa => 'Str');
  has Arn => (is => 'ro', isa => 'Str', required => 1);
  has Certificate => (is => 'ro', isa => 'Str');
  has CertificateChain => (is => 'ro', isa => 'Str');
  has CertificateId => (is => 'ro', isa => 'Str');
  has Description => (is => 'ro', isa => 'Str');
  has InactiveDate => (is => 'ro', isa => 'Str');
  has NotAfterDate => (is => 'ro', isa => 'Str');
  has NotBeforeDate => (is => 'ro', isa => 'Str');
  has Serial => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');
  has Tags => (is => 'ro', isa => 'ArrayRef[Paws::Transfer::Tag]');
  has Type => (is => 'ro', isa => 'Str');
  has Usage => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Transfer::DescribedCertificate

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Transfer::DescribedCertificate object:

  $service_obj->Method(Att1 => { ActiveDate => $value, ..., Usage => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Transfer::DescribedCertificate object:

  $result = $service_obj->Method(...);
  $result->Att1->ActiveDate

=head1 DESCRIPTION

Describes the properties of a certificate.

=head1 ATTRIBUTES


=head2 ActiveDate => Str

An optional date that specifies when the certificate becomes active. If
you do not specify a value, C<ActiveDate> takes the same value as
C<NotBeforeDate>, which is specified by the CA.


=head2 B<REQUIRED> Arn => Str

The unique Amazon Resource Name (ARN) for the certificate.


=head2 Certificate => Str

The file name for the certificate.


=head2 CertificateChain => Str

The list of certificates that make up the chain for the certificate.


=head2 CertificateId => Str

An array of identifiers for the imported certificates. You use this
identifier for working with profiles and partner profiles.


=head2 Description => Str

The name or description that's used to identity the certificate.


=head2 InactiveDate => Str

An optional date that specifies when the certificate becomes inactive.
If you do not specify a value, C<InactiveDate> takes the same value as
C<NotAfterDate>, which is specified by the CA.


=head2 NotAfterDate => Str

The final date that the certificate is valid.


=head2 NotBeforeDate => Str

The earliest date that the certificate is valid.


=head2 Serial => Str

The serial number for the certificate.


=head2 Status => Str

A certificate's status can be either C<ACTIVE> or C<INACTIVE>.

You can set C<ActiveDate> and C<InactiveDate> in the
C<UpdateCertificate> call. If you set values for these parameters,
those values are used to determine whether the certificate has a status
of C<ACTIVE> or C<INACTIVE>.

If you don't set values for C<ActiveDate> and C<InactiveDate>, we use
the C<NotBefore> and C<NotAfter> date as specified on the X509
certificate to determine when a certificate is active and when it is
inactive.


=head2 Tags => ArrayRef[L<Paws::Transfer::Tag>]

Key-value pairs that can be used to group and search for certificates.


=head2 Type => Str

If a private key has been specified for the certificate, its type is
C<CERTIFICATE_WITH_PRIVATE_KEY>. If there is no private key, the type
is C<CERTIFICATE>.


=head2 Usage => Str

Specifies how this certificate is used. It can be used in the following
ways:

=over

=item *

C<SIGNING>: For signing AS2 messages

=item *

C<ENCRYPTION>: For encrypting AS2 messages

=item *

C<TLS>: For securing AS2 communications sent over HTTPS

=back




=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Transfer>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

