# Generated by default/object.tt
package Paws::GlobalAccelerator::CrossAccountResource;
  use Moose;
  has AttachmentArn => (is => 'ro', isa => 'Str');
  has Cidr => (is => 'ro', isa => 'Str');
  has EndpointId => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::GlobalAccelerator::CrossAccountResource

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GlobalAccelerator::CrossAccountResource object:

  $service_obj->Method(Att1 => { AttachmentArn => $value, ..., EndpointId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GlobalAccelerator::CrossAccountResource object:

  $result = $service_obj->Method(...);
  $result->Att1->AttachmentArn

=head1 DESCRIPTION

An endpoint (Amazon Web Services resource) or an IP address range, in
CIDR format, that is listed in a cross-account attachment. A
cross-account resource can be added to an accelerator by specified
principals, which are also listed in the attachment.

For more information, see Working with cross-account attachments and
resources in Global Accelerator
(https://docs.aws.amazon.com/global-accelerator/latest/dg/cross-account-resources.html)
in the I< Global Accelerator Developer Guide>.

=head1 ATTRIBUTES


=head2 AttachmentArn => Str

The Amazon Resource Name (ARN) of the cross-account attachment that
specifies the resources (endpoints or CIDR range) that can be added to
accelerators and principals that have permission to add them.


=head2 Cidr => Str

An IP address range, in CIDR format, that is specified as an Amazon Web
Services resource. The address must be provisioned and advertised in
Global Accelerator by following the bring your own IP address (BYOIP)
process for Global Accelerator.

For more information, see Bring your own IP addresses (BYOIP)
(https://docs.aws.amazon.com/global-accelerator/latest/dg/using-byoip.html)
in the Global Accelerator Developer Guide.


=head2 EndpointId => Str

The endpoint ID for the endpoint that is listed in a cross-account
attachment and can be added to an accelerator by specified principals.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GlobalAccelerator>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

