# Generated by default/object.tt
package Paws::IoTSiteWise::Reference;
  use Moose;
  has Dataset => (is => 'ro', isa => 'Paws::IoTSiteWise::DataSetReference', request_name => 'dataset', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::IoTSiteWise::Reference

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::IoTSiteWise::Reference object:

  $service_obj->Method(Att1 => { Dataset => $value, ..., Dataset => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::IoTSiteWise::Reference object:

  $result = $service_obj->Method(...);
  $result->Att1->Dataset

=head1 DESCRIPTION

Contains the reference information.

=head1 ATTRIBUTES


=head2 Dataset => L<Paws::IoTSiteWise::DataSetReference>

Contains the dataset reference information.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::IoTSiteWise>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

