# Generated by default/object.tt
package Paws::MarketplaceAgreement::ByolPricingTerm;
  use Moose;
  has Type => (is => 'ro', isa => 'Str', request_name => 'type', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::MarketplaceAgreement::ByolPricingTerm

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MarketplaceAgreement::ByolPricingTerm object:

  $service_obj->Method(Att1 => { Type => $value, ..., Type => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MarketplaceAgreement::ByolPricingTerm object:

  $result = $service_obj->Method(...);
  $result->Att1->Type

=head1 DESCRIPTION

Enables you and your customers to move your existing agreements to AWS
Marketplace. The customer won't be charged for product usage in AWS
Marketplace because they already paid for the product outside of AWS
Marketplace.

=head1 ATTRIBUTES


=head2 Type => Str

Type of the term being updated.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MarketplaceAgreement>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

