# Generated by default/object.tt
package Paws::Kendra::TableExcerpt;
  use Moose;
  has Rows => (is => 'ro', isa => 'ArrayRef[Paws::Kendra::TableRow]');
  has TotalNumberOfRows => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Kendra::TableExcerpt

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Kendra::TableExcerpt object:

  $service_obj->Method(Att1 => { Rows => $value, ..., TotalNumberOfRows => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Kendra::TableExcerpt object:

  $result = $service_obj->Method(...);
  $result->Att1->Rows

=head1 DESCRIPTION

An excerpt from a table within a document. The table excerpt displays
up to five columns and three rows, depending on how many table cells
are relevant to the query and how many columns are available in the
original table. The top most relevant cell is displayed in the table
excerpt, along with the next most relevant cells.

=head1 ATTRIBUTES


=head2 Rows => ArrayRef[L<Paws::Kendra::TableRow>]

A list of rows in the table excerpt.


=head2 TotalNumberOfRows => Int

A count of the number of rows in the original table within the
document.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Kendra>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

