# Generated by default/object.tt
package Paws::Connect::DeviceInfo;
  use Moose;
  has OperatingSystem => (is => 'ro', isa => 'Str');
  has PlatformName => (is => 'ro', isa => 'Str');
  has PlatformVersion => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Connect::DeviceInfo

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Connect::DeviceInfo object:

  $service_obj->Method(Att1 => { OperatingSystem => $value, ..., PlatformVersion => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Connect::DeviceInfo object:

  $result = $service_obj->Method(...);
  $result->Att1->OperatingSystem

=head1 DESCRIPTION

Information regarding the device.

=head1 ATTRIBUTES


=head2 OperatingSystem => Str

Operating system that the participant used for the call.


=head2 PlatformName => Str

Name of the platform that the participant used for the call.


=head2 PlatformVersion => Str

Version of the platform that the participant used for the call.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Connect>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

