# Generated by default/object.tt
package Paws::MigrationHubStrategy::ApplicationComponentSummary;
  use Moose;
  has AppType => (is => 'ro', isa => 'Str', request_name => 'appType', traits => ['NameInRequest']);
  has Count => (is => 'ro', isa => 'Int', request_name => 'count', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::MigrationHubStrategy::ApplicationComponentSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MigrationHubStrategy::ApplicationComponentSummary object:

  $service_obj->Method(Att1 => { AppType => $value, ..., Count => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MigrationHubStrategy::ApplicationComponentSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->AppType

=head1 DESCRIPTION

Contains the summary of application components.

=head1 ATTRIBUTES


=head2 AppType => Str

Contains the name of application types.


=head2 Count => Int

Contains the count of application type.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MigrationHubStrategy>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

