# Generated by default/object.tt
package Paws::BedrockAgentRuntime::FlowTraceConditionNodeResultEvent;
  use Moose;
  has NodeName => (is => 'ro', isa => 'Str', request_name => 'nodeName', traits => ['NameInRequest'], required => 1);
  has SatisfiedConditions => (is => 'ro', isa => 'ArrayRef[Paws::BedrockAgentRuntime::FlowTraceCondition]', request_name => 'satisfiedConditions', traits => ['NameInRequest'], required => 1);
  has Timestamp => (is => 'ro', isa => 'Str', request_name => 'timestamp', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgentRuntime::FlowTraceConditionNodeResultEvent

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgentRuntime::FlowTraceConditionNodeResultEvent object:

  $service_obj->Method(Att1 => { NodeName => $value, ..., Timestamp => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgentRuntime::FlowTraceConditionNodeResultEvent object:

  $result = $service_obj->Method(...);
  $result->Att1->NodeName

=head1 DESCRIPTION

Contains information about an output from a condition node. For more
information, see Track each step in your prompt flow by viewing its
trace in Amazon Bedrock
(https://docs.aws.amazon.com/bedrock/latest/userguide/flows-trace.html).

=head1 ATTRIBUTES


=head2 B<REQUIRED> NodeName => Str

The name of the condition node.


=head2 B<REQUIRED> SatisfiedConditions => ArrayRef[L<Paws::BedrockAgentRuntime::FlowTraceCondition>]

An array of objects containing information about the conditions that
were satisfied.


=head2 B<REQUIRED> Timestamp => Str

The date and time that the trace was returned.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgentRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

