# Generated by default/object.tt
package Paws::BedrockAgentRuntime::KnowledgeBaseRetrievalConfiguration;
  use Moose;
  has VectorSearchConfiguration => (is => 'ro', isa => 'Paws::BedrockAgentRuntime::KnowledgeBaseVectorSearchConfiguration', request_name => 'vectorSearchConfiguration', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgentRuntime::KnowledgeBaseRetrievalConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgentRuntime::KnowledgeBaseRetrievalConfiguration object:

  $service_obj->Method(Att1 => { VectorSearchConfiguration => $value, ..., VectorSearchConfiguration => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgentRuntime::KnowledgeBaseRetrievalConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->VectorSearchConfiguration

=head1 DESCRIPTION

Contains configurations for knowledge base query. For more information,
see Query configurations
(https://docs.aws.amazon.com/bedrock/latest/userguide/kb-test-config.html).

This data type is used in the following API operations:

=over

=item *

Retrieve request
(https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html#API_agent-runtime_Retrieve_RequestSyntax)
E<ndash> in the C<retrievalConfiguration> field

=item *

RetrieveAndGenerate request
(https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html#API_agent-runtime_RetrieveAndGenerate_RequestSyntax)
E<ndash> in the C<retrievalConfiguration> field

=back


=head1 ATTRIBUTES


=head2 B<REQUIRED> VectorSearchConfiguration => L<Paws::BedrockAgentRuntime::KnowledgeBaseVectorSearchConfiguration>

Contains details about how the results from the vector search should be
returned. For more information, see Query configurations
(https://docs.aws.amazon.com/bedrock/latest/userguide/kb-test-config.html).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgentRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

