# Generated by default/object.tt
package Paws::BedrockAgentRuntime::RetrievedReference;
  use Moose;
  has Content => (is => 'ro', isa => 'Paws::BedrockAgentRuntime::RetrievalResultContent', request_name => 'content', traits => ['NameInRequest']);
  has Location => (is => 'ro', isa => 'Paws::BedrockAgentRuntime::RetrievalResultLocation', request_name => 'location', traits => ['NameInRequest']);
  has Metadata => (is => 'ro', isa => 'Paws::BedrockAgentRuntime::RetrievalResultMetadata', request_name => 'metadata', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgentRuntime::RetrievedReference

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgentRuntime::RetrievedReference object:

  $service_obj->Method(Att1 => { Content => $value, ..., Metadata => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgentRuntime::RetrievedReference object:

  $result = $service_obj->Method(...);
  $result->Att1->Content

=head1 DESCRIPTION

Contains metadata about a source cited for the generated response.

This data type is used in the following API operations:

=over

=item *

RetrieveAndGenerate response
(https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html#API_agent-runtime_RetrieveAndGenerate_ResponseSyntax)
E<ndash> in the C<retrievedReferences> field

=item *

InvokeAgent response
(https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_InvokeAgent.html#API_agent-runtime_InvokeAgent_ResponseSyntax)
E<ndash> in the C<retrievedReferences> field

=back


=head1 ATTRIBUTES


=head2 Content => L<Paws::BedrockAgentRuntime::RetrievalResultContent>

Contains the cited text from the data source.


=head2 Location => L<Paws::BedrockAgentRuntime::RetrievalResultLocation>

Contains information about the location of the data source.


=head2 Metadata => L<Paws::BedrockAgentRuntime::RetrievalResultMetadata>

Contains metadata attributes and their values for the file in the data
source. For more information, see Metadata and filtering
(https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-ds.html#kb-ds-metadata).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgentRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

