# Generated by default/object.tt
package Paws::TimestreamWrite::MagneticStoreRejectedDataLocation;
  use Moose;
  has S3Configuration => (is => 'ro', isa => 'Paws::TimestreamWrite::S3Configuration');

1;

### main pod documentation begin ###

=head1 NAME

Paws::TimestreamWrite::MagneticStoreRejectedDataLocation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::TimestreamWrite::MagneticStoreRejectedDataLocation object:

  $service_obj->Method(Att1 => { S3Configuration => $value, ..., S3Configuration => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::TimestreamWrite::MagneticStoreRejectedDataLocation object:

  $result = $service_obj->Method(...);
  $result->Att1->S3Configuration

=head1 DESCRIPTION

The location to write error reports for records rejected,
asynchronously, during magnetic store writes.

=head1 ATTRIBUTES


=head2 S3Configuration => L<Paws::TimestreamWrite::S3Configuration>

Configuration of an S3 location to write error reports for records
rejected, asynchronously, during magnetic store writes.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::TimestreamWrite>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

