# Generated by default/object.tt
package Paws::BCMDataExports::S3OutputConfigurations;
  use Moose;
  has Compression => (is => 'ro', isa => 'Str', required => 1);
  has Format => (is => 'ro', isa => 'Str', required => 1);
  has OutputType => (is => 'ro', isa => 'Str', required => 1);
  has Overwrite => (is => 'ro', isa => 'Str', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BCMDataExports::S3OutputConfigurations

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BCMDataExports::S3OutputConfigurations object:

  $service_obj->Method(Att1 => { Compression => $value, ..., Overwrite => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BCMDataExports::S3OutputConfigurations object:

  $result = $service_obj->Method(...);
  $result->Att1->Compression

=head1 DESCRIPTION

The compression type, file format, and overwrite preference for the
data export.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Compression => Str

The compression type for the data export.


=head2 B<REQUIRED> Format => Str

The file format for the data export.


=head2 B<REQUIRED> OutputType => Str

The output type for the data export.


=head2 B<REQUIRED> Overwrite => Str

The rule to follow when generating a version of the data export file.
You have the choice to overwrite the previous version or to be
delivered in addition to the previous versions. Overwriting exports can
save on Amazon S3 storage costs. Creating new export versions allows
you to track the changes in cost and usage data over time.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BCMDataExports>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

