# Generated by default/object.tt
package Paws::LicenseManagerLinuxSubscriptions::Subscription;
  use Moose;
  has InstanceCount => (is => 'ro', isa => 'Int');
  has Name => (is => 'ro', isa => 'Str');
  has Type => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::LicenseManagerLinuxSubscriptions::Subscription

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::LicenseManagerLinuxSubscriptions::Subscription object:

  $service_obj->Method(Att1 => { InstanceCount => $value, ..., Type => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::LicenseManagerLinuxSubscriptions::Subscription object:

  $result = $service_obj->Method(...);
  $result->Att1->InstanceCount

=head1 DESCRIPTION

An object which details a discovered Linux subscription.

=head1 ATTRIBUTES


=head2 InstanceCount => Int

The total amount of running instances using this subscription.


=head2 Name => Str

The name of the subscription.


=head2 Type => Str

The type of subscription. The type can be subscription-included with
Amazon EC2, Bring Your Own Subscription model (BYOS), or from the
Amazon Web Services Marketplace. Certain subscriptions may use
licensing from the Amazon Web Services Marketplace as well as OS
licensing from Amazon EC2 or BYOS.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::LicenseManagerLinuxSubscriptions>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

