# Generated by default/object.tt
package Paws::CloudTrail::RefreshScheduleFrequency;
  use Moose;
  has Unit => (is => 'ro', isa => 'Str');
  has Value => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::CloudTrail::RefreshScheduleFrequency

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CloudTrail::RefreshScheduleFrequency object:

  $service_obj->Method(Att1 => { Unit => $value, ..., Value => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CloudTrail::RefreshScheduleFrequency object:

  $result = $service_obj->Method(...);
  $result->Att1->Unit

=head1 DESCRIPTION

Specifies the frequency for a dashboard refresh schedule.

For a custom dashboard, you can schedule a refresh for every 1, 6, 12,
or 24 hours, or every day.

=head1 ATTRIBUTES


=head2 Unit => Str

The unit to use for the refresh.

For custom dashboards, the unit can be C<HOURS> or C<DAYS>.

For the Highlights dashboard, the C<Unit> must be C<HOURS>.


=head2 Value => Int

The value for the refresh schedule.

For custom dashboards, the following values are valid when the unit is
C<HOURS>: C<1>, C<6>, C<12>, C<24>

For custom dashboards, the only valid value when the unit is C<DAYS> is
C<1>.

For the Highlights dashboard, the C<Value> must be C<6>.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CloudTrail>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

