# Generated by default/object.tt
package Paws::Batch::EksAttemptDetail;
  use Moose;
  has Containers => (is => 'ro', isa => 'ArrayRef[Paws::Batch::EksAttemptContainerDetail]', request_name => 'containers', traits => ['NameInRequest']);
  has EksClusterArn => (is => 'ro', isa => 'Str', request_name => 'eksClusterArn', traits => ['NameInRequest']);
  has InitContainers => (is => 'ro', isa => 'ArrayRef[Paws::Batch::EksAttemptContainerDetail]', request_name => 'initContainers', traits => ['NameInRequest']);
  has NodeName => (is => 'ro', isa => 'Str', request_name => 'nodeName', traits => ['NameInRequest']);
  has PodName => (is => 'ro', isa => 'Str', request_name => 'podName', traits => ['NameInRequest']);
  has PodNamespace => (is => 'ro', isa => 'Str', request_name => 'podNamespace', traits => ['NameInRequest']);
  has StartedAt => (is => 'ro', isa => 'Int', request_name => 'startedAt', traits => ['NameInRequest']);
  has StatusReason => (is => 'ro', isa => 'Str', request_name => 'statusReason', traits => ['NameInRequest']);
  has StoppedAt => (is => 'ro', isa => 'Int', request_name => 'stoppedAt', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Batch::EksAttemptDetail

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Batch::EksAttemptDetail object:

  $service_obj->Method(Att1 => { Containers => $value, ..., StoppedAt => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Batch::EksAttemptDetail object:

  $result = $service_obj->Method(...);
  $result->Att1->Containers

=head1 DESCRIPTION

An object that represents the details of a job attempt for a job
attempt by an Amazon EKS container.

=head1 ATTRIBUTES


=head2 Containers => ArrayRef[L<Paws::Batch::EksAttemptContainerDetail>]

The details for the final status of the containers for this job
attempt.


=head2 EksClusterArn => Str

The Amazon Resource Name (ARN) of the Amazon EKS cluster.


=head2 InitContainers => ArrayRef[L<Paws::Batch::EksAttemptContainerDetail>]

The details for the init containers.


=head2 NodeName => Str

The name of the node for this job attempt.


=head2 PodName => Str

The name of the pod for this job attempt.


=head2 PodNamespace => Str

The namespace of the Amazon EKS cluster that the pod exists in.


=head2 StartedAt => Int

The Unix timestamp (in milliseconds) for when the attempt was started
(when the attempt transitioned from the C<STARTING> state to the
C<RUNNING> state).


=head2 StatusReason => Str

A short, human-readable string to provide additional details for the
current status of the job attempt.


=head2 StoppedAt => Int

The Unix timestamp (in milliseconds) for when the attempt was stopped.
This happens when the attempt transitioned from the C<RUNNING> state to
a terminal state, such as C<SUCCEEDED> or C<FAILED>.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Batch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

