# Generated by default/object.tt
package Paws::WorkSpacesWeb::BrowserSettings;
  use Moose;
  has AdditionalEncryptionContext => (is => 'ro', isa => 'Paws::WorkSpacesWeb::EncryptionContextMap', request_name => 'additionalEncryptionContext', traits => ['NameInRequest']);
  has AssociatedPortalArns => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'associatedPortalArns', traits => ['NameInRequest']);
  has BrowserPolicy => (is => 'ro', isa => 'Str', request_name => 'browserPolicy', traits => ['NameInRequest']);
  has BrowserSettingsArn => (is => 'ro', isa => 'Str', request_name => 'browserSettingsArn', traits => ['NameInRequest'], required => 1);
  has CustomerManagedKey => (is => 'ro', isa => 'Str', request_name => 'customerManagedKey', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::WorkSpacesWeb::BrowserSettings

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::WorkSpacesWeb::BrowserSettings object:

  $service_obj->Method(Att1 => { AdditionalEncryptionContext => $value, ..., CustomerManagedKey => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::WorkSpacesWeb::BrowserSettings object:

  $result = $service_obj->Method(...);
  $result->Att1->AdditionalEncryptionContext

=head1 DESCRIPTION

The browser settings resource that can be associated with a web portal.
Once associated with a web portal, browser settings control how the
browser will behave once a user starts a streaming session for the web
portal.

=head1 ATTRIBUTES


=head2 AdditionalEncryptionContext => L<Paws::WorkSpacesWeb::EncryptionContextMap>

The additional encryption context of the browser settings.


=head2 AssociatedPortalArns => ArrayRef[Str|Undef]

A list of web portal ARNs that this browser settings is associated
with.


=head2 BrowserPolicy => Str

A JSON string containing Chrome Enterprise policies that will be
applied to all streaming sessions.


=head2 B<REQUIRED> BrowserSettingsArn => Str

The ARN of the browser settings.


=head2 CustomerManagedKey => Str

The customer managed key used to encrypt sensitive information in the
browser settings.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::WorkSpacesWeb>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

