
package Paws::WorkSpacesWeb::UpdateIpAccessSettings;
  use Moose;
  has ClientToken => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'clientToken');
  has Description => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'description');
  has DisplayName => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'displayName');
  has IpAccessSettingsArn => (is => 'ro', isa => 'Str', traits => ['ParamInURI'], uri_name => 'ipAccessSettingsArn', required => 1);
  has IpRules => (is => 'ro', isa => 'ArrayRef[Paws::WorkSpacesWeb::IpRule]', traits => ['NameInRequest'], request_name => 'ipRules');

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'UpdateIpAccessSettings');
  class_has _api_uri  => (isa => 'Str', is => 'ro', default => '/ipAccessSettings/{ipAccessSettingsArn+}');
  class_has _api_method  => (isa => 'Str', is => 'ro', default => 'PATCH');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::WorkSpacesWeb::UpdateIpAccessSettingsResponse');
1;

### main pod documentation begin ###

=head1 NAME

Paws::WorkSpacesWeb::UpdateIpAccessSettings - Arguments for method UpdateIpAccessSettings on L<Paws::WorkSpacesWeb>

=head1 DESCRIPTION

This class represents the parameters used for calling the method UpdateIpAccessSettings on the
L<Amazon WorkSpaces Web|Paws::WorkSpacesWeb> service. Use the attributes of this class
as arguments to method UpdateIpAccessSettings.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to UpdateIpAccessSettings.

=head1 SYNOPSIS

    my $workspaces-web = Paws->service('WorkSpacesWeb');
    my $UpdateIpAccessSettingsResponse =
      $workspaces -web->UpdateIpAccessSettings(
      IpAccessSettingsArn => 'MyARN',
      ClientToken         => 'MyClientToken',    # OPTIONAL
      Description         => 'MyDescription',    # OPTIONAL
      DisplayName         => 'MyDisplayName',    # OPTIONAL
      IpRules             => [
        {
          IpRange     => 'MyIpRange',
          Description => 'MyDescription',        # min: 1, max: 256
        },
        ...
      ],    # OPTIONAL
      );

    # Results:
    my $IpAccessSettings = $UpdateIpAccessSettingsResponse->IpAccessSettings;

    # Returns a L<Paws::WorkSpacesWeb::UpdateIpAccessSettingsResponse> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/workspaces-web/UpdateIpAccessSettings>

=head1 ATTRIBUTES


=head2 ClientToken => Str

A unique, case-sensitive identifier that you provide to ensure the
idempotency of the request. Idempotency ensures that an API request
completes only once. With an idempotent request, if the original
request completes successfully, subsequent retries with the same client
token return the result from the original successful request.

If you do not specify a client token, one is automatically generated by
the Amazon Web Services SDK.



=head2 Description => Str

The description of the IP access settings.



=head2 DisplayName => Str

The display name of the IP access settings.



=head2 B<REQUIRED> IpAccessSettingsArn => Str

The ARN of the IP access settings.



=head2 IpRules => ArrayRef[L<Paws::WorkSpacesWeb::IpRule>]

The updated IP rules of the IP access settings.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method UpdateIpAccessSettings in L<Paws::WorkSpacesWeb>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

