# Generated by default/object.tt
package Paws::Notifications::ManagedNotificationEvent;
  use Moose;
  has AggregationEventType => (is => 'ro', isa => 'Str', request_name => 'aggregationEventType', traits => ['NameInRequest']);
  has AggregationSummary => (is => 'ro', isa => 'Paws::Notifications::AggregationSummary', request_name => 'aggregationSummary', traits => ['NameInRequest']);
  has EndTime => (is => 'ro', isa => 'Str', request_name => 'endTime', traits => ['NameInRequest']);
  has EventStatus => (is => 'ro', isa => 'Str', request_name => 'eventStatus', traits => ['NameInRequest']);
  has Id => (is => 'ro', isa => 'Str', request_name => 'id', traits => ['NameInRequest'], required => 1);
  has MessageComponents => (is => 'ro', isa => 'Paws::Notifications::MessageComponents', request_name => 'messageComponents', traits => ['NameInRequest'], required => 1);
  has NotificationType => (is => 'ro', isa => 'Str', request_name => 'notificationType', traits => ['NameInRequest'], required => 1);
  has OrganizationalUnitId => (is => 'ro', isa => 'Str', request_name => 'organizationalUnitId', traits => ['NameInRequest']);
  has SchemaVersion => (is => 'ro', isa => 'Str', request_name => 'schemaVersion', traits => ['NameInRequest'], required => 1);
  has SourceEventDetailUrl => (is => 'ro', isa => 'Str', request_name => 'sourceEventDetailUrl', traits => ['NameInRequest']);
  has SourceEventDetailUrlDisplayText => (is => 'ro', isa => 'Str', request_name => 'sourceEventDetailUrlDisplayText', traits => ['NameInRequest']);
  has StartTime => (is => 'ro', isa => 'Str', request_name => 'startTime', traits => ['NameInRequest']);
  has TextParts => (is => 'ro', isa => 'Paws::Notifications::TextParts', request_name => 'textParts', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Notifications::ManagedNotificationEvent

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Notifications::ManagedNotificationEvent object:

  $service_obj->Method(Att1 => { AggregationEventType => $value, ..., TextParts => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Notifications::ManagedNotificationEvent object:

  $result = $service_obj->Method(...);
  $result->Att1->AggregationEventType

=head1 DESCRIPTION

A notification-focused representation of an event. They contain
semantic information used by AccountContacts or Additional Channels to
create end-user notifications.

=head1 ATTRIBUTES


=head2 AggregationEventType => Str

The notifications aggregation type.


=head2 AggregationSummary => L<Paws::Notifications::AggregationSummary>




=head2 EndTime => Str

The end time of the notification event.


=head2 EventStatus => Str

The status of an event.

=over

=item *

Values:

=over

=item *

C<HEALTHY>

=over

=item *

All EventRules are C<ACTIVE> and any call can be run.

=back

=item *

C<UNHEALTHY>

=over

=item *

Some EventRules are C<ACTIVE> and some are C<INACTIVE>. Any call can be
run.

=back

=back

=back



=head2 B<REQUIRED> Id => Str

Unique identifier for a C<ManagedNotificationEvent>.


=head2 B<REQUIRED> MessageComponents => L<Paws::Notifications::MessageComponents>




=head2 B<REQUIRED> NotificationType => Str

The nature of the event causing this notification.

=over

=item *

Values:

=over

=item *

C<ALERT>

=over

=item *

A notification about an event where something was triggered, initiated,
reopened, deployed, or a threshold was breached.

=back

=item *

C<WARNING>

=over

=item *

A notification about an event where an issue is about to arise. For
example, something is approaching a threshold.

=back

=item *

C<ANNOUNCEMENT>

=over

=item *

A notification about an important event. For example, a step in a
workflow or escalation path or that a workflow was updated.

=back

=item *

C<INFORMATIONAL>

=over

=item *

A notification about informational messages. For example,
recommendations, service announcements, or reminders.

=back

=back

=back



=head2 OrganizationalUnitId => Str

The Organizational Unit Id that an Amazon Web Services account belongs
to.


=head2 B<REQUIRED> SchemaVersion => Str

Version of the C<ManagedNotificationEvent> schema.


=head2 SourceEventDetailUrl => Str

URL defined by Source Service to be used by notification consumers to
get additional information about event.


=head2 SourceEventDetailUrlDisplayText => Str

Text that needs to be hyperlinked with the sourceEventDetailUrl. For
example, the description of the sourceEventDetailUrl.


=head2 StartTime => Str

The earliest time of events to return from this call.


=head2 B<REQUIRED> TextParts => L<Paws::Notifications::TextParts>

A list of text values.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Notifications>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

