# Generated by default/object.tt
package Paws::Notifications::TextPartValue;
  use Moose;
  has DisplayText => (is => 'ro', isa => 'Str', request_name => 'displayText', traits => ['NameInRequest']);
  has TextByLocale => (is => 'ro', isa => 'Paws::Notifications::TextByLocale', request_name => 'textByLocale', traits => ['NameInRequest']);
  has Type => (is => 'ro', isa => 'Str', request_name => 'type', traits => ['NameInRequest'], required => 1);
  has Url => (is => 'ro', isa => 'Str', request_name => 'url', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Notifications::TextPartValue

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Notifications::TextPartValue object:

  $service_obj->Method(Att1 => { DisplayText => $value, ..., Url => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Notifications::TextPartValue object:

  $result = $service_obj->Method(...);
  $result->Att1->DisplayText

=head1 DESCRIPTION

Describes text information objects containing fields that determine how
text part objects are composed.

=head1 ATTRIBUTES


=head2 DisplayText => Str

A short single line description of the link. Must be hyper-linked with
the URL itself.

Used for text parts with the type C<URL>.


=head2 TextByLocale => L<Paws::Notifications::TextByLocale>

A map of locales to the text in that locale.


=head2 B<REQUIRED> Type => Str

The type of text part. Determines the usage of all other fields and
whether or not they're required.


=head2 Url => Str

The URL itself.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Notifications>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

