# Generated by default/object.tt
package Paws::QApps::CardValue;
  use Moose;
  has CardId => (is => 'ro', isa => 'Str', request_name => 'cardId', traits => ['NameInRequest'], required => 1);
  has SubmissionMutation => (is => 'ro', isa => 'Paws::QApps::SubmissionMutation', request_name => 'submissionMutation', traits => ['NameInRequest']);
  has Value => (is => 'ro', isa => 'Str', request_name => 'value', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::QApps::CardValue

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::QApps::CardValue object:

  $service_obj->Method(Att1 => { CardId => $value, ..., Value => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::QApps::CardValue object:

  $result = $service_obj->Method(...);
  $result->Att1->CardId

=head1 DESCRIPTION

The value or result associated with a card in a Amazon Q App session.

=head1 ATTRIBUTES


=head2 B<REQUIRED> CardId => Str

The unique identifier of the card.


=head2 SubmissionMutation => L<Paws::QApps::SubmissionMutation>

The structure that describes how the current form card value is
mutated. Only applies for form cards when multiple responses are
allowed.


=head2 B<REQUIRED> Value => Str

The value or result associated with the card.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::QApps>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

