# Generated by default/object.tt
package Paws::AppTest::TestRunStepSummary;
  use Moose;
  has AfterStep => (is => 'ro', isa => 'Bool', request_name => 'afterStep', traits => ['NameInRequest']);
  has BeforeStep => (is => 'ro', isa => 'Bool', request_name => 'beforeStep', traits => ['NameInRequest']);
  has RunEndTime => (is => 'ro', isa => 'Str', request_name => 'runEndTime', traits => ['NameInRequest']);
  has RunStartTime => (is => 'ro', isa => 'Str', request_name => 'runStartTime', traits => ['NameInRequest'], required => 1);
  has Status => (is => 'ro', isa => 'Str', request_name => 'status', traits => ['NameInRequest'], required => 1);
  has StatusReason => (is => 'ro', isa => 'Str', request_name => 'statusReason', traits => ['NameInRequest']);
  has StepName => (is => 'ro', isa => 'Str', request_name => 'stepName', traits => ['NameInRequest'], required => 1);
  has TestCaseId => (is => 'ro', isa => 'Str', request_name => 'testCaseId', traits => ['NameInRequest']);
  has TestCaseVersion => (is => 'ro', isa => 'Int', request_name => 'testCaseVersion', traits => ['NameInRequest']);
  has TestRunId => (is => 'ro', isa => 'Str', request_name => 'testRunId', traits => ['NameInRequest'], required => 1);
  has TestSuiteId => (is => 'ro', isa => 'Str', request_name => 'testSuiteId', traits => ['NameInRequest']);
  has TestSuiteVersion => (is => 'ro', isa => 'Int', request_name => 'testSuiteVersion', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::AppTest::TestRunStepSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::AppTest::TestRunStepSummary object:

  $service_obj->Method(Att1 => { AfterStep => $value, ..., TestSuiteVersion => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::AppTest::TestRunStepSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->AfterStep

=head1 DESCRIPTION

Specifies a test run step summary.

=head1 ATTRIBUTES


=head2 AfterStep => Bool

The after step of the test run step summary.


=head2 BeforeStep => Bool

The before step of the test run step summary.


=head2 RunEndTime => Str

The run end time of the test run step summary.


=head2 B<REQUIRED> RunStartTime => Str

The run start time of the test run step summary.


=head2 B<REQUIRED> Status => Str

The status of the test run step summary.


=head2 StatusReason => Str

The status reason of the test run step summary.


=head2 B<REQUIRED> StepName => Str

The step name of the test run step summary.


=head2 TestCaseId => Str

The test case ID of the test run step summary.


=head2 TestCaseVersion => Int

The test case version of the test run step summary.


=head2 B<REQUIRED> TestRunId => Str

The test run ID of the test run step summary.


=head2 TestSuiteId => Str

The test suite ID of the test run step summary.


=head2 TestSuiteVersion => Int

The test suite version of the test run step summary.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::AppTest>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

