# Generated by default/object.tt
package Paws::Comprehend::ChildBlock;
  use Moose;
  has BeginOffset => (is => 'ro', isa => 'Int');
  has ChildBlockId => (is => 'ro', isa => 'Str');
  has EndOffset => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Comprehend::ChildBlock

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Comprehend::ChildBlock object:

  $service_obj->Method(Att1 => { BeginOffset => $value, ..., EndOffset => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Comprehend::ChildBlock object:

  $result = $service_obj->Method(...);
  $result->Att1->BeginOffset

=head1 DESCRIPTION

Nested block contained within a block.

=head1 ATTRIBUTES


=head2 BeginOffset => Int

Offset of the start of the child block within its parent block.


=head2 ChildBlockId => Str

Unique identifier for the child block.


=head2 EndOffset => Int

Offset of the end of the child block within its parent block.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Comprehend>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

