# Generated by default/object.tt
package Paws::Comprehend::WarningsListItem;
  use Moose;
  has Page => (is => 'ro', isa => 'Int');
  has WarnCode => (is => 'ro', isa => 'Str');
  has WarnMessage => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Comprehend::WarningsListItem

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Comprehend::WarningsListItem object:

  $service_obj->Method(Att1 => { Page => $value, ..., WarnMessage => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Comprehend::WarningsListItem object:

  $result = $service_obj->Method(...);
  $result->Att1->Page

=head1 DESCRIPTION

The system identified one of the following warnings while processing
the input document:

=over

=item *

The document to classify is plain text, but the classifier is a native
document model.

=item *

The document to classify is semi-structured, but the classifier is a
plain-text model.

=back


=head1 ATTRIBUTES


=head2 Page => Int

Page number in the input document.


=head2 WarnCode => Str

The type of warning.


=head2 WarnMessage => Str

Text message associated with the warning.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Comprehend>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

