# Generated by default/object.tt
package Paws::SimSpaceWeaver::SimulationMetadata;
  use Moose;
  has Arn => (is => 'ro', isa => 'Str');
  has CreationTime => (is => 'ro', isa => 'Str');
  has Name => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');
  has TargetStatus => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SimSpaceWeaver::SimulationMetadata

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SimSpaceWeaver::SimulationMetadata object:

  $service_obj->Method(Att1 => { Arn => $value, ..., TargetStatus => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SimSpaceWeaver::SimulationMetadata object:

  $result = $service_obj->Method(...);
  $result->Att1->Arn

=head1 DESCRIPTION

A collection of data about the simulation.

=head1 ATTRIBUTES


=head2 Arn => Str

The Amazon Resource Name (ARN) of the simulation. For more information
about ARNs, see Amazon Resource Names (ARNs)
(https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
in the I<Amazon Web Services General Reference>.


=head2 CreationTime => Str

The time when the simulation was created, expressed as the number of
seconds and milliseconds in UTC since the Unix epoch (0:0:0.000,
January 1, 1970).


=head2 Name => Str

The name of the simulation.


=head2 Status => Str

The current status of the simulation.


=head2 TargetStatus => Str

The desired status of the simulation.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SimSpaceWeaver>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

