# Generated by default/object.tt
package Paws::GeoPlaces::Country;
  use Moose;
  has Code2 => (is => 'ro', isa => 'Str');
  has Code3 => (is => 'ro', isa => 'Str');
  has Name => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::GeoPlaces::Country

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GeoPlaces::Country object:

  $service_obj->Method(Att1 => { Code2 => $value, ..., Name => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GeoPlaces::Country object:

  $result = $service_obj->Method(...);
  $result->Att1->Code2

=head1 DESCRIPTION

The alpha-2 or alpha-3 character code for the country that the results
will be present in.

=head1 ATTRIBUTES


=head2 Code2 => Str

Country, represented by its alpha 2-character code.


=head2 Code3 => Str

Country, represented by its alpha t-character code.


=head2 Name => Str

Name of the country.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GeoPlaces>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

