# Generated by default/object.tt
package Paws::VoiceID::Watchlist;
  use Moose;
  has CreatedAt => (is => 'ro', isa => 'Str');
  has DefaultWatchlist => (is => 'ro', isa => 'Bool');
  has Description => (is => 'ro', isa => 'Str');
  has DomainId => (is => 'ro', isa => 'Str');
  has Name => (is => 'ro', isa => 'Str');
  has UpdatedAt => (is => 'ro', isa => 'Str');
  has WatchlistId => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::VoiceID::Watchlist

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::VoiceID::Watchlist object:

  $service_obj->Method(Att1 => { CreatedAt => $value, ..., WatchlistId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::VoiceID::Watchlist object:

  $result = $service_obj->Method(...);
  $result->Att1->CreatedAt

=head1 DESCRIPTION

Contains all the information about a watchlist.

=head1 ATTRIBUTES


=head2 CreatedAt => Str

The timestamp of when the watchlist was created.


=head2 DefaultWatchlist => Bool

Whether the specified watchlist is the default watchlist of a domain.


=head2 Description => Str

The description of the watchlist.


=head2 DomainId => Str

The identifier of the domain that contains the watchlist.


=head2 Name => Str

The name for the watchlist.


=head2 UpdatedAt => Str

The timestamp of when the watchlist was updated.


=head2 WatchlistId => Str

The identifier of the watchlist.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::VoiceID>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

