# Generated by default/object.tt
package Paws::CUR::ReportStatus;
  use Moose;
  has LastDelivery => (is => 'ro', isa => 'Str', request_name => 'lastDelivery', traits => ['NameInRequest']);
  has LastStatus => (is => 'ro', isa => 'Str', request_name => 'lastStatus', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::CUR::ReportStatus

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CUR::ReportStatus object:

  $service_obj->Method(Att1 => { LastDelivery => $value, ..., LastStatus => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CUR::ReportStatus object:

  $result = $service_obj->Method(...);
  $result->Att1->LastDelivery

=head1 DESCRIPTION

A two element dictionary with a C<lastDelivery> and C<lastStatus> key
whose values describe the date and status of the last delivered report
for a particular report definition.

=head1 ATTRIBUTES


=head2 LastDelivery => Str

A timestamp that gives the date of a report delivery.


=head2 LastStatus => Str

An enum that gives the status of a report delivery.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CUR>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

