# Generated by default/object.tt
package Paws::Finspace::SuperuserParameters;
  use Moose;
  has EmailAddress => (is => 'ro', isa => 'Str', request_name => 'emailAddress', traits => ['NameInRequest'], required => 1);
  has FirstName => (is => 'ro', isa => 'Str', request_name => 'firstName', traits => ['NameInRequest'], required => 1);
  has LastName => (is => 'ro', isa => 'Str', request_name => 'lastName', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Finspace::SuperuserParameters

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Finspace::SuperuserParameters object:

  $service_obj->Method(Att1 => { EmailAddress => $value, ..., LastName => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Finspace::SuperuserParameters object:

  $result = $service_obj->Method(...);
  $result->Att1->EmailAddress

=head1 DESCRIPTION

Configuration information for the superuser.

=head1 ATTRIBUTES


=head2 B<REQUIRED> EmailAddress => Str

The email address of the superuser.


=head2 B<REQUIRED> FirstName => Str

The first name of the superuser.


=head2 B<REQUIRED> LastName => Str

The last name of the superuser.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Finspace>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

