# Generated by default/object.tt
package Paws::DataZone::DomainSummary;
  use Moose;
  has Arn => (is => 'ro', isa => 'Str', request_name => 'arn', traits => ['NameInRequest'], required => 1);
  has CreatedAt => (is => 'ro', isa => 'Str', request_name => 'createdAt', traits => ['NameInRequest'], required => 1);
  has Description => (is => 'ro', isa => 'Str', request_name => 'description', traits => ['NameInRequest']);
  has DomainVersion => (is => 'ro', isa => 'Str', request_name => 'domainVersion', traits => ['NameInRequest']);
  has Id => (is => 'ro', isa => 'Str', request_name => 'id', traits => ['NameInRequest'], required => 1);
  has LastUpdatedAt => (is => 'ro', isa => 'Str', request_name => 'lastUpdatedAt', traits => ['NameInRequest']);
  has ManagedAccountId => (is => 'ro', isa => 'Str', request_name => 'managedAccountId', traits => ['NameInRequest'], required => 1);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);
  has PortalUrl => (is => 'ro', isa => 'Str', request_name => 'portalUrl', traits => ['NameInRequest']);
  has Status => (is => 'ro', isa => 'Str', request_name => 'status', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::DataZone::DomainSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::DataZone::DomainSummary object:

  $service_obj->Method(Att1 => { Arn => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::DataZone::DomainSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->Arn

=head1 DESCRIPTION

A summary of a Amazon DataZone domain.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Arn => Str

The ARN of the Amazon DataZone domain.


=head2 B<REQUIRED> CreatedAt => Str

A timestamp of when a Amazon DataZone domain was created.


=head2 Description => Str

A description of an Amazon DataZone domain.


=head2 DomainVersion => Str

The domain version.


=head2 B<REQUIRED> Id => Str

The ID of the Amazon DataZone domain.


=head2 LastUpdatedAt => Str

A timestamp of when a Amazon DataZone domain was last updated.


=head2 B<REQUIRED> ManagedAccountId => Str

The identifier of the Amazon Web Services account that manages the
domain.


=head2 B<REQUIRED> Name => Str

A name of an Amazon DataZone domain.


=head2 PortalUrl => Str

The data portal URL for the Amazon DataZone domain.


=head2 B<REQUIRED> Status => Str

The status of the Amazon DataZone domain.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::DataZone>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

