# Generated by default/object.tt
package Paws::DataZone::PolicyGrantDetail;
  use Moose;
  has AddToProjectMemberPool => (is => 'ro', isa => 'Paws::DataZone::AddToProjectMemberPoolPolicyGrantDetail', request_name => 'addToProjectMemberPool', traits => ['NameInRequest']);
  has CreateAssetType => (is => 'ro', isa => 'Paws::DataZone::CreateAssetTypePolicyGrantDetail', request_name => 'createAssetType', traits => ['NameInRequest']);
  has CreateDomainUnit => (is => 'ro', isa => 'Paws::DataZone::CreateDomainUnitPolicyGrantDetail', request_name => 'createDomainUnit', traits => ['NameInRequest']);
  has CreateEnvironment => (is => 'ro', isa => 'Paws::DataZone::Unit', request_name => 'createEnvironment', traits => ['NameInRequest']);
  has CreateEnvironmentFromBlueprint => (is => 'ro', isa => 'Paws::DataZone::Unit', request_name => 'createEnvironmentFromBlueprint', traits => ['NameInRequest']);
  has CreateEnvironmentProfile => (is => 'ro', isa => 'Paws::DataZone::CreateEnvironmentProfilePolicyGrantDetail', request_name => 'createEnvironmentProfile', traits => ['NameInRequest']);
  has CreateFormType => (is => 'ro', isa => 'Paws::DataZone::CreateFormTypePolicyGrantDetail', request_name => 'createFormType', traits => ['NameInRequest']);
  has CreateGlossary => (is => 'ro', isa => 'Paws::DataZone::CreateGlossaryPolicyGrantDetail', request_name => 'createGlossary', traits => ['NameInRequest']);
  has CreateProject => (is => 'ro', isa => 'Paws::DataZone::CreateProjectPolicyGrantDetail', request_name => 'createProject', traits => ['NameInRequest']);
  has CreateProjectFromProjectProfile => (is => 'ro', isa => 'Paws::DataZone::CreateProjectFromProjectProfilePolicyGrantDetail', request_name => 'createProjectFromProjectProfile', traits => ['NameInRequest']);
  has DelegateCreateEnvironmentProfile => (is => 'ro', isa => 'Paws::DataZone::Unit', request_name => 'delegateCreateEnvironmentProfile', traits => ['NameInRequest']);
  has OverrideDomainUnitOwners => (is => 'ro', isa => 'Paws::DataZone::OverrideDomainUnitOwnersPolicyGrantDetail', request_name => 'overrideDomainUnitOwners', traits => ['NameInRequest']);
  has OverrideProjectOwners => (is => 'ro', isa => 'Paws::DataZone::OverrideProjectOwnersPolicyGrantDetail', request_name => 'overrideProjectOwners', traits => ['NameInRequest']);
  has UseAssetType => (is => 'ro', isa => 'Paws::DataZone::UseAssetTypePolicyGrantDetail', request_name => 'useAssetType', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::DataZone::PolicyGrantDetail

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::DataZone::PolicyGrantDetail object:

  $service_obj->Method(Att1 => { AddToProjectMemberPool => $value, ..., UseAssetType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::DataZone::PolicyGrantDetail object:

  $result = $service_obj->Method(...);
  $result->Att1->AddToProjectMemberPool

=head1 DESCRIPTION

The details of the policy grant.

=head1 ATTRIBUTES


=head2 AddToProjectMemberPool => L<Paws::DataZone::AddToProjectMemberPoolPolicyGrantDetail>

Specifies that the policy grant is to be added to the members of the
project.


=head2 CreateAssetType => L<Paws::DataZone::CreateAssetTypePolicyGrantDetail>

Specifies that this is a create asset type policy.


=head2 CreateDomainUnit => L<Paws::DataZone::CreateDomainUnitPolicyGrantDetail>

Specifies that this is a create domain unit policy.


=head2 CreateEnvironment => L<Paws::DataZone::Unit>

Specifies that this is a create environment policy.


=head2 CreateEnvironmentFromBlueprint => L<Paws::DataZone::Unit>




=head2 CreateEnvironmentProfile => L<Paws::DataZone::CreateEnvironmentProfilePolicyGrantDetail>

Specifies that this is a create environment profile policy.


=head2 CreateFormType => L<Paws::DataZone::CreateFormTypePolicyGrantDetail>

Specifies that this is a create form type policy.


=head2 CreateGlossary => L<Paws::DataZone::CreateGlossaryPolicyGrantDetail>

Specifies that this is a create glossary policy.


=head2 CreateProject => L<Paws::DataZone::CreateProjectPolicyGrantDetail>

Specifies that this is a create project policy.


=head2 CreateProjectFromProjectProfile => L<Paws::DataZone::CreateProjectFromProjectProfilePolicyGrantDetail>

Specifies whether to create a project from project profile.


=head2 DelegateCreateEnvironmentProfile => L<Paws::DataZone::Unit>

Specifies that this is the delegation of the create environment profile
policy.


=head2 OverrideDomainUnitOwners => L<Paws::DataZone::OverrideDomainUnitOwnersPolicyGrantDetail>

Specifies whether to override domain unit owners.


=head2 OverrideProjectOwners => L<Paws::DataZone::OverrideProjectOwnersPolicyGrantDetail>

Specifies whether to override project owners.


=head2 UseAssetType => L<Paws::DataZone::UseAssetTypePolicyGrantDetail>

Specifies the domain unit(s) whose projects can use this asset type
while creating asset or asset revisions.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::DataZone>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

