# Generated by default/object.tt
package Paws::DataZone::SearchInventoryResultItem;
  use Moose;
  has AssetItem => (is => 'ro', isa => 'Paws::DataZone::AssetItem', request_name => 'assetItem', traits => ['NameInRequest']);
  has DataProductItem => (is => 'ro', isa => 'Paws::DataZone::DataProductResultItem', request_name => 'dataProductItem', traits => ['NameInRequest']);
  has GlossaryItem => (is => 'ro', isa => 'Paws::DataZone::GlossaryItem', request_name => 'glossaryItem', traits => ['NameInRequest']);
  has GlossaryTermItem => (is => 'ro', isa => 'Paws::DataZone::GlossaryTermItem', request_name => 'glossaryTermItem', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::DataZone::SearchInventoryResultItem

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::DataZone::SearchInventoryResultItem object:

  $service_obj->Method(Att1 => { AssetItem => $value, ..., GlossaryTermItem => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::DataZone::SearchInventoryResultItem object:

  $result = $service_obj->Method(...);
  $result->Att1->AssetItem

=head1 DESCRIPTION

The details of the search results.

=head1 ATTRIBUTES


=head2 AssetItem => L<Paws::DataZone::AssetItem>

The asset item included in the search results.


=head2 DataProductItem => L<Paws::DataZone::DataProductResultItem>

The data product.


=head2 GlossaryItem => L<Paws::DataZone::GlossaryItem>

The glossary item included in the search results.


=head2 GlossaryTermItem => L<Paws::DataZone::GlossaryTermItem>

The glossary term item included in the search results.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::DataZone>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

