# Generated by default/object.tt
package Paws::DataZone::SubscribedListingItem;
  use Moose;
  has AssetListing => (is => 'ro', isa => 'Paws::DataZone::SubscribedAssetListing', request_name => 'assetListing', traits => ['NameInRequest']);
  has ProductListing => (is => 'ro', isa => 'Paws::DataZone::SubscribedProductListing', request_name => 'productListing', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::DataZone::SubscribedListingItem

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::DataZone::SubscribedListingItem object:

  $service_obj->Method(Att1 => { AssetListing => $value, ..., ProductListing => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::DataZone::SubscribedListingItem object:

  $result = $service_obj->Method(...);
  $result->Att1->AssetListing

=head1 DESCRIPTION

The published asset for which the subscription grant is created.

=head1 ATTRIBUTES


=head2 AssetListing => L<Paws::DataZone::SubscribedAssetListing>

The asset for which the subscription grant is created.


=head2 ProductListing => L<Paws::DataZone::SubscribedProductListing>

The data product listing.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::DataZone>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

