# Generated by default/object.tt
package Paws::DirectConnect::RouterType;
  use Moose;
  has Platform => (is => 'ro', isa => 'Str', request_name => 'platform', traits => ['NameInRequest']);
  has RouterTypeIdentifier => (is => 'ro', isa => 'Str', request_name => 'routerTypeIdentifier', traits => ['NameInRequest']);
  has Software => (is => 'ro', isa => 'Str', request_name => 'software', traits => ['NameInRequest']);
  has Vendor => (is => 'ro', isa => 'Str', request_name => 'vendor', traits => ['NameInRequest']);
  has XsltTemplateName => (is => 'ro', isa => 'Str', request_name => 'xsltTemplateName', traits => ['NameInRequest']);
  has XsltTemplateNameForMacSec => (is => 'ro', isa => 'Str', request_name => 'xsltTemplateNameForMacSec', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::DirectConnect::RouterType

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::DirectConnect::RouterType object:

  $service_obj->Method(Att1 => { Platform => $value, ..., XsltTemplateNameForMacSec => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::DirectConnect::RouterType object:

  $result = $service_obj->Method(...);
  $result->Att1->Platform

=head1 DESCRIPTION

Information about the virtual router.

=head1 ATTRIBUTES


=head2 Platform => Str

The virtual interface router platform.


=head2 RouterTypeIdentifier => Str

Identifies the router by a combination of vendor, platform, and
software version. For example,
C<CiscoSystemsInc-2900SeriesRouters-IOS124>.


=head2 Software => Str

The router software.


=head2 Vendor => Str

The vendor for the virtual interface's router.


=head2 XsltTemplateName => Str

The template for the virtual interface's router.


=head2 XsltTemplateNameForMacSec => Str

The MAC Security (MACsec) template for the virtual interface's router.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::DirectConnect>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

