# Generated by default/object.tt
package Paws::GlueDataBrew::AllowedStatistics;
  use Moose;
  has Statistics => (is => 'ro', isa => 'ArrayRef[Str|Undef]', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::GlueDataBrew::AllowedStatistics

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::GlueDataBrew::AllowedStatistics object:

  $service_obj->Method(Att1 => { Statistics => $value, ..., Statistics => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::GlueDataBrew::AllowedStatistics object:

  $result = $service_obj->Method(...);
  $result->Att1->Statistics

=head1 DESCRIPTION

Configuration of statistics that are allowed to be run on columns that
contain detected entities. When undefined, no statistics will be
computed on columns that contain detected entities.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Statistics => ArrayRef[Str|Undef]

One or more column statistics to allow for columns that contain
detected entities.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::GlueDataBrew>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

