
package Paws::SSOIdentityStore::ListGroupMembershipsForMember;
  use Moose;
  has IdentityStoreId => (is => 'ro', isa => 'Str', required => 1);
  has MaxResults => (is => 'ro', isa => 'Int');
  has MemberId => (is => 'ro', isa => 'Paws::SSOIdentityStore::MemberId', required => 1);
  has NextToken => (is => 'ro', isa => 'Str');

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'ListGroupMembershipsForMember');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::SSOIdentityStore::ListGroupMembershipsForMemberResponse');
  class_has _result_key => (isa => 'Str', is => 'ro');
1;

### main pod documentation begin ###

=head1 NAME

Paws::SSOIdentityStore::ListGroupMembershipsForMember - Arguments for method ListGroupMembershipsForMember on L<Paws::SSOIdentityStore>

=head1 DESCRIPTION

This class represents the parameters used for calling the method ListGroupMembershipsForMember on the
L<AWS SSO Identity Store|Paws::SSOIdentityStore> service. Use the attributes of this class
as arguments to method ListGroupMembershipsForMember.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to ListGroupMembershipsForMember.

=head1 SYNOPSIS

    my $identitystore = Paws->service('SSOIdentityStore');
    my $ListGroupMembershipsForMemberResponse =
      $identitystore->ListGroupMembershipsForMember(
      IdentityStoreId => 'MyIdentityStoreId',
      MemberId        => {
        UserId => 'MyResourceId',    # min: 1, max: 47; OPTIONAL
      },
      MaxResults => 1,                # OPTIONAL
      NextToken  => 'MyNextToken',    # OPTIONAL
      );

    # Results:
    my $GroupMemberships =
      $ListGroupMembershipsForMemberResponse->GroupMemberships;
    my $NextToken = $ListGroupMembershipsForMemberResponse->NextToken;

# Returns a L<Paws::SSOIdentityStore::ListGroupMembershipsForMemberResponse> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/identitystore/ListGroupMembershipsForMember>

=head1 ATTRIBUTES


=head2 B<REQUIRED> IdentityStoreId => Str

The globally unique identifier for the identity store.



=head2 MaxResults => Int

The maximum number of results to be returned per request. This
parameter is used in the C<ListUsers> and C<ListGroups> requests to
specify how many results to return in one page. The length limit is 50
characters.



=head2 B<REQUIRED> MemberId => L<Paws::SSOIdentityStore::MemberId>

An object that contains the identifier of a group member. Setting the
C<UserID> field to the specific identifier for a user indicates that
the user is a member of the group.



=head2 NextToken => Str

The pagination token used for the C<ListUsers>, C<ListGroups>, and
C<ListGroupMemberships> API operations. This value is generated by the
identity store service. It is returned in the API response if the total
results are more than the size of one page. This token is also returned
when it is used in the API request to search for the next page.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method ListGroupMembershipsForMember in L<Paws::SSOIdentityStore>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

