
package Paws::SSOIdentityStore::ListGroupMemberships;
  use Moose;
  has GroupId => (is => 'ro', isa => 'Str', required => 1);
  has IdentityStoreId => (is => 'ro', isa => 'Str', required => 1);
  has MaxResults => (is => 'ro', isa => 'Int');
  has NextToken => (is => 'ro', isa => 'Str');

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'ListGroupMemberships');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::SSOIdentityStore::ListGroupMembershipsResponse');
  class_has _result_key => (isa => 'Str', is => 'ro');
1;

### main pod documentation begin ###

=head1 NAME

Paws::SSOIdentityStore::ListGroupMemberships - Arguments for method ListGroupMemberships on L<Paws::SSOIdentityStore>

=head1 DESCRIPTION

This class represents the parameters used for calling the method ListGroupMemberships on the
L<AWS SSO Identity Store|Paws::SSOIdentityStore> service. Use the attributes of this class
as arguments to method ListGroupMemberships.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to ListGroupMemberships.

=head1 SYNOPSIS

    my $identitystore = Paws->service('SSOIdentityStore');
    my $ListGroupMembershipsResponse = $identitystore->ListGroupMemberships(
      GroupId         => 'MyResourceId',
      IdentityStoreId => 'MyIdentityStoreId',
      MaxResults      => 1,                     # OPTIONAL
      NextToken       => 'MyNextToken',         # OPTIONAL
    );

    # Results:
    my $GroupMemberships = $ListGroupMembershipsResponse->GroupMemberships;
    my $NextToken        = $ListGroupMembershipsResponse->NextToken;

    # Returns a L<Paws::SSOIdentityStore::ListGroupMembershipsResponse> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/identitystore/ListGroupMemberships>

=head1 ATTRIBUTES


=head2 B<REQUIRED> GroupId => Str

The identifier for a group in the identity store.



=head2 B<REQUIRED> IdentityStoreId => Str

The globally unique identifier for the identity store.



=head2 MaxResults => Int

The maximum number of results to be returned per request. This
parameter is used in all C<List> requests to specify how many results
to return in one page.



=head2 NextToken => Str

The pagination token used for the C<ListUsers>, C<ListGroups> and
C<ListGroupMemberships> API operations. This value is generated by the
identity store service. It is returned in the API response if the total
results are more than the size of one page. This token is also returned
when it is used in the API request to search for the next page.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method ListGroupMemberships in L<Paws::SSOIdentityStore>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

