# Generated by default/object.tt
package Paws::Panorama::JobResourceTags;
  use Moose;
  has ResourceType => (is => 'ro', isa => 'Str', required => 1);
  has Tags => (is => 'ro', isa => 'Paws::Panorama::TagMap', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Panorama::JobResourceTags

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Panorama::JobResourceTags object:

  $service_obj->Method(Att1 => { ResourceType => $value, ..., Tags => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Panorama::JobResourceTags object:

  $result = $service_obj->Method(...);
  $result->Att1->ResourceType

=head1 DESCRIPTION

Tags for a job.

=head1 ATTRIBUTES


=head2 B<REQUIRED> ResourceType => Str

The job's type.


=head2 B<REQUIRED> Tags => L<Paws::Panorama::TagMap>

The job's tags.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Panorama>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

