
package Paws::Omics::StartAnnotationImportJob;
  use Moose;
  has AnnotationFields => (is => 'ro', isa => 'Paws::Omics::AnnotationFieldMap', traits => ['NameInRequest'], request_name => 'annotationFields');
  has DestinationName => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'destinationName', required => 1);
  has FormatOptions => (is => 'ro', isa => 'Paws::Omics::FormatOptions', traits => ['NameInRequest'], request_name => 'formatOptions');
  has Items => (is => 'ro', isa => 'ArrayRef[Paws::Omics::AnnotationImportItemSource]', traits => ['NameInRequest'], request_name => 'items', required => 1);
  has RoleArn => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'roleArn', required => 1);
  has RunLeftNormalization => (is => 'ro', isa => 'Bool', traits => ['NameInRequest'], request_name => 'runLeftNormalization');
  has VersionName => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'versionName');

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'StartAnnotationImportJob');
  class_has _api_uri  => (isa => 'Str', is => 'ro', default => '/import/annotation');
  class_has _api_method  => (isa => 'Str', is => 'ro', default => 'POST');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::Omics::StartAnnotationImportResponse');
1;

### main pod documentation begin ###

=head1 NAME

Paws::Omics::StartAnnotationImportJob - Arguments for method StartAnnotationImportJob on L<Paws::Omics>

=head1 DESCRIPTION

This class represents the parameters used for calling the method StartAnnotationImportJob on the
L<Amazon Omics|Paws::Omics> service. Use the attributes of this class
as arguments to method StartAnnotationImportJob.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to StartAnnotationImportJob.

=head1 SYNOPSIS

    my $omics = Paws->service('Omics');
    my $StartAnnotationImportResponse = $omics->StartAnnotationImportJob(
      DestinationName => 'MyStoreName',
      Items           => [
        {
          Source => 'MyS3Uri',

        },
        ...
      ],
      RoleArn          => 'MyArn',
      AnnotationFields => {
        'MyAnnotationFieldMapKeyString' => 'MyAnnotationFieldMapValueString'
        ,    # key: min: 1, max: 21, value: min: 1, max: 21
      },    # OPTIONAL
      FormatOptions => {
        TsvOptions => {
          ReadOptions => {
            Comment      => 'MyCommentChar',    # min: 1, max: 1; OPTIONAL
            Encoding     => 'MyEncoding',       # min: 1, max: 20; OPTIONAL
            Escape       => 'MyEscapeChar',     # min: 1, max: 1; OPTIONAL
            EscapeQuotes => 1,                  # OPTIONAL
            Header       => 1,                  # OPTIONAL
            LineSep      => 'MyLineSep',        # min: 1, max: 20; OPTIONAL
            Quote        => 'MyQuote',          # min: 1, max: 1; OPTIONAL
            QuoteAll     => 1,                  # OPTIONAL
            Sep          => 'MySeparator',      # min: 1, max: 20; OPTIONAL
          },    # OPTIONAL
        },    # OPTIONAL
        VcfOptions => {
          IgnoreFilterField => 1,    # OPTIONAL
          IgnoreQualField   => 1,    # OPTIONAL
        },    # OPTIONAL
      },    # OPTIONAL
      RunLeftNormalization => 1,                  # OPTIONAL
      VersionName          => 'MyVersionName',    # OPTIONAL
    );

    # Results:
    my $JobId = $StartAnnotationImportResponse->JobId;

    # Returns a L<Paws::Omics::StartAnnotationImportResponse> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/omics/StartAnnotationImportJob>

=head1 ATTRIBUTES


=head2 AnnotationFields => L<Paws::Omics::AnnotationFieldMap>

The annotation schema generated by the parsed annotation data.



=head2 B<REQUIRED> DestinationName => Str

A destination annotation store for the job.



=head2 FormatOptions => L<Paws::Omics::FormatOptions>

Formatting options for the annotation file.



=head2 B<REQUIRED> Items => ArrayRef[L<Paws::Omics::AnnotationImportItemSource>]

Items to import.



=head2 B<REQUIRED> RoleArn => Str

A service role for the job.



=head2 RunLeftNormalization => Bool

The job's left normalization setting.



=head2 VersionName => Str

The name of the annotation store version.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method StartAnnotationImportJob in L<Paws::Omics>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

