# Generated by default/object.tt
package Paws::CloudFront::ImportSource;
  use Moose;
  has SourceARN => (is => 'ro', isa => 'Str', required => 1);
  has SourceType => (is => 'ro', isa => 'Str', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::CloudFront::ImportSource

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CloudFront::ImportSource object:

  $service_obj->Method(Att1 => { SourceARN => $value, ..., SourceType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CloudFront::ImportSource object:

  $result = $service_obj->Method(...);
  $result->Att1->SourceARN

=head1 DESCRIPTION

The import source for the key value store.

=head1 ATTRIBUTES


=head2 B<REQUIRED> SourceARN => Str

The Amazon Resource Name (ARN) of the import source for the key value
store.


=head2 B<REQUIRED> SourceType => Str

The source type of the import source for the key value store.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CloudFront>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

