# Generated by default/object.tt
package Paws::AppFabric::Oauth2Credential;
  use Moose;
  has ClientId => (is => 'ro', isa => 'Str', request_name => 'clientId', traits => ['NameInRequest'], required => 1);
  has ClientSecret => (is => 'ro', isa => 'Str', request_name => 'clientSecret', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::AppFabric::Oauth2Credential

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::AppFabric::Oauth2Credential object:

  $service_obj->Method(Att1 => { ClientId => $value, ..., ClientSecret => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::AppFabric::Oauth2Credential object:

  $result = $service_obj->Method(...);
  $result->Att1->ClientId

=head1 DESCRIPTION

Contains OAuth2 client credential information.

=head1 ATTRIBUTES


=head2 B<REQUIRED> ClientId => Str

The client ID of the client application.


=head2 B<REQUIRED> ClientSecret => Str

The client secret of the client application.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::AppFabric>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

