#!perl

# This file has been modified from the original upstream distribution
# by Peatix, Inc. See the git log for this file for details of changes.

use Paws;
use v5.10;
use Module::Runtime qw/require_module/;
use Getopt::Long;

my $console = 0;
GetOptions('console' => \$console);

my $bo_loaded = 0;

if (not $console) {
  eval {
    require_module 'Browser::Open';
  };
  if ($@) {
    $console = 1;
  }
}

my $user = $ENV{USER} or 'paws federated user';
my $issuer = 'http://aws.amazon.com';
my $dest = 'https://console.aws.amazon.com/';

my $creds = Paws->service('STS')->GetFederationToken(
  Name => $user, 
  Policy => '{"Version": "2012-10-17","Statement": {"Effect": "Allow","Action": "*", "Resource": "*" } }');

my $token = Paws->service('Signin')->GetSigninToken(
  SessionId => $creds->Credentials->AccessKeyId, 
  SessionKey => $creds->Credentials->SecretAccessKey, 
  SessionToken => $creds->Credentials->SessionToken
);

my $url = Paws->service('Signin')->Login(
  Issuer => $issuer,
  Destination => $dest,
  SigninToken => $token->SigninToken
);

if ($console){
  say "Go to :";
  say $url->URL;
} else {
  Browser::Open::open_browser($url->URL);
}
