#!perl

# This file has been modified from the original upstream distribution
# by Peatix, Inc. See the git log for this file for details of changes.

use 5.010;
use strict;
use warnings;

use Data::Dumper;
use Paws;
use ARGV::Struct;
use Term::ANSIColor 2.00 qw();
use DataStruct::Flat;
use List::Util qw(reduce);
use Module::Find;

use Getopt::Long qw/GetOptionsFromArray/;

my @args = @ARGV;

my $aws = Paws->new;

my $service_name = shift @args;
if (not defined $service_name) {
  say "A list of the services you have available";
  say $_ for (sort $aws->available_services);
  exit 1;  
}

my $service = $aws->class_for_service($service_name);

my $opts = {};
my @opts = (
  'caller=s',
  'region=s',
  'endpoint=s',
  'debug',
  'help'
);
#if ($service->meta->find_attribute_by_name('region')) {

GetOptionsFromArray(\@args, $opts, @opts);

my $method_name = shift @args;

if (exists $opts->{caller}) {
  Paws->load_class($opts->{ caller });
  $opts->{ caller } = $opts->{ caller }->new;
}

$service = $aws->service($service_name, %$opts);

my $call;

if (not defined $method_name or not $service->can($method_name)){
  if (defined $method_name) {
    print "Don't know method $method_name on $service_name\n\n";
  } else {
    print "Please specify a method for $service_name\n\n"
  }
  
  print "Maybe you ment:\n";

  say $_ for ($service->operations);
  
  exit 1;
}

my $help_with_method_call = grep { $_ =~ m/^help$/i } @args;

die "HELP!!!" if ($help_with_method_call);

my %args = %{ ARGV::Struct->new(argv => [ '{', @args, '}' ])->parse };

if ($opts->{ debug }) {
  print "Arguments to the call:\n";
  print Dumper(\%args);
} 

my $result = eval { $service->$method_name(%args) };
if ($@) {
  print $@ if ($opts->{debug});
  if (ref($@)){
    if ($@->isa('Paws::Exception')) {
      say "The API retured an error: " . $@->message . "(" . $@->code . ")";
      exit 1;
    } else {
      die $@
    }
  } else {
    die $@;
  }
}

if (ref($result)) {
  my $h = $service->to_hash($result);
  $h = DataStruct::Flat->new->flatten($h);

  my $max_chars = reduce { length($a) > length($b) ? $a : $b } keys %$h;
  $max_chars = length($max_chars);
  #TODO: colorize
  say "$_: " . (' ' x ($max_chars - length($_))) .  $h->{ $_ } for (sort keys %$h);
}
