# Generated by default/object.tt
package Paws::Bedrock::CustomMetricEvaluatorModelConfig;
  use Moose;
  has BedrockEvaluatorModels => (is => 'ro', isa => 'ArrayRef[Paws::Bedrock::CustomMetricBedrockEvaluatorModel]', request_name => 'bedrockEvaluatorModels', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Bedrock::CustomMetricEvaluatorModelConfig

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Bedrock::CustomMetricEvaluatorModelConfig object:

  $service_obj->Method(Att1 => { BedrockEvaluatorModels => $value, ..., BedrockEvaluatorModels => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Bedrock::CustomMetricEvaluatorModelConfig object:

  $result = $service_obj->Method(...);
  $result->Att1->BedrockEvaluatorModels

=head1 DESCRIPTION

Configuration of the evaluator model you want to use to evaluate custom
metrics in an Amazon Bedrock evaluation job.

=head1 ATTRIBUTES


=head2 B<REQUIRED> BedrockEvaluatorModels => ArrayRef[L<Paws::Bedrock::CustomMetricBedrockEvaluatorModel>]

Defines the model you want to evaluate custom metrics in an Amazon
Bedrock evaluation job.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Bedrock>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

