# Generated by default/object.tt
package Paws::Bedrock::EvaluationRagConfigSummary;
  use Moose;
  has BedrockKnowledgeBaseIdentifiers => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'bedrockKnowledgeBaseIdentifiers', traits => ['NameInRequest']);
  has PrecomputedRagSourceIdentifiers => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'precomputedRagSourceIdentifiers', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Bedrock::EvaluationRagConfigSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Bedrock::EvaluationRagConfigSummary object:

  $service_obj->Method(Att1 => { BedrockKnowledgeBaseIdentifiers => $value, ..., PrecomputedRagSourceIdentifiers => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Bedrock::EvaluationRagConfigSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->BedrockKnowledgeBaseIdentifiers

=head1 DESCRIPTION

A summary of the RAG resources used in an Amazon Bedrock Knowledge Base
evaluation job. These resources can be Knowledge Bases in Amazon
Bedrock or RAG sources outside of Amazon Bedrock that you use to
generate your own inference response data.

=head1 ATTRIBUTES


=head2 BedrockKnowledgeBaseIdentifiers => ArrayRef[Str|Undef]

The Amazon Resource Names (ARNs) of the Knowledge Base resources used
for a Knowledge Base evaluation job where Amazon Bedrock invokes the
Knowledge Base for you.


=head2 PrecomputedRagSourceIdentifiers => ArrayRef[Str|Undef]

A label that identifies the RAG sources used for a Knowledge Base
evaluation job where you provide your own inference response data.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Bedrock>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

