
package Paws::Ivschat::GetLoggingConfigurationResponse;
  use Moose;
  has Arn => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'arn');
  has CreateTime => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'createTime');
  has DestinationConfiguration => (is => 'ro', isa => 'Paws::Ivschat::DestinationConfiguration', traits => ['NameInRequest'], request_name => 'destinationConfiguration');
  has Id => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'id');
  has Name => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'name');
  has State => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'state');
  has Tags => (is => 'ro', isa => 'Paws::Ivschat::Tags', traits => ['NameInRequest'], request_name => 'tags');
  has UpdateTime => (is => 'ro', isa => 'Str', traits => ['NameInRequest'], request_name => 'updateTime');

  has _request_id => (is => 'ro', isa => 'Str');
1;

### main pod documentation begin ###

=head1 NAME

Paws::Ivschat::GetLoggingConfigurationResponse

=head1 ATTRIBUTES


=head2 Arn => Str

Logging-configuration ARN, from the request (if C<identifier> was an
ARN).


=head2 CreateTime => Str

Time when the logging configuration was created. This is an ISO 8601
timestamp; I<note that this is returned as a string>.


=head2 DestinationConfiguration => L<Paws::Ivschat::DestinationConfiguration>

A complex type that contains a destination configuration for where chat
content will be logged. There is only one type of destination
(C<cloudWatchLogs>, C<firehose>, or C<s3>) in a
C<destinationConfiguration>.


=head2 Id => Str

Logging-configuration ID, generated by the system. This is a relative
identifier, the part of the ARN that uniquely identifies the logging
configuration.


=head2 Name => Str

Logging-configuration name. This value does not need to be unique.


=head2 State => Str

The state of the logging configuration. When the state is C<ACTIVE>,
the configuration is ready to log chat content.

Valid values are: C<"CREATING">, C<"CREATE_FAILED">, C<"DELETING">, C<"DELETE_FAILED">, C<"UPDATING">, C<"UPDATE_FAILED">, C<"ACTIVE">
=head2 Tags => L<Paws::Ivschat::Tags>

Tags attached to the resource. Array of maps, each of the form
C<string:string (key:value)>.


=head2 UpdateTime => Str

Time of the logging configurationE<rsquo>s last update. This is an ISO
8601 timestamp; I<note that this is returned as a string>.


=head2 _request_id => Str


=cut

