# Generated by default/object.tt
package Paws::FMS::ThirdPartyFirewallMissingExpectedRouteTableViolation;
  use Moose;
  has AvailabilityZone => (is => 'ro', isa => 'Str');
  has CurrentRouteTable => (is => 'ro', isa => 'Str');
  has ExpectedRouteTable => (is => 'ro', isa => 'Str');
  has ViolationTarget => (is => 'ro', isa => 'Str');
  has VPC => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::FMS::ThirdPartyFirewallMissingExpectedRouteTableViolation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::FMS::ThirdPartyFirewallMissingExpectedRouteTableViolation object:

  $service_obj->Method(Att1 => { AvailabilityZone => $value, ..., VPC => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::FMS::ThirdPartyFirewallMissingExpectedRouteTableViolation object:

  $result = $service_obj->Method(...);
  $result->Att1->AvailabilityZone

=head1 DESCRIPTION

The violation details for a third-party firewall that's not associated
with an Firewall Manager managed route table.

=head1 ATTRIBUTES


=head2 AvailabilityZone => Str

The Availability Zone of the firewall subnet that's causing the
violation.


=head2 CurrentRouteTable => Str

The resource ID of the current route table that's associated with the
subnet, if one is available.


=head2 ExpectedRouteTable => Str

The resource ID of the route table that should be associated with the
subnet.


=head2 ViolationTarget => Str

The ID of the third-party firewall or VPC resource that's causing the
violation.


=head2 VPC => Str

The resource ID of the VPC associated with a fireawll subnet that's
causing the violation.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::FMS>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

