# Generated by default/object.tt
package Paws::CustomerProfiles::ExportingLocation;
  use Moose;
  has S3Exporting => (is => 'ro', isa => 'Paws::CustomerProfiles::S3ExportingLocation');

1;

### main pod documentation begin ###

=head1 NAME

Paws::CustomerProfiles::ExportingLocation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CustomerProfiles::ExportingLocation object:

  $service_obj->Method(Att1 => { S3Exporting => $value, ..., S3Exporting => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CustomerProfiles::ExportingLocation object:

  $result = $service_obj->Method(...);
  $result->Att1->S3Exporting

=head1 DESCRIPTION

The S3 location where Identity Resolution Jobs write result files.

=head1 ATTRIBUTES


=head2 S3Exporting => L<Paws::CustomerProfiles::S3ExportingLocation>

Information about the S3 location where Identity Resolution Jobs write
result files.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CustomerProfiles>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

