# Generated by default/object.tt
package Paws::CustomerProfiles::IdentityResolutionJob;
  use Moose;
  has DomainName => (is => 'ro', isa => 'Str');
  has ExportingLocation => (is => 'ro', isa => 'Paws::CustomerProfiles::ExportingLocation');
  has JobEndTime => (is => 'ro', isa => 'Str');
  has JobId => (is => 'ro', isa => 'Str');
  has JobStartTime => (is => 'ro', isa => 'Str');
  has JobStats => (is => 'ro', isa => 'Paws::CustomerProfiles::JobStats');
  has Message => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::CustomerProfiles::IdentityResolutionJob

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CustomerProfiles::IdentityResolutionJob object:

  $service_obj->Method(Att1 => { DomainName => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CustomerProfiles::IdentityResolutionJob object:

  $result = $service_obj->Method(...);
  $result->Att1->DomainName

=head1 DESCRIPTION

Information about the Identity Resolution Job.

=head1 ATTRIBUTES


=head2 DomainName => Str

The unique name of the domain.


=head2 ExportingLocation => L<Paws::CustomerProfiles::ExportingLocation>

The S3 location where the Identity Resolution Job writes result files.


=head2 JobEndTime => Str

The timestamp of when the job was completed.


=head2 JobId => Str

The unique identifier of the Identity Resolution Job.


=head2 JobStartTime => Str

The timestamp of when the job was started or will be started.


=head2 JobStats => L<Paws::CustomerProfiles::JobStats>

Statistics about an Identity Resolution Job.


=head2 Message => Str

The error messages that are generated when the Identity Resolution Job
runs.


=head2 Status => Str

The status of the Identity Resolution Job.

=over

=item *

C<PENDING>: The Identity Resolution Job is scheduled but has not
started yet. If you turn off the Identity Resolution feature in your
domain, jobs in the C<PENDING> state are deleted.

=item *

C<PREPROCESSING>: The Identity Resolution Job is loading your data.

=item *

C<FIND_MATCHING>: The Identity Resolution Job is using the machine
learning model to identify profiles that belong to the same matching
group.

=item *

C<MERGING>: The Identity Resolution Job is merging duplicate profiles.

=item *

C<COMPLETED>: The Identity Resolution Job completed successfully.

=item *

C<PARTIAL_SUCCESS>: There's a system error and not all of the data is
merged. The Identity Resolution Job writes a message indicating the
source of the problem.

=item *

C<FAILED>: The Identity Resolution Job did not merge any data. It
writes a message indicating the source of the problem.

=back




=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CustomerProfiles>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

