# Generated by default/object.tt
package Paws::TaxSettings::TurkeyAdditionalInfo;
  use Moose;
  has Industries => (is => 'ro', isa => 'Str', request_name => 'industries', traits => ['NameInRequest']);
  has KepEmailId => (is => 'ro', isa => 'Str', request_name => 'kepEmailId', traits => ['NameInRequest']);
  has SecondaryTaxId => (is => 'ro', isa => 'Str', request_name => 'secondaryTaxId', traits => ['NameInRequest']);
  has TaxOffice => (is => 'ro', isa => 'Str', request_name => 'taxOffice', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::TaxSettings::TurkeyAdditionalInfo

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::TaxSettings::TurkeyAdditionalInfo object:

  $service_obj->Method(Att1 => { Industries => $value, ..., TaxOffice => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::TaxSettings::TurkeyAdditionalInfo object:

  $result = $service_obj->Method(...);
  $result->Att1->Industries

=head1 DESCRIPTION

Additional tax information associated with your TRN in Turkey.

=head1 ATTRIBUTES


=head2 Industries => Str

The industry information that tells the Tax Settings API if you're
subject to additional withholding taxes. This information required for
business-to-business (B2B) customers. This information is conditionally
mandatory for B2B customers who are subject to KDV tax.


=head2 KepEmailId => Str

The Registered Electronic Mail (REM) that is used to send notarized
communication. This parameter is optional for business-to-business
(B2B) and business-to-government (B2G) customers. It's not required for
business-to-consumer (B2C) customers.


=head2 SecondaryTaxId => Str

Secondary tax ID (E<ldquo>harcama birimi VKNE<rdquo>siE<rdquo>). If one
isn't provided, we will use your VKN as the secondary ID.


=head2 TaxOffice => Str

The tax office where you're registered. You can enter this information
as a string. The Tax Settings API will add this information to your
invoice. This parameter is required for business-to-business (B2B) and
business-to-government customers. It's not required for
business-to-consumer (B2C) customers.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::TaxSettings>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

