# Generated by default/object.tt
package Paws::MediaPackageV2::DashBaseUrl;
  use Moose;
  has DvbPriority => (is => 'ro', isa => 'Int');
  has DvbWeight => (is => 'ro', isa => 'Int');
  has ServiceLocation => (is => 'ro', isa => 'Str');
  has Url => (is => 'ro', isa => 'Str', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::MediaPackageV2::DashBaseUrl

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MediaPackageV2::DashBaseUrl object:

  $service_obj->Method(Att1 => { DvbPriority => $value, ..., Url => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MediaPackageV2::DashBaseUrl object:

  $result = $service_obj->Method(...);
  $result->Att1->DvbPriority

=head1 DESCRIPTION

The base URLs to use for retrieving segments. You can specify multiple
locations and indicate the priority and weight for when each should be
used, for use in mutli-CDN workflows.

=head1 ATTRIBUTES


=head2 DvbPriority => Int

For use with DVB-DASH profiles only. The priority of this location for
servings segments. The lower the number, the higher the priority.


=head2 DvbWeight => Int

For use with DVB-DASH profiles only. The weighting for source locations
that have the same priority.


=head2 ServiceLocation => Str

The name of the source location.


=head2 B<REQUIRED> Url => Str

A source location for segments.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MediaPackageV2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

