# Generated by default/object.tt
package Paws::MediaPackageV2::FilterConfiguration;
  use Moose;
  has ClipStartTime => (is => 'ro', isa => 'Str');
  has End => (is => 'ro', isa => 'Str');
  has ManifestFilter => (is => 'ro', isa => 'Str');
  has Start => (is => 'ro', isa => 'Str');
  has TimeDelaySeconds => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::MediaPackageV2::FilterConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MediaPackageV2::FilterConfiguration object:

  $service_obj->Method(Att1 => { ClipStartTime => $value, ..., TimeDelaySeconds => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MediaPackageV2::FilterConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->ClipStartTime

=head1 DESCRIPTION

Filter configuration includes settings for manifest filtering, start
and end times, and time delay that apply to all of your egress requests
for this manifest.

=head1 ATTRIBUTES


=head2 ClipStartTime => Str

Optionally specify the clip start time for all of your manifest egress
requests. When you include clip start time, note that you cannot use
clip start time query parameters for this manifest's endpoint URL.


=head2 End => Str

Optionally specify the end time for all of your manifest egress
requests. When you include end time, note that you cannot use end time
query parameters for this manifest's endpoint URL.


=head2 ManifestFilter => Str

Optionally specify one or more manifest filters for all of your
manifest egress requests. When you include a manifest filter, note that
you cannot use an identical manifest filter query parameter for this
manifest's endpoint URL.


=head2 Start => Str

Optionally specify the start time for all of your manifest egress
requests. When you include start time, note that you cannot use start
time query parameters for this manifest's endpoint URL.


=head2 TimeDelaySeconds => Int

Optionally specify the time delay for all of your manifest egress
requests. Enter a value that is smaller than your endpoint's startover
window. When you include time delay, note that you cannot use time
delay query parameters for this manifest's endpoint URL.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MediaPackageV2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

