# Generated by default/object.tt
package Paws::SESv2::EmailInsights;
  use Moose;
  has Destination => (is => 'ro', isa => 'Str');
  has Events => (is => 'ro', isa => 'ArrayRef[Paws::SESv2::InsightsEvent]');
  has Isp => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SESv2::EmailInsights

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SESv2::EmailInsights object:

  $service_obj->Method(Att1 => { Destination => $value, ..., Isp => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SESv2::EmailInsights object:

  $result = $service_obj->Method(...);
  $result->Att1->Destination

=head1 DESCRIPTION

An email's insights contain metadata and delivery information about a
specific email.

=head1 ATTRIBUTES


=head2 Destination => Str

The recipient of the email.


=head2 Events => ArrayRef[L<Paws::SESv2::InsightsEvent>]

A list of events associated with the sent email.


=head2 Isp => Str

The recipient's ISP (e.g., C<Gmail>, C<Yahoo>, etc.).



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SESv2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

