# Generated by default/object.tt
package Paws::BedrockRuntime::GuardrailContentBlock;
  use Moose;
  has Image => (is => 'ro', isa => 'Paws::BedrockRuntime::GuardrailImageBlock', request_name => 'image', traits => ['NameInRequest']);
  has Text => (is => 'ro', isa => 'Paws::BedrockRuntime::GuardrailTextBlock', request_name => 'text', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockRuntime::GuardrailContentBlock

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockRuntime::GuardrailContentBlock object:

  $service_obj->Method(Att1 => { Image => $value, ..., Text => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockRuntime::GuardrailContentBlock object:

  $result = $service_obj->Method(...);
  $result->Att1->Image

=head1 DESCRIPTION

The content block to be evaluated by the guardrail.

=head1 ATTRIBUTES


=head2 Image => L<Paws::BedrockRuntime::GuardrailImageBlock>

Image within guardrail content block to be evaluated by the guardrail.


=head2 Text => L<Paws::BedrockRuntime::GuardrailTextBlock>

Text within content block to be evaluated by the guardrail.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

