# Generated by default/object.tt
package Paws::BedrockRuntime::TokenUsage;
  use Moose;
  has CacheReadInputTokens => (is => 'ro', isa => 'Int', request_name => 'cacheReadInputTokens', traits => ['NameInRequest']);
  has CacheWriteInputTokens => (is => 'ro', isa => 'Int', request_name => 'cacheWriteInputTokens', traits => ['NameInRequest']);
  has InputTokens => (is => 'ro', isa => 'Int', request_name => 'inputTokens', traits => ['NameInRequest'], required => 1);
  has OutputTokens => (is => 'ro', isa => 'Int', request_name => 'outputTokens', traits => ['NameInRequest'], required => 1);
  has TotalTokens => (is => 'ro', isa => 'Int', request_name => 'totalTokens', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockRuntime::TokenUsage

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockRuntime::TokenUsage object:

  $service_obj->Method(Att1 => { CacheReadInputTokens => $value, ..., TotalTokens => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockRuntime::TokenUsage object:

  $result = $service_obj->Method(...);
  $result->Att1->CacheReadInputTokens

=head1 DESCRIPTION

The tokens used in a message API inference call.

=head1 ATTRIBUTES


=head2 CacheReadInputTokens => Int

The number of input tokens read from the cache for the request.


=head2 CacheWriteInputTokens => Int

The number of input tokens written to the cache for the request.


=head2 B<REQUIRED> InputTokens => Int

The number of tokens sent in the request to the model.


=head2 B<REQUIRED> OutputTokens => Int

The number of tokens that the model generated for the request.


=head2 B<REQUIRED> TotalTokens => Int

The total of input tokens and tokens generated by the model.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockRuntime>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

