# Generated by default/object.tt
package Paws::Billingconductor::ListBillingGroupCostReportsFilter;
  use Moose;
  has BillingGroupArns => (is => 'ro', isa => 'ArrayRef[Str|Undef]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Billingconductor::ListBillingGroupCostReportsFilter

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Billingconductor::ListBillingGroupCostReportsFilter object:

  $service_obj->Method(Att1 => { BillingGroupArns => $value, ..., BillingGroupArns => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Billingconductor::ListBillingGroupCostReportsFilter object:

  $result = $service_obj->Method(...);
  $result->Att1->BillingGroupArns

=head1 DESCRIPTION

The filter used to retrieve specific C<BillingGroupCostReportElements>.

=head1 ATTRIBUTES


=head2 BillingGroupArns => ArrayRef[Str|Undef]

The list of Amazon Resource Names (ARNs) used to filter billing groups
to retrieve reports.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Billingconductor>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

