# Generated by default/object.tt
package Paws::Inspector2::LambdaFunctionAggregation;
  use Moose;
  has FunctionNames => (is => 'ro', isa => 'ArrayRef[Paws::Inspector2::StringFilter]', request_name => 'functionNames', traits => ['NameInRequest']);
  has FunctionTags => (is => 'ro', isa => 'ArrayRef[Paws::Inspector2::MapFilter]', request_name => 'functionTags', traits => ['NameInRequest']);
  has ResourceIds => (is => 'ro', isa => 'ArrayRef[Paws::Inspector2::StringFilter]', request_name => 'resourceIds', traits => ['NameInRequest']);
  has Runtimes => (is => 'ro', isa => 'ArrayRef[Paws::Inspector2::StringFilter]', request_name => 'runtimes', traits => ['NameInRequest']);
  has SortBy => (is => 'ro', isa => 'Str', request_name => 'sortBy', traits => ['NameInRequest']);
  has SortOrder => (is => 'ro', isa => 'Str', request_name => 'sortOrder', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Inspector2::LambdaFunctionAggregation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Inspector2::LambdaFunctionAggregation object:

  $service_obj->Method(Att1 => { FunctionNames => $value, ..., SortOrder => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Inspector2::LambdaFunctionAggregation object:

  $result = $service_obj->Method(...);
  $result->Att1->FunctionNames

=head1 DESCRIPTION

The details that define a findings aggregation based on Amazon Web
Services Lambda functions.

=head1 ATTRIBUTES


=head2 FunctionNames => ArrayRef[L<Paws::Inspector2::StringFilter>]

The Amazon Web Services Lambda function names to include in the
aggregation results.


=head2 FunctionTags => ArrayRef[L<Paws::Inspector2::MapFilter>]

The tags to include in the aggregation results.


=head2 ResourceIds => ArrayRef[L<Paws::Inspector2::StringFilter>]

The resource IDs to include in the aggregation results.


=head2 Runtimes => ArrayRef[L<Paws::Inspector2::StringFilter>]

Returns findings aggregated by Amazon Web Services Lambda function
runtime environments.


=head2 SortBy => Str

The finding severity to use for sorting the results.


=head2 SortOrder => Str

The order to use for sorting the results.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Inspector2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

