# Generated by default/object.tt
package Paws::PcaConnectorAd::TemplateV4;
  use Moose;
  has CertificateValidity => (is => 'ro', isa => 'Paws::PcaConnectorAd::CertificateValidity', required => 1);
  has EnrollmentFlags => (is => 'ro', isa => 'Paws::PcaConnectorAd::EnrollmentFlagsV4', required => 1);
  has Extensions => (is => 'ro', isa => 'Paws::PcaConnectorAd::ExtensionsV4', required => 1);
  has GeneralFlags => (is => 'ro', isa => 'Paws::PcaConnectorAd::GeneralFlagsV4', required => 1);
  has HashAlgorithm => (is => 'ro', isa => 'Str');
  has PrivateKeyAttributes => (is => 'ro', isa => 'Paws::PcaConnectorAd::PrivateKeyAttributesV4', required => 1);
  has PrivateKeyFlags => (is => 'ro', isa => 'Paws::PcaConnectorAd::PrivateKeyFlagsV4', required => 1);
  has SubjectNameFlags => (is => 'ro', isa => 'Paws::PcaConnectorAd::SubjectNameFlagsV4', required => 1);
  has SupersededTemplates => (is => 'ro', isa => 'ArrayRef[Str|Undef]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::PcaConnectorAd::TemplateV4

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::PcaConnectorAd::TemplateV4 object:

  $service_obj->Method(Att1 => { CertificateValidity => $value, ..., SupersededTemplates => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::PcaConnectorAd::TemplateV4 object:

  $result = $service_obj->Method(...);
  $result->Att1->CertificateValidity

=head1 DESCRIPTION

v4 template schema that can use either Legacy Cryptographic Providers
or Key Storage Providers.

=head1 ATTRIBUTES


=head2 B<REQUIRED> CertificateValidity => L<Paws::PcaConnectorAd::CertificateValidity>

Certificate validity describes the validity and renewal periods of a
certificate.


=head2 B<REQUIRED> EnrollmentFlags => L<Paws::PcaConnectorAd::EnrollmentFlagsV4>

Enrollment flags describe the enrollment settings for certificates
using the existing private key and deleting expired or revoked
certificates.


=head2 B<REQUIRED> Extensions => L<Paws::PcaConnectorAd::ExtensionsV4>

Extensions describe the key usage extensions and application policies
for a template.


=head2 B<REQUIRED> GeneralFlags => L<Paws::PcaConnectorAd::GeneralFlagsV4>

General flags describe whether the template is used for computers or
users and if the template can be used with autoenrollment.


=head2 HashAlgorithm => Str

Specifies the hash algorithm used to hash the private key. Hash
algorithm can only be specified when using Key Storage Providers.


=head2 B<REQUIRED> PrivateKeyAttributes => L<Paws::PcaConnectorAd::PrivateKeyAttributesV4>

Private key attributes allow you to specify the minimal key length, key
spec, key usage, and cryptographic providers for the private key of a
certificate for v4 templates. V4 templates allow you to use either Key
Storage Providers or Legacy Cryptographic Service Providers. You
specify the cryptography provider category in private key flags.


=head2 B<REQUIRED> PrivateKeyFlags => L<Paws::PcaConnectorAd::PrivateKeyFlagsV4>

Private key flags for v4 templates specify the client compatibility, if
the private key can be exported, if user input is required when using a
private key, if an alternate signature algorithm should be used, and if
certificates are renewed using the same private key.


=head2 B<REQUIRED> SubjectNameFlags => L<Paws::PcaConnectorAd::SubjectNameFlagsV4>

Subject name flags describe the subject name and subject alternate name
that is included in a certificate.


=head2 SupersededTemplates => ArrayRef[Str|Undef]

List of templates in Active Directory that are superseded by this
template.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::PcaConnectorAd>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

