# Generated by default/object.tt
package Paws::TimestreamQuery::QuerySpatialCoverage;
  use Moose;
  has Max => (is => 'ro', isa => 'Paws::TimestreamQuery::QuerySpatialCoverageMax');

1;

### main pod documentation begin ###

=head1 NAME

Paws::TimestreamQuery::QuerySpatialCoverage

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::TimestreamQuery::QuerySpatialCoverage object:

  $service_obj->Method(Att1 => { Max => $value, ..., Max => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::TimestreamQuery::QuerySpatialCoverage object:

  $result = $service_obj->Method(...);
  $result->Att1->Max

=head1 DESCRIPTION

Provides insights into the spatial coverage of the query, including the
table with sub-optimal (max) spatial pruning. This information can help
you identify areas for improvement in your partitioning strategy to
enhance spatial pruning

For example, you can do the following with the C<QuerySpatialCoverage>
information:

=over

=item *

Add measure_name or use customer-defined partition key
(https://docs.aws.amazon.com/timestream/latest/developerguide/customer-defined-partition-keys.html)
(CDPK) predicates.

=item *

If you've already done the preceding action, remove functions around
them or clauses, such as C<LIKE>.

=back


=head1 ATTRIBUTES


=head2 Max => L<Paws::TimestreamQuery::QuerySpatialCoverageMax>

Provides insights into the spatial coverage of the executed query and
the table with the most inefficient spatial pruning.

=over

=item *

C<Value> E<ndash> The maximum ratio of spatial coverage.

=item *

C<TableArn> E<ndash> The Amazon Resource Name (ARN) of the table with
sub-optimal spatial pruning.

=item *

C<PartitionKey> E<ndash> The partition key used for partitioning, which
can be a default C<measure_name> or a CDPK.

=back




=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::TimestreamQuery>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

