# Generated by default/object.tt
package Paws::BedrockAgent::FlowNode;
  use Moose;
  has Configuration => (is => 'ro', isa => 'Paws::BedrockAgent::FlowNodeConfiguration', request_name => 'configuration', traits => ['NameInRequest']);
  has Inputs => (is => 'ro', isa => 'ArrayRef[Paws::BedrockAgent::FlowNodeInput]', request_name => 'inputs', traits => ['NameInRequest']);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);
  has Outputs => (is => 'ro', isa => 'ArrayRef[Paws::BedrockAgent::FlowNodeOutput]', request_name => 'outputs', traits => ['NameInRequest']);
  has Type => (is => 'ro', isa => 'Str', request_name => 'type', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgent::FlowNode

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgent::FlowNode object:

  $service_obj->Method(Att1 => { Configuration => $value, ..., Type => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgent::FlowNode object:

  $result = $service_obj->Method(...);
  $result->Att1->Configuration

=head1 DESCRIPTION

Contains configurations about a node in the flow.

=head1 ATTRIBUTES


=head2 Configuration => L<Paws::BedrockAgent::FlowNodeConfiguration>

Contains configurations for the node.


=head2 Inputs => ArrayRef[L<Paws::BedrockAgent::FlowNodeInput>]

An array of objects, each of which contains information about an input
into the node.


=head2 B<REQUIRED> Name => Str

A name for the node.


=head2 Outputs => ArrayRef[L<Paws::BedrockAgent::FlowNodeOutput>]

A list of objects, each of which contains information about an output
from the node.


=head2 B<REQUIRED> Type => Str

The type of node. This value must match the name of the key that you
provide in the configuration you provide in the
C<FlowNodeConfiguration> field.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgent>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

