# Generated by default/object.tt
package Paws::BedrockAgent::FlowCondition;
  use Moose;
  has Expression => (is => 'ro', isa => 'Str', request_name => 'expression', traits => ['NameInRequest']);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgent::FlowCondition

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgent::FlowCondition object:

  $service_obj->Method(Att1 => { Expression => $value, ..., Name => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgent::FlowCondition object:

  $result = $service_obj->Method(...);
  $result->Att1->Expression

=head1 DESCRIPTION

Defines a condition in the condition node.

=head1 ATTRIBUTES


=head2 Expression => Str

Defines the condition. You must refer to at least one of the inputs in
the condition. For more information, expand the Condition node section
in Node types in prompt flows
(https://docs.aws.amazon.com/bedrock/latest/userguide/flows-how-it-works.html#flows-nodes).


=head2 B<REQUIRED> Name => Str

A name for the condition that you can reference.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgent>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

