# Generated by default/object.tt
package Paws::BedrockAgent::PromptVariant;
  use Moose;
  has AdditionalModelRequestFields => (is => 'ro', isa => 'Paws::BedrockAgent::Document', request_name => 'additionalModelRequestFields', traits => ['NameInRequest']);
  has GenAiResource => (is => 'ro', isa => 'Paws::BedrockAgent::PromptGenAiResource', request_name => 'genAiResource', traits => ['NameInRequest']);
  has InferenceConfiguration => (is => 'ro', isa => 'Paws::BedrockAgent::PromptInferenceConfiguration', request_name => 'inferenceConfiguration', traits => ['NameInRequest']);
  has Metadata => (is => 'ro', isa => 'ArrayRef[Paws::BedrockAgent::PromptMetadataEntry]', request_name => 'metadata', traits => ['NameInRequest']);
  has ModelId => (is => 'ro', isa => 'Str', request_name => 'modelId', traits => ['NameInRequest']);
  has Name => (is => 'ro', isa => 'Str', request_name => 'name', traits => ['NameInRequest'], required => 1);
  has TemplateConfiguration => (is => 'ro', isa => 'Paws::BedrockAgent::PromptTemplateConfiguration', request_name => 'templateConfiguration', traits => ['NameInRequest'], required => 1);
  has TemplateType => (is => 'ro', isa => 'Str', request_name => 'templateType', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockAgent::PromptVariant

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockAgent::PromptVariant object:

  $service_obj->Method(Att1 => { AdditionalModelRequestFields => $value, ..., TemplateType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockAgent::PromptVariant object:

  $result = $service_obj->Method(...);
  $result->Att1->AdditionalModelRequestFields

=head1 DESCRIPTION

Contains details about a variant of the prompt.

=head1 ATTRIBUTES


=head2 AdditionalModelRequestFields => L<Paws::BedrockAgent::Document>

Contains model-specific inference configurations that aren't in the
C<inferenceConfiguration> field. To see model-specific inference
parameters, see Inference request parameters and response fields for
foundation models
(https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html).


=head2 GenAiResource => L<Paws::BedrockAgent::PromptGenAiResource>

Specifies a generative AI resource with which to use the prompt.


=head2 InferenceConfiguration => L<Paws::BedrockAgent::PromptInferenceConfiguration>

Contains inference configurations for the prompt variant.


=head2 Metadata => ArrayRef[L<Paws::BedrockAgent::PromptMetadataEntry>]

An array of objects, each containing a key-value pair that defines a
metadata tag and value to attach to a prompt variant.


=head2 ModelId => Str

The unique identifier of the model or inference profile
(https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference.html)
with which to run inference on the prompt.


=head2 B<REQUIRED> Name => Str

The name of the prompt variant.


=head2 B<REQUIRED> TemplateConfiguration => L<Paws::BedrockAgent::PromptTemplateConfiguration>

Contains configurations for the prompt template.


=head2 B<REQUIRED> TemplateType => Str

The type of prompt template to use.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockAgent>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

