# Generated by default/object.tt
package Paws::BackupSearch::ExportSpecification;
  use Moose;
  has S3ExportSpecification => (is => 'ro', isa => 'Paws::BackupSearch::S3ExportSpecification', request_name => 's3ExportSpecification', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BackupSearch::ExportSpecification

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BackupSearch::ExportSpecification object:

  $service_obj->Method(Att1 => { S3ExportSpecification => $value, ..., S3ExportSpecification => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BackupSearch::ExportSpecification object:

  $result = $service_obj->Method(...);
  $result->Att1->S3ExportSpecification

=head1 DESCRIPTION

This contains the export specification object.

=head1 ATTRIBUTES


=head2 S3ExportSpecification => L<Paws::BackupSearch::S3ExportSpecification>

This specifies the destination Amazon S3 bucket for the export job.
And, if included, it also specifies the destination prefix.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BackupSearch>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

