name             = Paws-Docs
author           = Jose Luis Martinez <jlmartinez@capside.com>
license          = Apache_2_0
copyright_holder = Jose Luis Martinez
copyright_year   = 2024
main_module      = lib/Paws/Docs.pm
abstract         = Per-shape POD pages for the Paws AWS SDK

[VersionFromMainModule]

[GatherDir]
exclude_filename = dist.ini
exclude_filename = Makefile
exclude_match    = ^script/

[MakeMaker::Awesome]
WriteMakefile_arg = MIN_PERL_VERSION => '5.012001'

[MetaJSON]
[MetaResources]
homepage             = https://github.com/pplu/aws-sdk-perl
repository.url       = https://github.com/pplu/aws-sdk-perl.git
repository.web       = https://github.com/pplu/aws-sdk-perl
repository.type      = git
bugtracker.web       = https://github.com/pplu/aws-sdk-perl/issues

[License]
[ExtraTests]
[ExecDir]
[Manifest]
[ConfirmRelease]
[UploadToCPAN]

[Prereqs]
perl = 5.012001
; Paws::Docs is pure POD - no runtime perl deps.
