# Generated by default/object.tt
package Paws::PinpointSMSVoiceV2::OptOutListInformation;
  use Moose;
  has CreatedTimestamp => (is => 'ro', isa => 'Str', required => 1);
  has OptOutListArn => (is => 'ro', isa => 'Str', required => 1);
  has OptOutListName => (is => 'ro', isa => 'Str', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::PinpointSMSVoiceV2::OptOutListInformation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::PinpointSMSVoiceV2::OptOutListInformation object:

  $service_obj->Method(Att1 => { CreatedTimestamp => $value, ..., OptOutListName => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::PinpointSMSVoiceV2::OptOutListInformation object:

  $result = $service_obj->Method(...);
  $result->Att1->CreatedTimestamp

=head1 DESCRIPTION

The information for all OptOutList in an Amazon Web Services account.

=head1 ATTRIBUTES


=head2 B<REQUIRED> CreatedTimestamp => Str

The time when the OutOutList was created, in UNIX epoch time
(https://www.epochconverter.com/) format.


=head2 B<REQUIRED> OptOutListArn => Str

The Amazon Resource Name (ARN) of the OptOutList.


=head2 B<REQUIRED> OptOutListName => Str

The name of the OptOutList.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::PinpointSMSVoiceV2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

