# Generated by default/object.tt
package Paws::CloudFormation::HookResultSummary;
  use Moose;
  has FailureMode => (is => 'ro', isa => 'Str');
  has HookStatusReason => (is => 'ro', isa => 'Str');
  has InvocationPoint => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');
  has TypeConfigurationVersionId => (is => 'ro', isa => 'Str');
  has TypeName => (is => 'ro', isa => 'Str');
  has TypeVersionId => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::CloudFormation::HookResultSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::CloudFormation::HookResultSummary object:

  $service_obj->Method(Att1 => { FailureMode => $value, ..., TypeVersionId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::CloudFormation::HookResultSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->FailureMode

=head1 DESCRIPTION

Describes a Hook invocation, its status, and the reason for its status.

=head1 ATTRIBUTES


=head2 FailureMode => Str

The failure mode of the invocation. The following are potential modes:

=over

=item *

C<FAIL>: If the hook invocation returns a failure, then the requested
target operation should fail.

=item *

C<WARN>: If the hook invocation returns a failure, then the requested
target operation should warn.

=back



=head2 HookStatusReason => Str

A description of the Hook results status. For example, if the Hook
result is in a C<FAILED> state, this may contain additional information
for the C<FAILED> state.


=head2 InvocationPoint => Str

The exact point in the provisioning logic where the Hook runs.


=head2 Status => Str

The state of the Hook invocation.


=head2 TypeConfigurationVersionId => Str

The version of the Hook type configuration.


=head2 TypeName => Str

The type name of the Hook being invoked.


=head2 TypeVersionId => Str

The version of the Hook being invoked.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::CloudFormation>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

