# Generated by default/object.tt
package Paws::RAM::AssociatedPermission;
  use Moose;
  has Arn => (is => 'ro', isa => 'Str', request_name => 'arn', traits => ['NameInRequest']);
  has DefaultVersion => (is => 'ro', isa => 'Bool', request_name => 'defaultVersion', traits => ['NameInRequest']);
  has FeatureSet => (is => 'ro', isa => 'Str', request_name => 'featureSet', traits => ['NameInRequest']);
  has LastUpdatedTime => (is => 'ro', isa => 'Str', request_name => 'lastUpdatedTime', traits => ['NameInRequest']);
  has PermissionVersion => (is => 'ro', isa => 'Str', request_name => 'permissionVersion', traits => ['NameInRequest']);
  has ResourceShareArn => (is => 'ro', isa => 'Str', request_name => 'resourceShareArn', traits => ['NameInRequest']);
  has ResourceType => (is => 'ro', isa => 'Str', request_name => 'resourceType', traits => ['NameInRequest']);
  has Status => (is => 'ro', isa => 'Str', request_name => 'status', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::RAM::AssociatedPermission

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::RAM::AssociatedPermission object:

  $service_obj->Method(Att1 => { Arn => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::RAM::AssociatedPermission object:

  $result = $service_obj->Method(...);
  $result->Att1->Arn

=head1 DESCRIPTION

An object that describes a managed permission associated with a
resource share.

=head1 ATTRIBUTES


=head2 Arn => Str

The Amazon Resource Name (ARN)
(https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
of the associated managed permission.


=head2 DefaultVersion => Bool

Indicates whether the associated resource share is using the default
version of the permission.


=head2 FeatureSet => Str

Indicates what features are available for this resource share. This
parameter can have one of the following values:

=over

=item *

B<STANDARD> E<ndash> A resource share that supports all functionality.
These resource shares are visible to all principals you share the
resource share with. You can modify these resource shares in RAM using
the console or APIs. This resource share might have been created by
RAM, or it might have been B<CREATED_FROM_POLICY> and then promoted.

=item *

B<CREATED_FROM_POLICY> E<ndash> The customer manually shared a resource
by attaching a resource-based policy. That policy did not match any
existing managed permissions, so RAM created this customer managed
permission automatically on the customer's behalf based on the attached
policy document. This type of resource share is visible only to the
Amazon Web Services account that created it. You can't modify it in RAM
unless you promote it. For more information, see
PromoteResourceShareCreatedFromPolicy.

=item *

B<PROMOTING_TO_STANDARD> E<ndash> This resource share was originally
C<CREATED_FROM_POLICY>, but the customer ran the
PromoteResourceShareCreatedFromPolicy and that operation is still in
progress. This value changes to C<STANDARD> when complete.

=back



=head2 LastUpdatedTime => Str

The date and time when the association between the permission and the
resource share was last updated.


=head2 PermissionVersion => Str

The version of the permission currently associated with the resource
share.


=head2 ResourceShareArn => Str

The Amazon Resource Name (ARN)
(https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
of a resource share associated with this permission.


=head2 ResourceType => Str

The resource type to which this permission applies.


=head2 Status => Str

The current status of the association between the permission and the
resource share. The following are the possible values:

=over

=item *

C<ATTACHABLE> E<ndash> This permission or version can be associated
with resource shares.

=item *

C<UNATTACHABLE> E<ndash> This permission or version can't currently be
associated with resource shares.

=item *

C<DELETING> E<ndash> This permission or version is in the process of
being deleted.

=item *

C<DELETED> E<ndash> This permission or version is deleted.

=back




=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::RAM>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

