# Generated by default/object.tt
package Paws::AmplifyUIBuilder::FieldValidationConfiguration;
  use Moose;
  has NumValues => (is => 'ro', isa => 'ArrayRef[Int]', request_name => 'numValues', traits => ['NameInRequest']);
  has StrValues => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'strValues', traits => ['NameInRequest']);
  has Type => (is => 'ro', isa => 'Str', request_name => 'type', traits => ['NameInRequest'], required => 1);
  has ValidationMessage => (is => 'ro', isa => 'Str', request_name => 'validationMessage', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::AmplifyUIBuilder::FieldValidationConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::AmplifyUIBuilder::FieldValidationConfiguration object:

  $service_obj->Method(Att1 => { NumValues => $value, ..., ValidationMessage => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::AmplifyUIBuilder::FieldValidationConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->NumValues

=head1 DESCRIPTION

Describes the validation configuration for a field.

=head1 ATTRIBUTES


=head2 NumValues => ArrayRef[Int]

The validation to perform on a number value.


=head2 StrValues => ArrayRef[Str|Undef]

The validation to perform on a string value.


=head2 B<REQUIRED> Type => Str

The validation to perform on an object type.C<>


=head2 ValidationMessage => Str

The validation message to display.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::AmplifyUIBuilder>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

