# Generated by default/object.tt
package Paws::MailManager::AddonSubscription;
  use Moose;
  has AddonName => (is => 'ro', isa => 'Str');
  has AddonSubscriptionArn => (is => 'ro', isa => 'Str');
  has AddonSubscriptionId => (is => 'ro', isa => 'Str');
  has CreatedTimestamp => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::MailManager::AddonSubscription

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MailManager::AddonSubscription object:

  $service_obj->Method(Att1 => { AddonName => $value, ..., CreatedTimestamp => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MailManager::AddonSubscription object:

  $result = $service_obj->Method(...);
  $result->Att1->AddonName

=head1 DESCRIPTION

A subscription for an Add On representing the acceptance of its terms
of use and additional pricing.

=head1 ATTRIBUTES


=head2 AddonName => Str

The name of the Add On.


=head2 AddonSubscriptionArn => Str

The Amazon Resource Name (ARN) of the Add On subscription.


=head2 AddonSubscriptionId => Str

The unique ID of the Add On subscription.


=head2 CreatedTimestamp => Str

The timestamp of when the Add On subscription was created.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MailManager>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

