# Generated by default/object.tt
package Paws::MailManager::PolicyCondition;
  use Moose;
  has BooleanExpression => (is => 'ro', isa => 'Paws::MailManager::IngressBooleanExpression');
  has IpExpression => (is => 'ro', isa => 'Paws::MailManager::IngressIpv4Expression');
  has Ipv6Expression => (is => 'ro', isa => 'Paws::MailManager::IngressIpv6Expression');
  has StringExpression => (is => 'ro', isa => 'Paws::MailManager::IngressStringExpression');
  has TlsExpression => (is => 'ro', isa => 'Paws::MailManager::IngressTlsProtocolExpression');

1;

### main pod documentation begin ###

=head1 NAME

Paws::MailManager::PolicyCondition

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MailManager::PolicyCondition object:

  $service_obj->Method(Att1 => { BooleanExpression => $value, ..., TlsExpression => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MailManager::PolicyCondition object:

  $result = $service_obj->Method(...);
  $result->Att1->BooleanExpression

=head1 DESCRIPTION

The email traffic filtering conditions which are contained in a traffic
policy resource.

=head1 ATTRIBUTES


=head2 BooleanExpression => L<Paws::MailManager::IngressBooleanExpression>

This represents a boolean type condition matching on the incoming mail.
It performs the boolean operation configured in 'Operator' and
evaluates the 'Protocol' object against the 'Value'.


=head2 IpExpression => L<Paws::MailManager::IngressIpv4Expression>

This represents an IP based condition matching on the incoming mail. It
performs the operation configured in 'Operator' and evaluates the
'Protocol' object against the 'Value'.


=head2 Ipv6Expression => L<Paws::MailManager::IngressIpv6Expression>

This represents an IPv6 based condition matching on the incoming mail.
It performs the operation configured in 'Operator' and evaluates the
'Protocol' object against the 'Value'.


=head2 StringExpression => L<Paws::MailManager::IngressStringExpression>

This represents a string based condition matching on the incoming mail.
It performs the string operation configured in 'Operator' and evaluates
the 'Protocol' object against the 'Value'.


=head2 TlsExpression => L<Paws::MailManager::IngressTlsProtocolExpression>

This represents a TLS based condition matching on the incoming mail. It
performs the operation configured in 'Operator' and evaluates the
'Protocol' object against the 'Value'.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MailManager>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

