# Generated by default/object.tt
package Paws::MailManager::RuleBooleanToEvaluate;
  use Moose;
  has Analysis => (is => 'ro', isa => 'Paws::MailManager::Analysis');
  has Attribute => (is => 'ro', isa => 'Str');
  has IsInAddressList => (is => 'ro', isa => 'Paws::MailManager::RuleIsInAddressList');

1;

### main pod documentation begin ###

=head1 NAME

Paws::MailManager::RuleBooleanToEvaluate

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::MailManager::RuleBooleanToEvaluate object:

  $service_obj->Method(Att1 => { Analysis => $value, ..., IsInAddressList => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::MailManager::RuleBooleanToEvaluate object:

  $result = $service_obj->Method(...);
  $result->Att1->Analysis

=head1 DESCRIPTION

The union type representing the allowed types of operands for a boolean
condition.

=head1 ATTRIBUTES


=head2 Analysis => L<Paws::MailManager::Analysis>

The Add On ARN and its returned value to evaluate in a boolean
condition expression.


=head2 Attribute => Str

The boolean type representing the allowed attribute types for an email.


=head2 IsInAddressList => L<Paws::MailManager::RuleIsInAddressList>

The structure representing the address lists and address list attribute
that will be used in evaluation of boolean expression.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::MailManager>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

