# Generated by default/object.tt
package Paws::Neptunedata::RefreshStatisticsIdMap;
  use Moose;
  has StatisticsId => (is => 'ro', isa => 'Str', request_name => 'statisticsId', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Neptunedata::RefreshStatisticsIdMap

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Neptunedata::RefreshStatisticsIdMap object:

  $service_obj->Method(Att1 => { StatisticsId => $value, ..., StatisticsId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Neptunedata::RefreshStatisticsIdMap object:

  $result = $service_obj->Method(...);
  $result->Att1->StatisticsId

=head1 DESCRIPTION

Statistics for C<REFRESH> mode.

=head1 ATTRIBUTES


=head2 StatisticsId => Str

The ID of the statistics generation run that is currently occurring.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Neptunedata>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

