# Generated by default/object.tt
package Paws::Neptunedata::SparqlRecord;
  use Moose;
  has CommitTimestampInMillis => (is => 'ro', isa => 'Int', request_name => 'commitTimestamp', traits => ['NameInRequest'], required => 1);
  has Data => (is => 'ro', isa => 'Paws::Neptunedata::SparqlData', request_name => 'data', traits => ['NameInRequest'], required => 1);
  has EventId => (is => 'ro', isa => 'Paws::Neptunedata::StringValuedMap', request_name => 'eventId', traits => ['NameInRequest'], required => 1);
  has IsLastOp => (is => 'ro', isa => 'Bool', request_name => 'isLastOp', traits => ['NameInRequest']);
  has Op => (is => 'ro', isa => 'Str', request_name => 'op', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Neptunedata::SparqlRecord

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Neptunedata::SparqlRecord object:

  $service_obj->Method(Att1 => { CommitTimestampInMillis => $value, ..., Op => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Neptunedata::SparqlRecord object:

  $result = $service_obj->Method(...);
  $result->Att1->CommitTimestampInMillis

=head1 DESCRIPTION

A serialized SPARQL stream record capturing a change-log entry for the
RDF graph.

=head1 ATTRIBUTES


=head2 B<REQUIRED> CommitTimestampInMillis => Int

The time at which the commit for the transaction was requested, in
milliseconds from the Unix epoch.


=head2 B<REQUIRED> Data => L<Paws::Neptunedata::SparqlData>

The serialized SPARQL change record. The serialization formats of each
record are described in more detail in Serialization Formats in Neptune
Streams
(https://docs.aws.amazon.com/neptune/latest/userguide/streams-change-formats.html).


=head2 B<REQUIRED> EventId => L<Paws::Neptunedata::StringValuedMap>

The sequence identifier of the stream change record.


=head2 IsLastOp => Bool

Only present if this operation is the last one in its transaction. If
present, it is set to true. It is useful for ensuring that an entire
transaction is consumed.


=head2 B<REQUIRED> Op => Str

The operation that created the change.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Neptunedata>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

