# Generated by default/object.tt
package Paws::SageMaker::EmrServerlessSettings;
  use Moose;
  has ExecutionRoleArn => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMaker::EmrServerlessSettings

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMaker::EmrServerlessSettings object:

  $service_obj->Method(Att1 => { ExecutionRoleArn => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMaker::EmrServerlessSettings object:

  $result = $service_obj->Method(...);
  $result->Att1->ExecutionRoleArn

=head1 DESCRIPTION

The settings for running Amazon EMR Serverless jobs in SageMaker
Canvas.

=head1 ATTRIBUTES


=head2 ExecutionRoleArn => Str

The Amazon Resource Name (ARN) of the Amazon Web Services IAM role that
is assumed for running Amazon EMR Serverless jobs in SageMaker Canvas.
This role should have the necessary permissions to read and write data
attached and a trust relationship with EMR Serverless.


=head2 Status => Str

Describes whether Amazon EMR Serverless job capabilities are enabled or
disabled in the SageMaker Canvas application.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMaker>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

