# Generated by default/object.tt
package Paws::SageMaker::EndpointPerformance;
  use Moose;
  has EndpointInfo => (is => 'ro', isa => 'Paws::SageMaker::EndpointInfo', required => 1);
  has Metrics => (is => 'ro', isa => 'Paws::SageMaker::InferenceMetrics', required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMaker::EndpointPerformance

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMaker::EndpointPerformance object:

  $service_obj->Method(Att1 => { EndpointInfo => $value, ..., Metrics => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMaker::EndpointPerformance object:

  $result = $service_obj->Method(...);
  $result->Att1->EndpointInfo

=head1 DESCRIPTION

The performance results from running an Inference Recommender job on an
existing endpoint.

=head1 ATTRIBUTES


=head2 B<REQUIRED> EndpointInfo => L<Paws::SageMaker::EndpointInfo>




=head2 B<REQUIRED> Metrics => L<Paws::SageMaker::InferenceMetrics>

The metrics for an existing endpoint.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMaker>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

