# Generated by default/object.tt
package Paws::SageMaker::EnvironmentParameterRanges;
  use Moose;
  has CategoricalParameterRanges => (is => 'ro', isa => 'ArrayRef[Paws::SageMaker::CategoricalParameter]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMaker::EnvironmentParameterRanges

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMaker::EnvironmentParameterRanges object:

  $service_obj->Method(Att1 => { CategoricalParameterRanges => $value, ..., CategoricalParameterRanges => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMaker::EnvironmentParameterRanges object:

  $result = $service_obj->Method(...);
  $result->Att1->CategoricalParameterRanges

=head1 DESCRIPTION

Specifies the range of environment parameters

=head1 ATTRIBUTES


=head2 CategoricalParameterRanges => ArrayRef[L<Paws::SageMaker::CategoricalParameter>]

Specified a list of parameters for each category.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMaker>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

