# Generated by default/object.tt
package Paws::SageMaker::InferenceRecommendation;
  use Moose;
  has EndpointConfiguration => (is => 'ro', isa => 'Paws::SageMaker::EndpointOutputConfiguration', required => 1);
  has InvocationEndTime => (is => 'ro', isa => 'Str');
  has InvocationStartTime => (is => 'ro', isa => 'Str');
  has Metrics => (is => 'ro', isa => 'Paws::SageMaker::RecommendationMetrics');
  has ModelConfiguration => (is => 'ro', isa => 'Paws::SageMaker::ModelConfiguration', required => 1);
  has RecommendationId => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMaker::InferenceRecommendation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMaker::InferenceRecommendation object:

  $service_obj->Method(Att1 => { EndpointConfiguration => $value, ..., RecommendationId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMaker::InferenceRecommendation object:

  $result = $service_obj->Method(...);
  $result->Att1->EndpointConfiguration

=head1 DESCRIPTION

A list of recommendations made by Amazon SageMaker Inference
Recommender.

=head1 ATTRIBUTES


=head2 B<REQUIRED> EndpointConfiguration => L<Paws::SageMaker::EndpointOutputConfiguration>

Defines the endpoint configuration parameters.


=head2 InvocationEndTime => Str

A timestamp that shows when the benchmark completed.


=head2 InvocationStartTime => Str

A timestamp that shows when the benchmark started.


=head2 Metrics => L<Paws::SageMaker::RecommendationMetrics>

The metrics used to decide what recommendation to make.


=head2 B<REQUIRED> ModelConfiguration => L<Paws::SageMaker::ModelConfiguration>

Defines the model configuration.


=head2 RecommendationId => Str

The recommendation ID which uniquely identifies each recommendation.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMaker>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

