# Generated by default/object.tt
package Paws::SageMaker::ModelRegisterSettings;
  use Moose;
  has CrossAccountModelRegisterRoleArn => (is => 'ro', isa => 'Str');
  has Status => (is => 'ro', isa => 'Str');

1;

### main pod documentation begin ###

=head1 NAME

Paws::SageMaker::ModelRegisterSettings

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SageMaker::ModelRegisterSettings object:

  $service_obj->Method(Att1 => { CrossAccountModelRegisterRoleArn => $value, ..., Status => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SageMaker::ModelRegisterSettings object:

  $result = $service_obj->Method(...);
  $result->Att1->CrossAccountModelRegisterRoleArn

=head1 DESCRIPTION

The model registry settings for the SageMaker Canvas application.

=head1 ATTRIBUTES


=head2 CrossAccountModelRegisterRoleArn => Str

The Amazon Resource Name (ARN) of the SageMaker model registry account.
Required only to register model versions created by a different
SageMaker Canvas Amazon Web Services account than the Amazon Web
Services account in which SageMaker model registry is set up.


=head2 Status => Str

Describes whether the integration to the model registry is enabled or
disabled in the Canvas application.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SageMaker>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

