# Generated by default/object.tt
package Paws::BCMPricingCalculator::BillEstimateInputUsageModificationSummary;
  use Moose;
  has AvailabilityZone => (is => 'ro', isa => 'Str', request_name => 'availabilityZone', traits => ['NameInRequest']);
  has Group => (is => 'ro', isa => 'Str', request_name => 'group', traits => ['NameInRequest']);
  has HistoricalUsage => (is => 'ro', isa => 'Paws::BCMPricingCalculator::HistoricalUsageEntity', request_name => 'historicalUsage', traits => ['NameInRequest']);
  has Id => (is => 'ro', isa => 'Str', request_name => 'id', traits => ['NameInRequest']);
  has Location => (is => 'ro', isa => 'Str', request_name => 'location', traits => ['NameInRequest']);
  has Operation => (is => 'ro', isa => 'Str', request_name => 'operation', traits => ['NameInRequest'], required => 1);
  has Quantities => (is => 'ro', isa => 'ArrayRef[Paws::BCMPricingCalculator::UsageQuantity]', request_name => 'quantities', traits => ['NameInRequest']);
  has ServiceCode => (is => 'ro', isa => 'Str', request_name => 'serviceCode', traits => ['NameInRequest'], required => 1);
  has UsageAccountId => (is => 'ro', isa => 'Str', request_name => 'usageAccountId', traits => ['NameInRequest']);
  has UsageType => (is => 'ro', isa => 'Str', request_name => 'usageType', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BCMPricingCalculator::BillEstimateInputUsageModificationSummary

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BCMPricingCalculator::BillEstimateInputUsageModificationSummary object:

  $service_obj->Method(Att1 => { AvailabilityZone => $value, ..., UsageType => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BCMPricingCalculator::BillEstimateInputUsageModificationSummary object:

  $result = $service_obj->Method(...);
  $result->Att1->AvailabilityZone

=head1 DESCRIPTION

Summarizes an input usage modification for a bill estimate.

=head1 ATTRIBUTES


=head2 AvailabilityZone => Str

The availability zone associated with this usage modification, if
applicable.


=head2 Group => Str

The group identifier for the usage modification.


=head2 HistoricalUsage => L<Paws::BCMPricingCalculator::HistoricalUsageEntity>

Historical usage data associated with this modification, if available.


=head2 Id => Str

The unique identifier of the usage modification.


=head2 Location => Str

The location associated with this usage modification.


=head2 B<REQUIRED> Operation => Str

The specific operation associated with this usage modification.


=head2 Quantities => ArrayRef[L<Paws::BCMPricingCalculator::UsageQuantity>]

The modified usage quantities.


=head2 B<REQUIRED> ServiceCode => Str

The Amazon Web Services service code for this usage modification.


=head2 UsageAccountId => Str

The Amazon Web Services account ID associated with this usage
modification.


=head2 B<REQUIRED> UsageType => Str

The type of usage being modified.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BCMPricingCalculator>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

