# Generated by default/object.tt
package Paws::Macie2::DetectedDataDetails;
  use Moose;
  has Value => (is => 'ro', isa => 'Str', request_name => 'value', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Macie2::DetectedDataDetails

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Macie2::DetectedDataDetails object:

  $service_obj->Method(Att1 => { Value => $value, ..., Value => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Macie2::DetectedDataDetails object:

  $result = $service_obj->Method(...);
  $result->Att1->Value

=head1 DESCRIPTION

Specifies 1-10 occurrences of a specific type of sensitive data
reported by a finding.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Value => Str

An occurrence of the specified type of sensitive data. Each occurrence
contains 1-128 characters.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Macie2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

