# Generated by default/object.tt
package Paws::SocialMessaging::WhatsAppBusinessAccountEventDestination;
  use Moose;
  has EventDestinationArn => (is => 'ro', isa => 'Str', request_name => 'eventDestinationArn', traits => ['NameInRequest'], required => 1);
  has RoleArn => (is => 'ro', isa => 'Str', request_name => 'roleArn', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::SocialMessaging::WhatsAppBusinessAccountEventDestination

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::SocialMessaging::WhatsAppBusinessAccountEventDestination object:

  $service_obj->Method(Att1 => { EventDestinationArn => $value, ..., RoleArn => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::SocialMessaging::WhatsAppBusinessAccountEventDestination object:

  $result = $service_obj->Method(...);
  $result->Att1->EventDestinationArn

=head1 DESCRIPTION

Contains information on the event destination.

=head1 ATTRIBUTES


=head2 B<REQUIRED> EventDestinationArn => Str

The ARN of the event destination.


=head2 RoleArn => Str

The Amazon Resource Name (ARN) of an Identity and Access Management
role that is able to import phone numbers and write events.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::SocialMessaging>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

