
package Paws::AppSync::ListTypesByAssociation;
  use Moose;
  has AssociationId => (is => 'ro', isa => 'Str', traits => ['ParamInURI'], uri_name => 'associationId', required => 1);
  has Format => (is => 'ro', isa => 'Str', traits => ['ParamInQuery'], query_name => 'format', required => 1);
  has MaxResults => (is => 'ro', isa => 'Int', traits => ['ParamInQuery'], query_name => 'maxResults');
  has MergedApiIdentifier => (is => 'ro', isa => 'Str', traits => ['ParamInURI'], uri_name => 'mergedApiIdentifier', required => 1);
  has NextToken => (is => 'ro', isa => 'Str', traits => ['ParamInQuery'], query_name => 'nextToken');

  use MooseX::ClassAttribute;

  class_has _api_call => (isa => 'Str', is => 'ro', default => 'ListTypesByAssociation');
  class_has _api_uri  => (isa => 'Str', is => 'ro', default => '/v1/mergedApis/{mergedApiIdentifier}/sourceApiAssociations/{associationId}/types');
  class_has _api_method  => (isa => 'Str', is => 'ro', default => 'GET');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::AppSync::ListTypesByAssociationResponse');
1;

### main pod documentation begin ###

=head1 NAME

Paws::AppSync::ListTypesByAssociation - Arguments for method ListTypesByAssociation on L<Paws::AppSync>

=head1 DESCRIPTION

This class represents the parameters used for calling the method ListTypesByAssociation on the
L<AWS AppSync|Paws::AppSync> service. Use the attributes of this class
as arguments to method ListTypesByAssociation.

You shouldn't make instances of this class. Each attribute should be used as a named argument in the call to ListTypesByAssociation.

=head1 SYNOPSIS

    my $appsync = Paws->service('AppSync');
    my $ListTypesByAssociationResponse = $appsync->ListTypesByAssociation(
      AssociationId       => 'MyString',
      Format              => 'SDL',
      MergedApiIdentifier => 'MyString',
      MaxResults          => 1,                      # OPTIONAL
      NextToken           => 'MyPaginationToken',    # OPTIONAL
    );

    # Results:
    my $NextToken = $ListTypesByAssociationResponse->NextToken;
    my $Types     = $ListTypesByAssociationResponse->Types;

    # Returns a L<Paws::AppSync::ListTypesByAssociationResponse> object.

Values for attributes that are native types (Int, String, Float, etc) can passed as-is (scalar values). Values for complex Types (objects) can be passed as a HashRef. The keys and values of the hashref will be used to instance the underlying object.
For the AWS API documentation, see L<https://docs.aws.amazon.com/goto/WebAPI/appsync/ListTypesByAssociation>

=head1 ATTRIBUTES


=head2 B<REQUIRED> AssociationId => Str

The ID generated by the AppSync service for the source API association.



=head2 B<REQUIRED> Format => Str

The format type.

Valid values are: C<"SDL">, C<"JSON">

=head2 MaxResults => Int

The maximum number of results that you want the request to return.



=head2 B<REQUIRED> MergedApiIdentifier => Str

The identifier of the AppSync Merged API. This is generated by the
AppSync service. In most cases, Merged APIs (especially in your
account) only require the API ID value or ARN of the merged API.
However, Merged APIs in other accounts (cross-account use cases)
strictly require the full resource ARN of the merged API.



=head2 NextToken => Str

An identifier that was returned from the previous call to this
operation, which you can use to return the next set of items in the
list.




=head1 SEE ALSO

This class forms part of L<Paws>, documenting arguments for method ListTypesByAssociation in L<Paws::AppSync>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

