# Generated by default/object.tt
package Paws::Deadline::StepDetailsEntity;
  use Moose;
  has Dependencies => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'dependencies', traits => ['NameInRequest'], required => 1);
  has JobId => (is => 'ro', isa => 'Str', request_name => 'jobId', traits => ['NameInRequest'], required => 1);
  has SchemaVersion => (is => 'ro', isa => 'Str', request_name => 'schemaVersion', traits => ['NameInRequest'], required => 1);
  has StepId => (is => 'ro', isa => 'Str', request_name => 'stepId', traits => ['NameInRequest'], required => 1);
  has Template => (is => 'ro', isa => 'Paws::Deadline::Document', request_name => 'template', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Deadline::StepDetailsEntity

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Deadline::StepDetailsEntity object:

  $service_obj->Method(Att1 => { Dependencies => $value, ..., Template => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Deadline::StepDetailsEntity object:

  $result = $service_obj->Method(...);
  $result->Att1->Dependencies

=head1 DESCRIPTION

The details of a step entity.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Dependencies => ArrayRef[Str|Undef]

The dependencies for a step.


=head2 B<REQUIRED> JobId => Str

The job ID.


=head2 B<REQUIRED> SchemaVersion => Str

The schema version for a step template.


=head2 B<REQUIRED> StepId => Str

The step ID.


=head2 B<REQUIRED> Template => L<Paws::Deadline::Document>

The template for a step.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Deadline>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

