# Generated by default/object.tt
package Paws::Forecast::TimeSeriesTransformation;
  use Moose;
  has Action => (is => 'ro', isa => 'Paws::Forecast::Action');
  has TimeSeriesConditions => (is => 'ro', isa => 'ArrayRef[Paws::Forecast::TimeSeriesCondition]');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Forecast::TimeSeriesTransformation

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Forecast::TimeSeriesTransformation object:

  $service_obj->Method(Att1 => { Action => $value, ..., TimeSeriesConditions => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Forecast::TimeSeriesTransformation object:

  $result = $service_obj->Method(...);
  $result->Att1->Action

=head1 DESCRIPTION

A transformation function is a pair of operations that select and
modify the rows in a related time series. You select the rows that you
want with a condition operation and you modify the rows with a
transformation operation. All conditions are joined with an AND
operation, meaning that all conditions must be true for the
transformation to be applied. Transformations are applied in the order
that they are listed.

=head1 ATTRIBUTES


=head2 Action => L<Paws::Forecast::Action>

An array of actions that define a time series and how it is
transformed. These transformations create a new time series that is
used for the what-if analysis.


=head2 TimeSeriesConditions => ArrayRef[L<Paws::Forecast::TimeSeriesCondition>]

An array of conditions that define which members of the related time
series are transformed.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Forecast>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

