# Generated by default/object.tt
package Paws::Outposts::LineItemRequest;
  use Moose;
  has CatalogItemId => (is => 'ro', isa => 'Str');
  has Quantity => (is => 'ro', isa => 'Int');

1;

### main pod documentation begin ###

=head1 NAME

Paws::Outposts::LineItemRequest

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Outposts::LineItemRequest object:

  $service_obj->Method(Att1 => { CatalogItemId => $value, ..., Quantity => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Outposts::LineItemRequest object:

  $result = $service_obj->Method(...);
  $result->Att1->CatalogItemId

=head1 DESCRIPTION

Information about a line item request.

=head1 ATTRIBUTES


=head2 CatalogItemId => Str

The ID of the catalog item.


=head2 Quantity => Int

The quantity of a line item request.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Outposts>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

