# Generated by default/object.tt
package Paws::QBusiness::BlockedPhrasesConfigurationUpdate;
  use Moose;
  has BlockedPhrasesToCreateOrUpdate => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'blockedPhrasesToCreateOrUpdate', traits => ['NameInRequest']);
  has BlockedPhrasesToDelete => (is => 'ro', isa => 'ArrayRef[Str|Undef]', request_name => 'blockedPhrasesToDelete', traits => ['NameInRequest']);
  has SystemMessageOverride => (is => 'ro', isa => 'Str', request_name => 'systemMessageOverride', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::QBusiness::BlockedPhrasesConfigurationUpdate

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::QBusiness::BlockedPhrasesConfigurationUpdate object:

  $service_obj->Method(Att1 => { BlockedPhrasesToCreateOrUpdate => $value, ..., SystemMessageOverride => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::QBusiness::BlockedPhrasesConfigurationUpdate object:

  $result = $service_obj->Method(...);
  $result->Att1->BlockedPhrasesToCreateOrUpdate

=head1 DESCRIPTION

Updates a blocked phrases configuration in your Amazon Q Business
application.

=head1 ATTRIBUTES


=head2 BlockedPhrasesToCreateOrUpdate => ArrayRef[Str|Undef]

Creates or updates a blocked phrases configuration in your Amazon Q
Business application.


=head2 BlockedPhrasesToDelete => ArrayRef[Str|Undef]

Deletes a blocked phrases configuration in your Amazon Q Business
application.


=head2 SystemMessageOverride => Str

The configured custom message displayed to your end user when they use
blocked phrase during chat.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::QBusiness>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

