# Generated by default/object.tt
package Paws::QBusiness::TextOutputEvent;
  use Moose;
  has ConversationId => (is => 'ro', isa => 'Str', request_name => 'conversationId', traits => ['NameInRequest']);
  has SystemMessage => (is => 'ro', isa => 'Str', request_name => 'systemMessage', traits => ['NameInRequest']);
  has SystemMessageId => (is => 'ro', isa => 'Str', request_name => 'systemMessageId', traits => ['NameInRequest']);
  has SystemMessageType => (is => 'ro', isa => 'Str', request_name => 'systemMessageType', traits => ['NameInRequest']);
  has UserMessageId => (is => 'ro', isa => 'Str', request_name => 'userMessageId', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::QBusiness::TextOutputEvent

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::QBusiness::TextOutputEvent object:

  $service_obj->Method(Att1 => { ConversationId => $value, ..., UserMessageId => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::QBusiness::TextOutputEvent object:

  $result = $service_obj->Method(...);
  $result->Att1->ConversationId

=head1 DESCRIPTION

An output event for an AI-generated response in an Amazon Q Business
web experience.

=head1 ATTRIBUTES


=head2 ConversationId => Str

The identifier of the conversation with which the text output event is
associated.


=head2 SystemMessage => Str

An AI-generated message in a C<TextOutputEvent>.


=head2 SystemMessageId => Str

The identifier of an AI-generated message in a C<TextOutputEvent>.


=head2 SystemMessageType => Str

The type of AI-generated message in a C<TextOutputEvent>. Amazon Q
Business currently supports two types of messages:

=over

=item *

C<RESPONSE> - The Amazon Q Business system response.

=item *

C<GROUNDED_RESPONSE> - The corrected, hallucination-reduced, response
returned by Amazon Q Business. Available only if hallucination
reduction is supported and configured for the application and detected
in the end user chat query by Amazon Q Business.

=back



=head2 UserMessageId => Str

The identifier of an end user message in a C<TextOutputEvent>.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::QBusiness>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

