# Generated by default/object.tt
package Paws::Evidently::CloudWatchLogsDestinationConfig;
  use Moose;
  has LogGroup => (is => 'ro', isa => 'Str', request_name => 'logGroup', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Evidently::CloudWatchLogsDestinationConfig

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Evidently::CloudWatchLogsDestinationConfig object:

  $service_obj->Method(Att1 => { LogGroup => $value, ..., LogGroup => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Evidently::CloudWatchLogsDestinationConfig object:

  $result = $service_obj->Method(...);
  $result->Att1->LogGroup

=head1 DESCRIPTION

A structure containing the CloudWatch Logs log group where the project
stores evaluation events.

=head1 ATTRIBUTES


=head2 LogGroup => Str

The name of the log group where the project stores evaluation events.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Evidently>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

