# Generated by default/object.tt
package Paws::BedrockDataAutomation::VideoStandardOutputConfiguration;
  use Moose;
  has Extraction => (is => 'ro', isa => 'Paws::BedrockDataAutomation::VideoStandardExtraction', request_name => 'extraction', traits => ['NameInRequest']);
  has GenerativeField => (is => 'ro', isa => 'Paws::BedrockDataAutomation::VideoStandardGenerativeField', request_name => 'generativeField', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::BedrockDataAutomation::VideoStandardOutputConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::BedrockDataAutomation::VideoStandardOutputConfiguration object:

  $service_obj->Method(Att1 => { Extraction => $value, ..., GenerativeField => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::BedrockDataAutomation::VideoStandardOutputConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->Extraction

=head1 DESCRIPTION

Standard Output Configuration of Video

=head1 ATTRIBUTES


=head2 Extraction => L<Paws::BedrockDataAutomation::VideoStandardExtraction>




=head2 GenerativeField => L<Paws::BedrockDataAutomation::VideoStandardGenerativeField>





=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::BedrockDataAutomation>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

