# Generated by default/object.tt
package Paws::Drs::PITPolicyRule;
  use Moose;
  has Enabled => (is => 'ro', isa => 'Bool', request_name => 'enabled', traits => ['NameInRequest']);
  has Interval => (is => 'ro', isa => 'Int', request_name => 'interval', traits => ['NameInRequest'], required => 1);
  has RetentionDuration => (is => 'ro', isa => 'Int', request_name => 'retentionDuration', traits => ['NameInRequest'], required => 1);
  has RuleID => (is => 'ro', isa => 'Int', request_name => 'ruleID', traits => ['NameInRequest']);
  has Units => (is => 'ro', isa => 'Str', request_name => 'units', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::Drs::PITPolicyRule

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::Drs::PITPolicyRule object:

  $service_obj->Method(Att1 => { Enabled => $value, ..., Units => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::Drs::PITPolicyRule object:

  $result = $service_obj->Method(...);
  $result->Att1->Enabled

=head1 DESCRIPTION

A rule in the Point in Time (PIT) policy representing when to take
snapshots and how long to retain them for.

=head1 ATTRIBUTES


=head2 Enabled => Bool

Whether this rule is enabled or not.


=head2 B<REQUIRED> Interval => Int

How often, in the chosen units, a snapshot should be taken.


=head2 B<REQUIRED> RetentionDuration => Int

The duration to retain a snapshot for, in the chosen units.


=head2 RuleID => Int

The ID of the rule.


=head2 B<REQUIRED> Units => Str

The units used to measure the interval and retentionDuration.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::Drs>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

