# Generated by default/object.tt
package Paws::VerifiedPermissions::OpenIdConnectConfiguration;
  use Moose;
  has EntityIdPrefix => (is => 'ro', isa => 'Str', request_name => 'entityIdPrefix', traits => ['NameInRequest']);
  has GroupConfiguration => (is => 'ro', isa => 'Paws::VerifiedPermissions::OpenIdConnectGroupConfiguration', request_name => 'groupConfiguration', traits => ['NameInRequest']);
  has Issuer => (is => 'ro', isa => 'Str', request_name => 'issuer', traits => ['NameInRequest'], required => 1);
  has TokenSelection => (is => 'ro', isa => 'Paws::VerifiedPermissions::OpenIdConnectTokenSelection', request_name => 'tokenSelection', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::VerifiedPermissions::OpenIdConnectConfiguration

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::VerifiedPermissions::OpenIdConnectConfiguration object:

  $service_obj->Method(Att1 => { EntityIdPrefix => $value, ..., TokenSelection => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::VerifiedPermissions::OpenIdConnectConfiguration object:

  $result = $service_obj->Method(...);
  $result->Att1->EntityIdPrefix

=head1 DESCRIPTION

Contains configuration details of an OpenID Connect (OIDC) identity
provider, or identity source, that Verified Permissions can use to
generate entities from authenticated identities. It specifies the
issuer URL, token type that you want to use, and policy store entity
details.

This data type is part of a Configuration
(https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_Configuration.html)
structure, which is a parameter to CreateIdentitySource
(https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreateIdentitySource.html).

=head1 ATTRIBUTES


=head2 EntityIdPrefix => Str

A descriptive string that you want to prefix to user entities from your
OIDC identity provider. For example, if you set an C<entityIdPrefix> of
C<MyOIDCProvider>, you can reference principals in your policies in the
format C<MyCorp::User::MyOIDCProvider|Carlos>.


=head2 GroupConfiguration => L<Paws::VerifiedPermissions::OpenIdConnectGroupConfiguration>

The claim in OIDC identity provider tokens that indicates a user's
group membership, and the entity type that you want to map it to. For
example, this object can map the contents of a C<groups> claim to
C<MyCorp::UserGroup>.


=head2 B<REQUIRED> Issuer => Str

The issuer URL of an OIDC identity provider. This URL must have an OIDC
discovery endpoint at the path C<.well-known/openid-configuration>.


=head2 B<REQUIRED> TokenSelection => L<Paws::VerifiedPermissions::OpenIdConnectTokenSelection>

The token type that you want to process from your OIDC identity
provider. Your policy store can process either identity (ID) or access
tokens from a given OIDC identity source.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::VerifiedPermissions>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

