# Generated by default/object.tt
package Paws::VerifiedPermissions::PolicyDefinitionDetail;
  use Moose;
  has Static => (is => 'ro', isa => 'Paws::VerifiedPermissions::StaticPolicyDefinitionDetail', request_name => 'static', traits => ['NameInRequest']);
  has TemplateLinked => (is => 'ro', isa => 'Paws::VerifiedPermissions::TemplateLinkedPolicyDefinitionDetail', request_name => 'templateLinked', traits => ['NameInRequest']);

1;

### main pod documentation begin ###

=head1 NAME

Paws::VerifiedPermissions::PolicyDefinitionDetail

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::VerifiedPermissions::PolicyDefinitionDetail object:

  $service_obj->Method(Att1 => { Static => $value, ..., TemplateLinked => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::VerifiedPermissions::PolicyDefinitionDetail object:

  $result = $service_obj->Method(...);
  $result->Att1->Static

=head1 DESCRIPTION

A structure that describes a policy definition. It must always have
either an C<static> or a C<templateLinked> element.

This data type is used as a response parameter for the GetPolicy
(https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetPolicy.html)
operation.

=head1 ATTRIBUTES


=head2 Static => L<Paws::VerifiedPermissions::StaticPolicyDefinitionDetail>

Information about a static policy that wasn't created with a policy
template.


=head2 TemplateLinked => L<Paws::VerifiedPermissions::TemplateLinkedPolicyDefinitionDetail>

Information about a template-linked policy that was created by
instantiating a policy template.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::VerifiedPermissions>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

