# Generated by default/object.tt
package Paws::StepFunctions::MapRunExecutionCounts;
  use Moose;
  has Aborted => (is => 'ro', isa => 'Int', request_name => 'aborted', traits => ['NameInRequest'], required => 1);
  has Failed => (is => 'ro', isa => 'Int', request_name => 'failed', traits => ['NameInRequest'], required => 1);
  has FailuresNotRedrivable => (is => 'ro', isa => 'Int', request_name => 'failuresNotRedrivable', traits => ['NameInRequest']);
  has Pending => (is => 'ro', isa => 'Int', request_name => 'pending', traits => ['NameInRequest'], required => 1);
  has PendingRedrive => (is => 'ro', isa => 'Int', request_name => 'pendingRedrive', traits => ['NameInRequest']);
  has ResultsWritten => (is => 'ro', isa => 'Int', request_name => 'resultsWritten', traits => ['NameInRequest'], required => 1);
  has Running => (is => 'ro', isa => 'Int', request_name => 'running', traits => ['NameInRequest'], required => 1);
  has Succeeded => (is => 'ro', isa => 'Int', request_name => 'succeeded', traits => ['NameInRequest'], required => 1);
  has TimedOut => (is => 'ro', isa => 'Int', request_name => 'timedOut', traits => ['NameInRequest'], required => 1);
  has Total => (is => 'ro', isa => 'Int', request_name => 'total', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::StepFunctions::MapRunExecutionCounts

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::StepFunctions::MapRunExecutionCounts object:

  $service_obj->Method(Att1 => { Aborted => $value, ..., Total => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::StepFunctions::MapRunExecutionCounts object:

  $result = $service_obj->Method(...);
  $result->Att1->Aborted

=head1 DESCRIPTION

Contains details about all of the child workflow executions started by
a Map Run.

=head1 ATTRIBUTES


=head2 B<REQUIRED> Aborted => Int

The total number of child workflow executions that were started by a
Map Run and were running, but were either stopped by the user or by
Step Functions because the Map Run failed.


=head2 B<REQUIRED> Failed => Int

The total number of child workflow executions that were started by a
Map Run, but have failed.


=head2 FailuresNotRedrivable => Int

The number of C<FAILED>, C<ABORTED>, or C<TIMED_OUT> child workflow
executions that cannot be redriven because their execution status is
terminal. For example, child workflows with an execution status of
C<FAILED>, C<ABORTED>, or C<TIMED_OUT> and a C<redriveStatus> of
C<NOT_REDRIVABLE>.


=head2 B<REQUIRED> Pending => Int

The total number of child workflow executions that were started by a
Map Run, but haven't started executing yet.


=head2 PendingRedrive => Int

The number of unsuccessful child workflow executions currently waiting
to be redriven. The status of these child workflow executions could be
C<FAILED>, C<ABORTED>, or C<TIMED_OUT> in the original execution
attempt or a previous redrive attempt.


=head2 B<REQUIRED> ResultsWritten => Int

Returns the count of child workflow executions whose results were
written by C<ResultWriter>. For more information, see ResultWriter
(https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultwriter.html)
in the I<Step Functions Developer Guide>.


=head2 B<REQUIRED> Running => Int

The total number of child workflow executions that were started by a
Map Run and are currently in-progress.


=head2 B<REQUIRED> Succeeded => Int

The total number of child workflow executions that were started by a
Map Run and have completed successfully.


=head2 B<REQUIRED> TimedOut => Int

The total number of child workflow executions that were started by a
Map Run and have timed out.


=head2 B<REQUIRED> Total => Int

The total number of child workflow executions that were started by a
Map Run.



=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::StepFunctions>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

